package main

import (
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
	"ph_holdings_app/pkg/finance/posting"
)

func (a *App) PreviewCustomerInvoicePosting(invoiceID string) (posting.Entry, error) {
	if err := a.requirePermission("finance:view"); err != nil {
		return posting.Entry{}, err
	}
	if a.db == nil {
		return posting.Entry{}, newError("DB_NOT_INITIALIZED", "Database connection not available", "")
	}

	entry, _, err := a.previewPostingEntry(a.db, posting.SourceCustomerInvoice, invoiceID)
	return entry, err
}

func (a *App) PreviewCustomerPaymentPosting(paymentID string) (posting.Entry, error) {
	if err := a.requirePermission("finance:view"); err != nil {
		return posting.Entry{}, err
	}
	if a.db == nil {
		return posting.Entry{}, newError("DB_NOT_INITIALIZED", "Database connection not available", "")
	}

	entry, _, err := a.previewPostingEntry(a.db, posting.SourceCustomerPayment, paymentID)
	return entry, err
}

func (a *App) PreviewSupplierInvoicePosting(invoiceID string) (posting.Entry, error) {
	if err := a.requirePermission("finance:view"); err != nil {
		return posting.Entry{}, err
	}
	if a.db == nil {
		return posting.Entry{}, newError("DB_NOT_INITIALIZED", "Database connection not available", "")
	}

	entry, _, err := a.previewPostingEntry(a.db, posting.SourceSupplierInvoice, invoiceID)
	return entry, err
}

func (a *App) PreviewSupplierPaymentPosting(paymentID string) (posting.Entry, error) {
	if err := a.requirePermission("finance:view"); err != nil {
		return posting.Entry{}, err
	}
	if a.db == nil {
		return posting.Entry{}, newError("DB_NOT_INITIALIZED", "Database connection not available", "")
	}

	entry, _, err := a.previewPostingEntry(a.db, posting.SourceSupplierPayment, paymentID)
	return entry, err
}

func (a *App) CreateDraftJournalFromPosting(sourceType string, sourceID string) (*JournalEntry, error) {
	if err := a.requirePermission("finance:create"); err != nil {
		return nil, err
	}
	if a.db == nil {
		return nil, newError("DB_NOT_INITIALIZED", "Database connection not available", "")
	}

	sourceType = strings.TrimSpace(sourceType)
	sourceID = strings.TrimSpace(sourceID)
	if sourceType == "" || sourceID == "" {
		return nil, fmt.Errorf("source type and source id are required")
	}

	var created JournalEntry
	err := a.db.Transaction(func(tx *gorm.DB) error {
		entry, linkedJournalID, err := a.previewPostingEntry(tx, sourceType, sourceID)
		if err != nil {
			return err
		}

		if linkedJournalID != "" {
			if err := tx.Preload("Lines").First(&created, "id = ?", linkedJournalID).Error; err != nil {
				return fmt.Errorf("source is linked to missing journal entry %s: %w", linkedJournalID, err)
			}
			return nil
		}

		var existing JournalEntry
		if err := tx.Preload("Lines").
			Where("source_type = ? AND source_id = ? AND deleted_at IS NULL", sourceType, sourceID).
			First(&existing).Error; err == nil {
			if err := a.linkPostingSource(tx, sourceType, sourceID, existing.ID); err != nil {
				return err
			}
			created = existing
			return nil
		} else if err != gorm.ErrRecordNotFound {
			return fmt.Errorf("check existing journal entry: %w", err)
		}

		now := time.Now()
		entryDate := entry.EntryDate
		if entryDate.IsZero() {
			entryDate = now
		}
		journal := JournalEntry{
			Base:            Base{ID: uuid.New().String(), CreatedBy: a.getCurrentUserID(), CreatedAt: now, UpdatedAt: now},
			EntryNumber:     a.nextAutoJournalNumber(tx, entryDate.Year()),
			EntryDate:       entryDate,
			Description:     entry.Description,
			DebitTotal:      entry.DebitTotal,
			CreditTotal:     entry.CreditTotal,
			IsPosted:        false,
			FiscalYear:      entryDate.Year(),
			FiscalPeriod:    int(entryDate.Month()),
			SourceType:      sourceType,
			SourceID:        sourceID,
			IsAutoGenerated: true,
			UpdatedBy:       a.getCurrentUserID(),
		}

		if err := tx.Create(&journal).Error; err != nil {
			return fmt.Errorf("create draft journal entry: %w", err)
		}

		lines := make([]JournalLine, 0, len(entry.Lines))
		for _, previewLine := range entry.Lines {
			account, err := a.resolvePostingAccount(tx, previewLine.Account)
			if err != nil {
				return err
			}
			lines = append(lines, JournalLine{
				Base:        Base{ID: uuid.New().String(), CreatedBy: a.getCurrentUserID(), CreatedAt: now, UpdatedAt: now},
				EntryID:     journal.ID,
				AccountID:   account.ID,
				AccountName: account.AccountName,
				Debit:       previewLine.Debit,
				Credit:      previewLine.Credit,
				Description: previewLine.Memo,
				UpdatedBy:   a.getCurrentUserID(),
			})
		}
		if err := tx.Create(&lines).Error; err != nil {
			return fmt.Errorf("create draft journal lines: %w", err)
		}
		if err := a.linkPostingSource(tx, sourceType, sourceID, journal.ID); err != nil {
			return err
		}

		created = journal
		created.Lines = lines
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &created, nil
}

func (a *App) previewPostingEntry(db *gorm.DB, sourceType string, sourceID string) (posting.Entry, string, error) {
	switch strings.TrimSpace(sourceType) {
	case posting.SourceCustomerInvoice:
		var invoice Invoice
		if err := db.First(&invoice, "id = ?", sourceID).Error; err != nil {
			return posting.Entry{}, "", fmt.Errorf("customer invoice not found: %w", err)
		}
		entry, err := posting.CustomerInvoicePreview(posting.SourceDocument{
			ID:          invoice.ID,
			Number:      invoice.InvoiceNumber,
			PartyID:     invoice.CustomerID,
			PartyName:   invoice.CustomerName,
			Date:        invoice.InvoiceDate,
			Currency:    posting.DefaultCurrency,
			SubtotalBHD: invoice.SubtotalBHD,
			VATBHD:      invoice.VATBHD,
			TotalBHD:    invoice.GrandTotalBHD,
			Division:    invoice.Division,
			Reference:   invoice.CustomerPONumber,
		})
		return entry, invoice.JournalEntryID, err
	case posting.SourceCustomerPayment:
		var payment Payment
		if err := db.First(&payment, "id = ?", sourceID).Error; err != nil {
			return posting.Entry{}, "", fmt.Errorf("customer payment not found: %w", err)
		}
		entry, err := posting.CustomerPaymentPreview(posting.SourceDocument{
			ID:        payment.ID,
			Number:    payment.InvoiceNumber,
			Date:      payment.PaymentDate,
			Currency:  posting.DefaultCurrency,
			TotalBHD:  payment.AmountBHD,
			Division:  payment.Division,
			Reference: payment.Reference,
		})
		return entry, payment.JournalEntryID, err
	case posting.SourceSupplierInvoice:
		var invoice SupplierInvoice
		if err := db.First(&invoice, "id = ?", sourceID).Error; err != nil {
			return posting.Entry{}, "", fmt.Errorf("supplier invoice not found: %w", err)
		}
		entry, err := posting.SupplierInvoicePreview(posting.SourceDocument{
			ID:          invoice.ID,
			Number:      invoice.InvoiceNumber,
			PartyID:     invoice.SupplierID,
			PartyName:   invoice.SupplierName,
			Date:        invoice.InvoiceDate,
			Currency:    invoice.Currency,
			SubtotalBHD: invoice.SubtotalBHD,
			VATBHD:      invoice.VATBHD,
			TotalBHD:    invoice.TotalBHD,
			Division:    invoice.Division,
			Reference:   invoice.PONumber,
		})
		return entry, invoice.JournalEntryID, err
	case posting.SourceSupplierPayment:
		var payment SupplierPayment
		if err := db.First(&payment, "id = ?", sourceID).Error; err != nil {
			return posting.Entry{}, "", fmt.Errorf("supplier payment not found: %w", err)
		}
		entry, err := posting.SupplierPaymentPreview(posting.SourceDocument{
			ID:        payment.ID,
			Number:    payment.InvoiceNumber,
			PartyID:   payment.SupplierID,
			PartyName: payment.SupplierName,
			Date:      payment.PaymentDate,
			Currency:  payment.Currency,
			TotalBHD:  payment.AmountBHD,
			Division:  payment.Division,
			Reference: payment.Reference,
		})
		return entry, payment.JournalEntryID, err
	default:
		return posting.Entry{}, "", fmt.Errorf("unsupported posting source type %q", sourceType)
	}
}

func (a *App) linkPostingSource(tx *gorm.DB, sourceType string, sourceID string, journalEntryID string) error {
	switch sourceType {
	case posting.SourceCustomerInvoice:
		return tx.Model(&Invoice{}).Where("id = ?", sourceID).Update("journal_entry_id", journalEntryID).Error
	case posting.SourceCustomerPayment:
		return tx.Model(&Payment{}).Where("id = ?", sourceID).Update("journal_entry_id", journalEntryID).Error
	case posting.SourceSupplierInvoice:
		return tx.Model(&SupplierInvoice{}).Where("id = ?", sourceID).Update("journal_entry_id", journalEntryID).Error
	case posting.SourceSupplierPayment:
		return tx.Model(&SupplierPayment{}).Where("id = ?", sourceID).Update("journal_entry_id", journalEntryID).Error
	default:
		return fmt.Errorf("unsupported posting source type %q", sourceType)
	}
}

func (a *App) nextAutoJournalNumber(tx *gorm.DB, fiscalYear int) string {
	var count int64
	tx.Model(&JournalEntry{}).Where("fiscal_year = ?", fiscalYear).Count(&count)
	return fmt.Sprintf("AUTO-JE-%d-%06d", fiscalYear, count+1)
}

func (a *App) resolvePostingAccount(tx *gorm.DB, ref posting.AccountRef) (ChartOfAccount, error) {
	if tx.Migrator().HasTable(&AccountMapping{}) {
		candidates := postingRoleMappingKeys(ref.Role)
		if len(candidates) > 0 {
			var mapping AccountMapping
			err := tx.Where("is_active = ? AND lower(transaction_type) IN ?", true, candidates).
				Order("updated_at DESC").
				First(&mapping).Error
			if err == nil {
				if account, found := findMappedPostingAccount(tx, mapping); found {
					return account, nil
				}
			} else if err != gorm.ErrRecordNotFound {
				return ChartOfAccount{}, fmt.Errorf("resolve account mapping for %s: %w", ref.Role, err)
			}
		}
	}

	accountType := postingAccountType(ref.Role)
	if accountType == "" {
		return ChartOfAccount{}, fmt.Errorf("no account type configured for posting role %q", ref.Role)
	}
	return ensurePostingAccountTx(tx, ref.Code, ref.Name, accountType)
}

func findMappedPostingAccount(tx *gorm.DB, mapping AccountMapping) (ChartOfAccount, bool) {
	var account ChartOfAccount
	if strings.TrimSpace(mapping.AccountID) != "" {
		if err := tx.Where("id = ? AND is_active = ? AND deleted_at IS NULL", mapping.AccountID, true).First(&account).Error; err == nil {
			return account, true
		}
	}
	if strings.TrimSpace(mapping.AccountCode) != "" {
		if err := tx.Where("account_code = ? AND is_active = ? AND deleted_at IS NULL", mapping.AccountCode, true).First(&account).Error; err == nil {
			return account, true
		}
	}
	return ChartOfAccount{}, false
}

func ensurePostingAccountTx(tx *gorm.DB, code string, name string, accountType string) (ChartOfAccount, error) {
	code = strings.TrimSpace(code)
	name = strings.TrimSpace(name)
	if code == "" || name == "" {
		return ChartOfAccount{}, fmt.Errorf("posting account code and name are required")
	}
	var account ChartOfAccount
	if err := tx.Where("account_code = ? AND deleted_at IS NULL", code).First(&account).Error; err == nil {
		return account, nil
	} else if err != gorm.ErrRecordNotFound {
		return ChartOfAccount{}, fmt.Errorf("load posting account %s: %w", code, err)
	}
	now := time.Now()
	account = ChartOfAccount{
		Base:        Base{ID: uuid.New().String(), CreatedBy: "system", CreatedAt: now, UpdatedAt: now},
		AccountCode: code,
		AccountName: name,
		AccountType: accountType,
		IsActive:    true,
	}
	if err := tx.Create(&account).Error; err != nil {
		return ChartOfAccount{}, fmt.Errorf("create posting account %s: %w", code, err)
	}
	return account, nil
}

func postingRoleMappingKeys(role posting.AccountRole) []string {
	switch role {
	case posting.RoleAccountsReceivable:
		return []string{"accounts_receivable", "ar"}
	case posting.RoleAccountsPayable:
		return []string{"accounts_payable", "ap"}
	case posting.RoleBank:
		return []string{"bank", "cash"}
	case posting.RoleRevenue:
		return []string{"revenue", "sales"}
	case posting.RolePurchases:
		return []string{"purchases", "cogs"}
	case posting.RoleVATOutput:
		return []string{"vat_output", "output_vat"}
	case posting.RoleVATInput:
		return []string{"vat_input", "input_vat"}
	default:
		return nil
	}
}

func postingAccountType(role posting.AccountRole) string {
	switch role {
	case posting.RoleAccountsReceivable, posting.RoleBank, posting.RoleVATInput:
		return "Asset"
	case posting.RoleAccountsPayable, posting.RoleVATOutput:
		return "Liability"
	case posting.RoleRevenue:
		return "Revenue"
	case posting.RolePurchases:
		return "Expense"
	default:
		return ""
	}
}

func (a *App) GetTrialBalanceGate(fiscalYear int, fiscalPeriod int) (posting.TrialBalanceGate, error) {
	if err := a.requirePermission("finance:view"); err != nil {
		return posting.TrialBalanceGate{}, err
	}
	if a.db == nil {
		return posting.TrialBalanceGate{}, newError("DB_NOT_INITIALIZED", "Database connection not available", "")
	}

	var entries []JournalEntry
	query := a.db.Preload("Lines").Where("deleted_at IS NULL AND is_posted = ?", true)
	if fiscalYear > 0 {
		query = query.Where("fiscal_year = ?", fiscalYear)
	}
	if fiscalPeriod > 0 {
		query = query.Where("fiscal_period = ?", fiscalPeriod)
	}
	if err := query.Find(&entries).Error; err != nil {
		return posting.TrialBalanceGate{}, fmt.Errorf("load posted journal entries: %w", err)
	}

	accountIDs := make([]string, 0)
	seen := map[string]bool{}
	for _, entry := range entries {
		for _, line := range entry.Lines {
			accountID := strings.TrimSpace(line.AccountID)
			if accountID != "" && !seen[accountID] {
				seen[accountID] = true
				accountIDs = append(accountIDs, accountID)
			}
		}
	}

	accountsByID := map[string]ChartOfAccount{}
	if len(accountIDs) > 0 {
		var accounts []ChartOfAccount
		if err := a.db.Where("id IN ?", accountIDs).Find(&accounts).Error; err != nil {
			return posting.TrialBalanceGate{}, fmt.Errorf("load chart accounts: %w", err)
		}
		for _, account := range accounts {
			accountsByID[account.ID] = account
		}
	}

	postedEntries := make([]posting.PostedJournalEntry, 0, len(entries))
	for _, entry := range entries {
		postedEntry := posting.PostedJournalEntry{
			ID:          entry.ID,
			EntryNumber: entry.EntryNumber,
			SourceType:  entry.SourceType,
			SourceID:    entry.SourceID,
			Lines:       make([]posting.PostedJournalLine, 0, len(entry.Lines)),
		}
		for _, line := range entry.Lines {
			account := posting.AccountRef{Name: line.AccountName}
			if chartAccount, ok := accountsByID[line.AccountID]; ok {
				account.Code = chartAccount.AccountCode
				account.Name = chartAccount.AccountName
			}
			postedEntry.Lines = append(postedEntry.Lines, posting.PostedJournalLine{
				Account: account,
				Debit:   line.Debit,
				Credit:  line.Credit,
			})
		}
		postedEntries = append(postedEntries, postedEntry)
	}

	return posting.BuildTrialBalanceGate(fiscalYear, fiscalPeriod, postedEntries), nil
}

func (a *App) GetPostingCoverageReport() (posting.CoverageReport, error) {
	if err := a.requirePermission("finance:view"); err != nil {
		return posting.CoverageReport{}, err
	}
	if a.db == nil {
		return posting.CoverageReport{}, newError("DB_NOT_INITIALIZED", "Database connection not available", "")
	}

	sourceRows := []struct {
		sourceType string
		label      string
		model      any
		query      string
		args       []any
	}{
		{posting.SourceCustomerInvoice, "Customer Invoices", &Invoice{}, "status IN ? AND grand_total_bhd > 0", []any{[]string{"Sent", "Paid", "PartiallyPaid", "Overdue"}}},
		{posting.SourceCustomerPayment, "Customer Payments", &Payment{}, "amount_bhd > 0", nil},
		{posting.SourceSupplierInvoice, "Supplier Invoices", &SupplierInvoice{}, "status IN ? AND total_bhd > 0", []any{[]string{"Approved", "Paid"}}},
		{posting.SourceSupplierPayment, "Supplier Payments", &SupplierPayment{}, "amount_bhd > 0", nil},
	}
	rows := make([]posting.CoverageRow, 0, len(sourceRows))
	for _, source := range sourceRows {
		row, err := a.postingCoverageRow(source.sourceType, source.label, source.model, source.query, source.args...)
		if err != nil {
			return posting.CoverageReport{}, err
		}
		rows = append(rows, row)
	}
	return posting.BuildCoverageReport(rows), nil
}

func (a *App) postingCoverageRow(sourceType string, label string, model any, query string, args ...any) (posting.CoverageRow, error) {
	var total, linked, draftEntries int64
	if err := a.db.Model(model).Where(query, args...).Count(&total).Error; err != nil {
		return posting.CoverageRow{}, fmt.Errorf("count posting coverage for %s: %w", label, err)
	}
	if err := a.db.Model(model).Where(query, args...).Where("journal_entry_id <> ''").Count(&linked).Error; err != nil {
		return posting.CoverageRow{}, fmt.Errorf("count linked posting coverage for %s: %w", label, err)
	}
	if err := a.db.Model(&JournalEntry{}).
		Where("source_type = ? AND deleted_at IS NULL", sourceType).
		Count(&draftEntries).Error; err != nil {
		return posting.CoverageRow{}, fmt.Errorf("count draft journal coverage for %s: %w", label, err)
	}
	return posting.CoverageRow{
		SourceType:   sourceType,
		Label:        label,
		Total:        total,
		Linked:       linked,
		DraftEntries: draftEntries,
	}, nil
}
