package main

import (
	"fmt"

	"ph_holdings_app/pkg/compliance/india"
)

// This file is the India Spec-01 B6 mission: the e-invoicing (IRN/QR)
// applicability indicator. G8 puts e-invoicing itself OUT of this wave —
// the threshold has moved five times historically, and the free portal
// path covers below-threshold businesses entirely. This is a cheap,
// honest, display-only read so IN-W3 has a clean mount point. It changes
// no behavior anywhere: nothing blocks on Applicable, and no IRN/QR is
// generated by this file or anything it calls.

// EInvoiceApplicability is the display-only e-invoicing applicability read.
// When Mounted is false the India GST plane isn't configured at all and
// every other field is meaningless.
type EInvoiceApplicability struct {
	Mounted bool `json:"mounted"`

	// Applicable is true when AATOINR exceeds ThresholdINR (§0 G8: "AATO >
	// ₹5cr", strictly greater, matching india.AATOTier's boundary handling).
	Applicable bool `json:"applicable"`

	// ThresholdINR is the configured (never hardcoded, §0 config-not-constant)
	// AATO boundary above which e-invoicing applies.
	ThresholdINR float64 `json:"threshold_inr"`

	// AATOINR is the AATO figure used to evaluate Applicable.
	AATOINR float64 `json:"aato_inr"`

	// AATOSource is "override" when AATOINR came from the overlay's
	// AATOOverrideINR, or "unknown" when no in-app turnover figure exists
	// yet — this wave has no invoice-history roll-up, so the computed AATO
	// india.ResolveAATO falls back to is always 0 until a later wave wires
	// a real pkg/compliance/india.AATOSource implementation in.
	AATOSource string `json:"aato_source"`

	// Message is the honest, human-readable sentence for display next to
	// the indicator — never silently blank.
	Message string `json:"message"`
}

// GetEInvoiceApplicability is the Wails-bound, display-only read of the G8
// e-invoicing applicability indicator. Guarded by requirePermission and
// degrading to a safe zero-ish value on denial rather than erroring, same
// convention as GetBusinessVATRate (app_setup_documents_surface.go) — the
// closest sibling overlay-config getter, itself a plain-value (no error)
// Wails-bound method.
func (a *App) GetEInvoiceApplicability() EInvoiceApplicability {
	if err := a.requirePermission("settings:view"); err != nil {
		return EInvoiceApplicability{Message: "permission denied"}
	}

	if !activeOverlay.IndiaMounted() {
		return EInvoiceApplicability{Message: "India GST plane not mounted"}
	}

	cfg := activeOverlay.IndiaConfig()
	threshold := cfg.EInvoiceThresholdAATO
	// No invoice-history roll-up exists yet (pkg/compliance/india/aato.go's
	// AATOSource interface awaits a document-store implementation in a
	// later wave), so the computed figure is always 0 this wave — ResolveAATO
	// only ever resolves the override.
	aato := india.ResolveAATO(0, cfg.AATOOverrideINR)
	applicable := aato > threshold

	source := "unknown"
	if cfg.AATOOverrideINR > 0 {
		source = "override"
	}

	var message string
	switch {
	case source == "unknown":
		message = fmt.Sprintf(
			"e-invoicing applies above ₹%s AATO — this deployment's turnover is not yet computed in-app; set the AATO override in the overlay to activate this indicator",
			indianDigitGrouping(threshold),
		)
	case !applicable:
		message = "e-invoicing (IRN/QR) not applicable at current AATO — integration arrives in a later wave"
	default:
		message = "e-invoicing (IRN/QR) APPLICABLE at current AATO — integration pending (IN-W3); invoices remain valid for below-threshold filing paths"
	}

	return EInvoiceApplicability{
		Mounted:      true,
		Applicable:   applicable,
		ThresholdINR: threshold,
		AATOINR:      aato,
		AATOSource:   source,
		Message:      message,
	}
}
