package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/signintech/gopdf"
)

// ReportType defines the type of report to generate
type ReportType string

const (
	ReportDashboard         ReportType = "dashboard"
	ReportPredictionHistory ReportType = "prediction_history"
	ReportCustomer360       ReportType = "customer_360"
)

// ReportGenerator handles PDF report generation for business intelligence
type ReportGenerator struct {
	pdf            *gopdf.GoPdf
	pageWidth      float64 // A4 = 595 points
	pageHeight     float64 // A4 = 842 points
	letterheadPath string  // Path to letterhead image (set by App)
}

// NewReportGenerator creates a new report generator with professional styling
func NewReportGenerator() *ReportGenerator {
	pdf := &gopdf.GoPdf{}
	pdf.Start(gopdf.Config{PageSize: *gopdf.PageSizeA4})

	return &ReportGenerator{
		pdf:        pdf,
		pageWidth:  595.0,
		pageHeight: 842.0,
	}
}

// drawLetterhead draws the Acme Instrumentation letterhead background on the current page
func (g *ReportGenerator) drawLetterhead() {
	if g.letterheadPath == "" {
		return
	}
	if _, err := os.Stat(g.letterheadPath); err != nil {
		return
	}
	// Draw letterhead as full-page background (A4: 595 x 842 points)
	g.pdf.Image(g.letterheadPath, 0, 0, &gopdf.Rect{W: g.pageWidth, H: g.pageHeight})
}

// loadFonts loads Arial (Windows default) for clean professional output
func (g *ReportGenerator) loadFonts() error {
	// Try multiple font paths for cross-platform compatibility
	fontPaths := []string{
		"C:/Windows/Fonts/arial.ttf",                      // Windows
		"/System/Library/Fonts/Supplemental/Arial.ttf",    // macOS
		"/Library/Fonts/Arial.ttf",                        // macOS (user-installed)
		"/System/Library/Fonts/Helvetica.ttc",             // macOS (built-in)
		"/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", // Linux
	}

	fontLoaded := false
	for _, fontPath := range fontPaths {
		if fileExists(fontPath) {
			err := g.pdf.AddTTFFont("report", fontPath)
			if err == nil {
				fontLoaded = true
				break
			}
		}
	}

	if !fontLoaded {
		return fmt.Errorf("could not load any fonts - tried: %v", fontPaths)
	}

	return nil
}

// drawHeader draws the Acme Instrumentation header - uses letterhead if available, falls back to navy bar
func (g *ReportGenerator) drawHeader(title, subtitle string) {
	if g.letterheadPath != "" {
		// Use letterhead background
		g.drawLetterhead()

		// Report title overlay (below letterhead header area ~135pt)
		g.pdf.SetTextColor(30, 58, 138) // Navy
		g.pdf.SetFont("report", "", 14)
		g.pdf.SetXY(40, 140)
		g.pdf.Cell(nil, title)

		// Date (right side)
		dateStr := time.Now().Format("January 2, 2006")
		g.pdf.SetFont("report", "", 9)
		g.pdf.SetTextColor(100, 100, 100)
		g.pdf.SetXY(g.pageWidth-150, 140)
		g.pdf.Cell(nil, dateStr)

		// Reset
		g.pdf.SetTextColor(0, 0, 0)

		if subtitle != "" {
			g.pdf.SetFont("report", "", 10)
			g.pdf.SetTextColor(100, 100, 100)
			g.pdf.SetXY(40, 155)
			g.pdf.Cell(nil, subtitle)
			g.pdf.SetTextColor(0, 0, 0)
		}
	} else {
		// Fallback: Navy header bar (0-50pt height)
		g.pdf.SetFillColor(30, 58, 138) // Navy
		g.pdf.RectFromUpperLeftWithStyle(0, 0, g.pageWidth, 50, "F")

		// Company name (white)
		g.pdf.SetTextColor(255, 255, 255)
		g.pdf.SetFont("report", "", 16)
		g.pdf.SetXY(40, 15)
		g.pdf.Cell(nil, activeOverlay.CompanyDisplayName)

		// Report title (white)
		g.pdf.SetFont("report", "", 12)
		g.pdf.SetXY(40, 30)
		g.pdf.Cell(nil, title)

		// Date (right side, white)
		dateStr := time.Now().Format("January 2, 2006")
		g.pdf.SetFont("report", "", 9)
		g.pdf.SetXY(g.pageWidth-150, 15)
		g.pdf.Cell(nil, dateStr)

		// Reset to black for body
		g.pdf.SetTextColor(0, 0, 0)

		// Subtitle below header
		if subtitle != "" {
			g.pdf.SetFont("report", "", 10)
			g.pdf.SetTextColor(100, 100, 100) // Gray
			g.pdf.SetXY(40, 65)
			g.pdf.Cell(nil, subtitle)
			g.pdf.SetTextColor(0, 0, 0) // Back to black
		}
	}
}

// drawFooter draws page footer with page number
func (g *ReportGenerator) drawFooter(pageNum int) {
	g.pdf.SetFont("report", "", 8)
	g.pdf.SetTextColor(150, 150, 150) // Light gray

	// Page number (centered)
	pageText := fmt.Sprintf("Page %d", pageNum)
	g.pdf.SetXY((g.pageWidth/2)-20, g.pageHeight-30)
	g.pdf.Cell(nil, pageText)

	// Watermark
	g.pdf.SetXY(40, g.pageHeight-30)
	g.pdf.Cell(nil, "Generated by "+activeOverlay.CompanyDisplayName+" - Asymmetrica Intelligence")

	g.pdf.SetTextColor(0, 0, 0) // Back to black
}

// drawSectionTitle draws a section title with subtle border
func (g *ReportGenerator) drawSectionTitle(title string, y float64) float64 {
	g.pdf.SetFont("report", "", 12)
	g.pdf.SetTextColor(30, 58, 138) // Navy
	g.pdf.SetXY(40, y)
	g.pdf.Cell(nil, title)

	// Underline
	g.pdf.SetLineWidth(0.5)
	g.pdf.SetStrokeColor(200, 200, 200) // Light gray
	g.pdf.Line(40, y+12, g.pageWidth-40, y+12)

	g.pdf.SetTextColor(0, 0, 0) // Back to black
	return y + 25               // Return next Y position
}

// drawKeyValuePair draws a labeled value (e.g., "Total Predictions: 142")
func (g *ReportGenerator) drawKeyValuePair(label, value string, x, y float64) {
	g.pdf.SetFont("report", "", 10)
	g.pdf.SetTextColor(100, 100, 100) // Gray label
	g.pdf.SetXY(x, y)
	g.pdf.Cell(nil, label+":")

	g.pdf.SetTextColor(0, 0, 0) // Black value
	g.pdf.SetFont("report", "", 11)
	g.pdf.SetXY(x+150, y)
	g.pdf.Cell(nil, value)
}

// drawTable draws a simple table with headers and rows
func (g *ReportGenerator) drawTable(headers []string, rows [][]string, startY float64, colWidths []float64) float64 {
	currentY := startY
	startX := 40.0

	// Calculate total width
	totalWidth := 0.0
	for _, w := range colWidths {
		totalWidth += w
	}

	// Draw header row
	g.pdf.SetFillColor(240, 240, 240) // Light gray background
	g.pdf.RectFromUpperLeftWithStyle(startX, currentY, totalWidth, 20, "F")

	g.pdf.SetFont("report", "", 9)
	g.pdf.SetTextColor(0, 0, 0)

	currentX := startX
	for i, header := range headers {
		g.pdf.SetXY(currentX+5, currentY+6)
		g.pdf.Cell(nil, header)
		currentX += colWidths[i]
	}

	currentY += 20

	// Draw rows
	g.pdf.SetFont("report", "", 8)
	for _, row := range rows {
		// Alternate row background (very subtle)
		if len(rows)%2 == 0 {
			g.pdf.SetFillColor(250, 250, 250)
			g.pdf.RectFromUpperLeftWithStyle(startX, currentY, totalWidth, 15, "F")
		}

		currentX = startX
		for i, cell := range row {
			g.pdf.SetXY(currentX+5, currentY+4)
			g.pdf.Cell(nil, truncateText(cell, int(colWidths[i]/6)))
			currentX += colWidths[i]
		}

		currentY += 15

		// Check if we need a new page (leave room for footer)
		if currentY > g.pageHeight-60 {
			g.pdf.AddPage()
			g.drawLetterhead()
			currentY = 80
		}
	}

	return currentY
}

// ═══════════════════════════════════════════════════════════════════════════
// PUBLIC API - Wails-exposed methods
// ═══════════════════════════════════════════════════════════════════════════

// GenerateDashboardReport generates a PDF report of dashboard statistics
func (a *App) GenerateDashboardReport() (string, error) {
	// I-26: exported/bound report generator — gate read access. The internal
	// email surfaces (SendReportByEmail/CreateReportDraft) already gate with
	// reports:export, which is granted only via the admin wildcard that also
	// grants reports:view, so this adds no double-gate regression.
	if err := a.requirePermission("reports:view"); err != nil {
		return "", err
	}
	gen := NewReportGenerator()
	gen.letterheadPath = a.letterheadImagePath()

	if err := gen.loadFonts(); err != nil {
		return "", fmt.Errorf("failed to load fonts: %v", err)
	}

	gen.pdf.AddPage()

	// Header (with letterhead background)
	gen.drawHeader("Dashboard Report", "Payment Prediction Analytics Overview")

	// Get statistics
	stats, err := a.GetStatistics()
	if err != nil {
		return "", fmt.Errorf("failed to get statistics: %v", err)
	}

	dashStats, err := a.GetDashboardStats()
	if err != nil {
		return "", fmt.Errorf("failed to get dashboard stats: %v", err)
	}

	// Key Metrics Section (start below letterhead if present)
	startY := 90.0
	if gen.letterheadPath != "" {
		startY = 175.0
	}
	currentY := gen.drawSectionTitle("Key Metrics", startY)

	gen.drawKeyValuePair("Total Predictions", fmt.Sprintf("%d", stats.TotalPredictions), 40, currentY)
	currentY += 20

	gen.drawKeyValuePair("Average Confidence", fmt.Sprintf("%.1f%%", stats.AvgConfidence*100), 40, currentY)
	currentY += 20

	gen.drawKeyValuePair("Average Payment Days", fmt.Sprintf("%.0f days", stats.AvgPredictedDays), 40, currentY)
	currentY += 20

	gen.drawKeyValuePair("Win Rate", fmt.Sprintf("%.1f%%", dashStats.WinRate), 40, currentY)
	currentY += 30

	// Grade Distribution Section
	currentY = gen.drawSectionTitle("Grade Distribution", currentY)

	for grade, count := range stats.GradeDistribution {
		percentage := float64(count) / float64(stats.TotalPredictions) * 100
		gen.drawKeyValuePair(
			fmt.Sprintf("Grade %s", grade),
			fmt.Sprintf("%d (%.1f%%)", count, percentage),
			40,
			currentY,
		)
		currentY += 18
	}

	currentY += 20

	// Recent Activity Section
	currentY = gen.drawSectionTitle("Recent Activity", currentY)
	currentY += 10

	records, err := a.GetHistory(10)
	if err != nil {
		return "", fmt.Errorf("failed to get history: %v", err)
	}
	if len(records) > 0 {
		headers := []string{"Date", "Customer", "Grade", "Days", "Confidence"}
		colWidths := []float64{80, 200, 60, 60, 80}

		rows := [][]string{}
		for _, record := range records {
			rows = append(rows, []string{
				record.CreatedAt.Format("2006-01-02"),
				record.CustomerName,
				record.Grade,
				fmt.Sprintf("%d", record.PredictedDays),
				fmt.Sprintf("%.1f%%", record.Confidence*100),
			})
		}

		currentY = gen.drawTable(headers, rows, currentY, colWidths)
	}

	// Footer
	gen.drawFooter(1)

	// Save to user's Documents folder
	documentsPath, err := os.UserHomeDir()
	if err != nil {
		documentsPath = "."
	} else {
		documentsPath = filepath.Join(documentsPath, "Documents")
	}

	timestamp := time.Now().Format("20060102_150405")
	filename := fmt.Sprintf("PH_Holdings_Dashboard_%s.pdf", timestamp)
	outputPath := filepath.Join(documentsPath, filename)

	if err := gen.pdf.WritePdf(outputPath); err != nil {
		return "", fmt.Errorf("failed to write PDF: %v", err)
	}

	return outputPath, nil
}

// GeneratePredictionHistoryReport generates a PDF report of prediction history
func (a *App) GeneratePredictionHistoryReport(limit int) (string, error) {
	// I-26: exported/bound report generator — gate read access (see
	// GenerateDashboardReport for the reports:view/reports:export rationale).
	if err := a.requirePermission("reports:view"); err != nil {
		return "", err
	}
	if limit <= 0 {
		limit = 100
	}

	gen := NewReportGenerator()
	gen.letterheadPath = a.letterheadImagePath()

	if err := gen.loadFonts(); err != nil {
		return "", fmt.Errorf("failed to load fonts: %v", err)
	}

	gen.pdf.AddPage()

	// Header (with letterhead background)
	gen.drawHeader("Prediction History Report", fmt.Sprintf("Last %d predictions", limit))

	// Summary Section (start below letterhead if present)
	startY := 90.0
	if gen.letterheadPath != "" {
		startY = 175.0
	}
	currentY := gen.drawSectionTitle("Summary Statistics", startY)

	records, err := a.GetHistory(limit)
	if err != nil {
		return "", fmt.Errorf("failed to get history: %v", err)
	}

	stats, err := a.GetStatistics()
	if err != nil {
		return "", fmt.Errorf("failed to get statistics: %v", err)
	}

	gen.drawKeyValuePair("Total Records", fmt.Sprintf("%d", len(records)), 40, currentY)
	currentY += 20

	gen.drawKeyValuePair("Average Confidence", fmt.Sprintf("%.1f%%", stats.AvgConfidence*100), 40, currentY)
	currentY += 20

	gen.drawKeyValuePair("Average Payment Days", fmt.Sprintf("%.0f days", stats.AvgPredictedDays), 40, currentY)
	currentY += 30

	// Predictions Table Section
	currentY = gen.drawSectionTitle("Prediction Records", currentY)
	currentY += 10

	if len(records) > 0 {
		headers := []string{"Date", "Customer", "Grade", "Days", "Conf%", "R1", "R2", "R3"}
		colWidths := []float64{70, 150, 40, 40, 45, 40, 40, 40}

		rows := [][]string{}
		for _, record := range records {
			rows = append(rows, []string{
				record.CreatedAt.Format("01/02"),
				record.CustomerName,
				record.Grade,
				fmt.Sprintf("%d", record.PredictedDays),
				fmt.Sprintf("%.0f", record.Confidence*100),
				fmt.Sprintf("%.0f", record.R1*100),
				fmt.Sprintf("%.0f", record.R2*100),
				fmt.Sprintf("%.0f", record.R3*100),
			})
		}

		currentY = gen.drawTable(headers, rows, currentY, colWidths)
	}

	// Footer
	gen.drawFooter(1)

	// Save to user's Documents folder
	documentsPath, err := os.UserHomeDir()
	if err != nil {
		documentsPath = "."
	} else {
		documentsPath = filepath.Join(documentsPath, "Documents")
	}

	timestamp := time.Now().Format("20060102_150405")
	filename := fmt.Sprintf("PH_Holdings_History_%s.pdf", timestamp)
	outputPath := filepath.Join(documentsPath, filename)

	if err := gen.pdf.WritePdf(outputPath); err != nil {
		return "", fmt.Errorf("failed to write PDF: %v", err)
	}

	return outputPath, nil
}

// GenerateCustomer360Report generates a detailed customer report
func (a *App) GenerateCustomer360Report(customerID string) (string, error) {
	// I-26: exported/bound report generator — gate read access (see
	// GenerateDashboardReport for the reports:view/reports:export rationale).
	if err := a.requirePermission("reports:view"); err != nil {
		return "", err
	}
	gen := NewReportGenerator()
	gen.letterheadPath = a.letterheadImagePath()

	if err := gen.loadFonts(); err != nil {
		return "", fmt.Errorf("failed to load fonts: %v", err)
	}

	gen.pdf.AddPage()

	// Get customer history
	records, err := a.GetCustomerHistory(customerID)
	if err != nil {
		return "", fmt.Errorf("failed to get customer history: %v", err)
	}
	if len(records) == 0 {
		return "", fmt.Errorf("no records found for customer: %s", customerID)
	}

	latestRecord := records[0]

	// Header (with letterhead background)
	gen.drawHeader("Customer 360° Report", latestRecord.CustomerName)

	// Customer Information Section (start below letterhead if present)
	startY := 90.0
	if gen.letterheadPath != "" {
		startY = 175.0
	}
	currentY := gen.drawSectionTitle("Customer Information", startY)

	gen.drawKeyValuePair("Customer ID", latestRecord.CustomerID, 40, currentY)
	currentY += 20

	gen.drawKeyValuePair("Customer Name", latestRecord.CustomerName, 40, currentY)
	currentY += 20

	gen.drawKeyValuePair("Current Grade", latestRecord.Grade, 40, currentY)
	currentY += 20

	gen.drawKeyValuePair("Latest Prediction", fmt.Sprintf("%d days", latestRecord.PredictedDays), 40, currentY)
	currentY += 20

	gen.drawKeyValuePair("Confidence Score", fmt.Sprintf("%.1f%%", latestRecord.Confidence*100), 40, currentY)
	currentY += 30

	// Three-Regime Analysis Section
	currentY = gen.drawSectionTitle("Three-Regime Analysis", currentY)

	gen.drawKeyValuePair("Exploration (R1)", fmt.Sprintf("%.1f%%", latestRecord.R1*100), 40, currentY)
	currentY += 18

	gen.drawKeyValuePair("Optimization (R2)", fmt.Sprintf("%.1f%%", latestRecord.R2*100), 40, currentY)
	currentY += 18

	gen.drawKeyValuePair("Stabilization (R3)", fmt.Sprintf("%.1f%%", latestRecord.R3*100), 40, currentY)
	currentY += 30

	// Prediction History Section
	currentY = gen.drawSectionTitle("Prediction History", currentY)
	currentY += 10

	if len(records) > 0 {
		headers := []string{"Date", "Grade", "Days", "Confidence", "R1", "R2", "R3"}
		colWidths := []float64{80, 60, 60, 80, 60, 60, 60}

		rows := [][]string{}
		for _, record := range records {
			rows = append(rows, []string{
				record.CreatedAt.Format("2006-01-02"),
				record.Grade,
				fmt.Sprintf("%d", record.PredictedDays),
				fmt.Sprintf("%.1f%%", record.Confidence*100),
				fmt.Sprintf("%.0f%%", record.R1*100),
				fmt.Sprintf("%.0f%%", record.R2*100),
				fmt.Sprintf("%.0f%%", record.R3*100),
			})
		}

		currentY = gen.drawTable(headers, rows, currentY, colWidths)
	}

	// Behavioral Insights Section
	currentY += 20
	if currentY > gen.pageHeight-150 {
		gen.pdf.AddPage()
		gen.drawLetterhead()
		currentY = 80
	}

	currentY = gen.drawSectionTitle("Behavioral Insights", currentY)

	// Calculate trends
	if len(records) >= 2 {
		avgGrade := calculateAverageGrade(records)
		avgDays := calculateAverageDays(records)

		gen.drawKeyValuePair("Average Grade", avgGrade, 40, currentY)
		currentY += 18

		gen.drawKeyValuePair("Average Payment Days", fmt.Sprintf("%.0f days", avgDays), 40, currentY)
		currentY += 18

		gen.drawKeyValuePair("Total Predictions", fmt.Sprintf("%d", len(records)), 40, currentY)
		currentY += 18
	}

	// Footer
	gen.drawFooter(1)

	// Save to user's Documents folder
	documentsPath, err := os.UserHomeDir()
	if err != nil {
		documentsPath = "."
	} else {
		documentsPath = filepath.Join(documentsPath, "Documents")
	}

	timestamp := time.Now().Format("20060102_150405")
	sanitizedName := sanitizeFilename(latestRecord.CustomerName)
	filename := fmt.Sprintf("PH_Holdings_Customer_%s_%s.pdf", sanitizedName, timestamp)
	outputPath := filepath.Join(documentsPath, filename)

	if err := gen.pdf.WritePdf(outputPath); err != nil {
		return "", fmt.Errorf("failed to write PDF: %v", err)
	}

	return outputPath, nil
}

// ═══════════════════════════════════════════════════════════════════════════
// HELPER FUNCTIONS
// ═══════════════════════════════════════════════════════════════════════════

// calculateAverageGrade calculates the average grade from records
func calculateAverageGrade(records []PredictionRecord) string {
	if len(records) == 0 {
		return "N/A"
	}

	gradeMap := map[string]int{"A": 4, "B": 3, "C": 2, "D": 1}
	reverseMap := map[int]string{4: "A", 3: "B", 2: "C", 1: "D"}

	total := 0
	for _, record := range records {
		total += gradeMap[record.Grade]
	}

	avg := total / len(records)
	return reverseMap[avg]
}

// calculateAverageDays calculates the average predicted days from records
func calculateAverageDays(records []PredictionRecord) float64 {
	if len(records) == 0 {
		return 0
	}

	total := 0
	for _, record := range records {
		total += record.PredictedDays
	}

	return float64(total) / float64(len(records))
}

// Note: truncateText and fileExists are defined in pdf_generator.go

// sanitizeFilename removes invalid characters from filenames
func sanitizeFilename(name string) string {
	// Replace spaces and special chars with underscores
	result := ""
	for _, ch := range name {
		if (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9') {
			result += string(ch)
		} else {
			result += "_"
		}
	}

	// Truncate to reasonable length
	if len(result) > 30 {
		result = result[:30]
	}

	return result
}

// ============================================================================
// REPORTS SCREEN DATA LAYER - Business Intelligence
// ============================================================================

// ReportData encapsulates all report types (sales, customers, operations, etc.)
type ReportData struct {
	// Sales Report Data
	Pipeline       []PipelineStage `json:"pipeline,omitempty"`
	ConversionRate float64         `json:"conversion_rate,omitempty"`
	AvgDealSize    float64         `json:"avg_deal_size,omitempty"`
	WinRate        float64         `json:"win_rate,omitempty"`
	TopProducts    []TopProduct    `json:"top_products,omitempty"`

	// Customer Report Data
	GradeDistribution []GradeDistItem    `json:"grade_distribution,omitempty"`
	TypeDistribution  []CustomerTypeItem `json:"type_distribution,omitempty"`
	AvgPaymentDays    float64            `json:"avg_payment_days,omitempty"`
	CollectionEff     float64            `json:"collection_efficiency,omitempty"`

	// Operations Report Data
	OrdersByStage    []OrderStage `json:"orders_by_stage,omitempty"`
	AvgLeadTime      int          `json:"avg_lead_time,omitempty"`
	OnTimeDelivery   float64      `json:"on_time_delivery,omitempty"`
	PendingShipments int          `json:"pending_shipments,omitempty"`

	// Inventory Report Data
	TotalItems     int                    `json:"total_items,omitempty"`
	TotalValue     float64                `json:"total_value,omitempty"`
	LowStockAlerts int                    `json:"low_stock_alerts,omitempty"`
	Movements      []StockMovementSummary `json:"movements,omitempty"`

	// Financial Report Data — trader vocabulary, not SaaS metrics. No runway/
	// burn/MRR-target here: those were either hardcoded fiction (Runway) or
	// rough guesses (Cash Balance, Monthly Burn) dressed up as real numbers.
	// Receivables/Payables Outstanding and Avg Monthly Revenue below are all
	// real query results.
	ReceivablesOutstanding float64         `json:"receivables_outstanding,omitempty"`
	PayablesOutstanding    float64         `json:"payables_outstanding,omitempty"`
	AvgMonthlyRevenue      float64         `json:"avg_monthly_revenue,omitempty"`
	CollectionTarget       float64         `json:"collection_target,omitempty"`
	Collected              float64         `json:"collected,omitempty"`
	Overdue                []OverdueBucket `json:"overdue,omitempty"`
}

// Pipeline stage for sales report
type PipelineStage struct {
	Stage string  `json:"stage"`
	Count int     `json:"count"`
	Value float64 `json:"value"`
}

// Top product for sales report
type TopProduct struct {
	Name    string  `json:"name"`
	Revenue float64 `json:"revenue"`
	Count   int     `json:"count"`
}

// Grade distribution item
type GradeDistItem struct {
	Grade      string  `json:"grade"`
	Count      int     `json:"count"`
	Percentage float64 `json:"percentage"`
}

// Customer type distribution (renamed to avoid conflict with existing CustomerType)
type CustomerTypeItem struct {
	Type  string `json:"type"`
	Label string `json:"label"`
	Count int    `json:"count"`
}

// Order stage for operations report
type OrderStage struct {
	Stage string `json:"stage"`
	Count int    `json:"count"`
}

// Stock movement summary for reports
type StockMovementSummary struct {
	Type  string  `json:"type"`
	Count int     `json:"count"`
	Value float64 `json:"value"`
}

// Overdue bucket for financial report
type OverdueBucket struct {
	Days   string  `json:"days"`
	Amount float64 `json:"amount"`
}

// GetReportData retrieves report data based on type and date range
func (a *App) GetReportData(reportType string, dateRange string) (ReportData, error) {
	// I-26: this exported/bound getter returns the same underlying finance,
	// sales, customer and operations data the exporters gate — so it must gate
	// too. Map each report type to the permission that guards its data
	// (requireReportAccess), matching ExportReport and deployed PH.
	if err := a.requireReportAccess(reportType); err != nil {
		return ReportData{}, err
	}
	if a.db == nil {
		return ReportData{}, newError("DB_NOT_INITIALIZED", "Database not available", "")
	}

	var startDate time.Time
	now := time.Now()

	// Parse date range
	switch dateRange {
	case "week":
		startDate = now.AddDate(0, 0, -7)
	case "month":
		startDate = now.AddDate(0, -1, 0)
	case "quarter":
		startDate = now.AddDate(0, -3, 0)
	case "year":
		startDate = now.AddDate(-1, 0, 0)
	default:
		startDate = now.AddDate(0, -1, 0) // Default to month
	}

	switch reportType {
	case "sales":
		return a.getSalesReport(startDate)
	case "customers":
		return a.getCustomersReport(startDate)
	case "operations":
		return a.getOperationsReport(startDate)
	case "inventory":
		return a.getInventoryReport(startDate)
	case "financial":
		return a.getFinancialReport(startDate)
	default:
		return ReportData{}, newError("INVALID_REPORT_TYPE", "Unknown report type", reportType)
	}
}

// getSalesReport generates sales analytics
func (a *App) getSalesReport(startDate time.Time) (ReportData, error) {
	var data ReportData

	// Pipeline by Stage (from Offers table)
	type StageCount struct {
		Stage string
		Count int64
		Total float64
	}
	var stages []StageCount
	err := a.db.Model(&Offer{}).
		Select("stage, COUNT(*) as count, COALESCE(SUM(net_value_bhd), 0) as total").
		Where("created_at >= ?", startDate).
		Group("stage").
		Order("CASE stage WHEN 'RFQ' THEN 1 WHEN 'Quoted' THEN 2 WHEN 'Follow-up' THEN 3 WHEN 'Won' THEN 4 ELSE 5 END").
		Scan(&stages).Error

	if err == nil {
		data.Pipeline = make([]PipelineStage, len(stages))
		for i, s := range stages {
			data.Pipeline[i] = PipelineStage{
				Stage: s.Stage,
				Count: int(s.Count),
				Value: s.Total,
			}
		}
	}

	// Win rate calculation
	var totalOffers, wonOffers int64
	a.db.Model(&Offer{}).Where("created_at >= ?", startDate).Count(&totalOffers)
	a.db.Model(&Offer{}).Where("created_at >= ? AND stage = ?", startDate, "Won").Count(&wonOffers)
	if totalOffers > 0 {
		data.WinRate = float64(wonOffers) / float64(totalOffers)
	}

	// Average deal size
	var avgDeal float64
	a.db.Model(&Offer{}).
		Where("created_at >= ? AND stage = ?", startDate, "Won").
		Select("AVG(net_value_bhd)").
		Scan(&avgDeal)
	data.AvgDealSize = avgDeal

	// Conversion rate (RFQ → Won)
	var rfqCount int64
	a.db.Model(&Offer{}).Where("created_at >= ? AND stage = ?", startDate, "RFQ").Count(&rfqCount)
	if rfqCount > 0 {
		data.ConversionRate = float64(wonOffers) / float64(rfqCount)
	}

	// Top products (from offer items)
	type ProductSummary struct {
		ProductCode string
		Revenue     float64
		Quantity    float64
	}
	var products []ProductSummary
	err = a.db.Table("offer_items oi").
		Select("oi.product_code, SUM(oi.line_total_bhd) as revenue, SUM(oi.quantity) as quantity").
		Joins("JOIN offers o ON o.id = oi.offer_id").
		Where("o.created_at >= ? AND o.stage = ?", startDate, "Won").
		Group("oi.product_code").
		Order("revenue DESC").
		Limit(5).
		Scan(&products).Error

	if err == nil {
		data.TopProducts = make([]TopProduct, len(products))
		for i, p := range products {
			data.TopProducts[i] = TopProduct{
				Name:    p.ProductCode,
				Revenue: p.Revenue,
				Count:   int(p.Quantity),
			}
		}
	}

	return data, nil
}

// getCustomersReport generates customer analytics
func (a *App) getCustomersReport(startDate time.Time) (ReportData, error) {
	var data ReportData

	// Grade distribution
	type GradeCount struct {
		Grade string
		Count int64
	}
	var grades []GradeCount
	err := a.db.Model(&CustomerMaster{}).
		Select("payment_grade as grade, COUNT(*) as count").
		Where("payment_grade != ''").
		Group("payment_grade").
		Order("payment_grade").
		Scan(&grades).Error

	if err == nil {
		totalCustomers := int64(0)
		for _, g := range grades {
			totalCustomers += g.Count
		}

		data.GradeDistribution = make([]GradeDistItem, len(grades))
		for i, g := range grades {
			percentage := float64(0)
			if totalCustomers > 0 {
				percentage = (float64(g.Count) / float64(totalCustomers)) * 100
			}
			data.GradeDistribution[i] = GradeDistItem{
				Grade:      g.Grade,
				Count:      int(g.Count),
				Percentage: percentage,
			}
		}
	}

	// Customer type distribution
	type TypeCount struct {
		Type  string
		Count int64
	}
	var types []TypeCount
	err = a.db.Model(&CustomerMaster{}).
		Select("customer_type as type, COUNT(*) as count").
		Where("customer_type != ''").
		Group("customer_type").
		Scan(&types).Error

	if err == nil {
		typeLabels := map[string]string{
			"EC": "End Customer",
			"EP": "EPC/Licensor",
			"SI": "System Integrator",
			"NR": "National Reseller",
		}

		data.TypeDistribution = make([]CustomerTypeItem, len(types))
		for i, t := range types {
			label := typeLabels[t.Type]
			if label == "" {
				label = t.Type
			}
			data.TypeDistribution[i] = CustomerTypeItem{
				Type:  t.Type,
				Label: label,
				Count: int(t.Count),
			}
		}
	}

	// Average payment days
	var avgPayment float64
	a.db.Model(&CustomerMaster{}).
		Select("AVG(avg_payment_days)").
		Scan(&avgPayment)
	data.AvgPaymentDays = avgPayment

	// Collection efficiency (simplified - invoices paid within terms)
	var totalInvoices, paidOnTime int64
	a.db.Model(&Invoice{}).Where("created_at >= ?", startDate).Count(&totalInvoices)
	a.db.Model(&Invoice{}).
		Where("created_at >= ? AND paid_date IS NOT NULL", startDate).
		Count(&paidOnTime)

	if totalInvoices > 0 {
		data.CollectionEff = float64(paidOnTime) / float64(totalInvoices)
	}

	return data, nil
}

// getOperationsReport generates operations analytics
func (a *App) getOperationsReport(startDate time.Time) (ReportData, error) {
	var data ReportData

	// Orders by stage
	type StageCount struct {
		Status string
		Count  int64
	}
	var stages []StageCount
	err := a.db.Model(&Order{}).
		Select("status, COUNT(*) as count").
		Where("created_at >= ?", startDate).
		Group("status").
		Scan(&stages).Error

	if err == nil {
		data.OrdersByStage = make([]OrderStage, len(stages))
		for i, s := range stages {
			data.OrdersByStage[i] = OrderStage{
				Stage: s.Status,
				Count: int(s.Count),
			}
		}
	}

	// Average lead time (simplified - from order to delivery)
	var avgLead float64
	a.db.Table("orders o").
		Select("AVG(JULIANDAY(s.delivered_date) - JULIANDAY(o.order_date))").
		Joins("JOIN shipments s ON s.order_id = o.id").
		Where("o.created_at >= ? AND s.delivered_date IS NOT NULL", startDate).
		Scan(&avgLead)
	data.AvgLeadTime = int(avgLead)

	// On-time delivery rate
	var totalDelivered, onTime int64
	a.db.Table("orders o").
		Joins("JOIN shipments s ON s.order_id = o.id").
		Where("o.created_at >= ? AND s.delivered_date IS NOT NULL", startDate).
		Count(&totalDelivered)

	a.db.Table("orders o").
		Joins("JOIN shipments s ON s.order_id = o.id").
		Where("o.created_at >= ? AND s.delivered_date IS NOT NULL AND s.delivered_date <= o.promised_date", startDate).
		Count(&onTime)

	if totalDelivered > 0 {
		data.OnTimeDelivery = float64(onTime) / float64(totalDelivered)
	}

	// Pending shipments
	var pending int64
	a.db.Model(&Shipment{}).
		Where("status IN ?", []string{"Packed", "Shipped", "In Transit"}).
		Count(&pending)
	data.PendingShipments = int(pending)

	return data, nil
}

// getInventoryReport generates inventory analytics
func (a *App) getInventoryReport(startDate time.Time) (ReportData, error) {
	var data ReportData

	// Total items and value (from products table)
	var totalItems int64
	var totalValue float64
	a.db.Model(&ProductMaster{}).
		Where("is_stocked = ?", true).
		Count(&totalItems)

	a.db.Model(&ProductMaster{}).
		Where("is_stocked = ?", true).
		Select("SUM(stock_quantity * standard_cost_bhd)").
		Scan(&totalValue)

	data.TotalItems = int(totalItems)
	data.TotalValue = totalValue

	// Low stock alerts (products with stock below threshold)
	var lowStock int64
	a.db.Model(&ProductMaster{}).
		Where("is_stocked = ? AND stock_quantity < ?", true, 5).
		Count(&lowStock)
	data.LowStockAlerts = int(lowStock)

	// Stock movements within the report window, aggregated by direction from
	// the real stock_movements ledger (RecordStockMovement) — replaces the
	// previous hardcoded placeholder rows.
	type MovementAgg struct {
		Direction string
		Count     int64
		Value     float64
	}
	var movementAggs []MovementAgg
	err := a.db.Model(&StockMovement{}).
		Select("direction, COUNT(*) as count, COALESCE(SUM(total_value), 0) as value").
		Where("movement_date >= ?", startDate).
		Group("direction").
		Scan(&movementAggs).Error

	if err == nil {
		data.Movements = make([]StockMovementSummary, len(movementAggs))
		for i, m := range movementAggs {
			data.Movements[i] = StockMovementSummary{
				Type:  m.Direction,
				Count: int(m.Count),
				Value: m.Value,
			}
		}
	}

	return data, nil
}

// getFinancialReport generates financial analytics in trader vocabulary —
// receivables/payables/collection, not SaaS runway/burn/MRR framing. Every
// figure below is a direct query result; nothing is an assumed-margin guess
// dressed up as fact (the old Runway card was a hardcoded 12.5, and Cash
// Balance/Monthly Burn were revenue*0.3 estimates — all three are gone).
func (a *App) getFinancialReport(startDate time.Time) (ReportData, error) {
	var data ReportData

	// Avg Monthly Revenue — real average of paid invoice totals per calendar
	// month in the window (previously mislabeled "MRR" with a fictional
	// 8000 BHD target bolted on; the target is gone, the number is real).
	var avgMonthlyRevenue float64
	a.db.Model(&Invoice{}).
		Where("created_at >= ? AND status = ?", startDate, "Paid").
		Select("SUM(grand_total_bhd) / COUNT(DISTINCT strftime('%Y-%m', invoice_date))").
		Scan(&avgMonthlyRevenue)
	data.AvgMonthlyRevenue = avgMonthlyRevenue

	// Collection metrics
	var collectionTarget, collected float64
	a.db.Model(&Invoice{}).
		Where("created_at >= ?", startDate).
		Select("SUM(grand_total_bhd)").
		Scan(&collectionTarget)

	a.db.Model(&Invoice{}).
		Where("created_at >= ? AND status = ?", startDate, "Paid").
		Select("SUM(paid_amount_bhd)").
		Scan(&collected)

	data.CollectionTarget = collectionTarget
	data.Collected = collected

	// Receivables Outstanding — real sum of unpaid invoice balances. Replaces
	// the old hardcoded Runway card outright (no margin/assumption factor).
	var totalReceivables float64
	a.db.Model(&Invoice{}).
		Where("status != ?", "Paid").
		Select("SUM(outstanding_bhd)").
		Scan(&totalReceivables)
	data.ReceivablesOutstanding = totalReceivables

	// Payables Outstanding — real sum of unpaid supplier invoices, mirroring
	// GetAPAgingReport's own unpaid-invoice query. Replaces the old Cash
	// Balance/Monthly Burn cards, which were revenue*0.3 guesses.
	var totalPayables float64
	a.db.Model(&SupplierInvoice{}).
		Where("payment_status != ? AND deleted_at IS NULL", "Paid").
		Select("SUM(total_bhd)").
		Scan(&totalPayables)
	data.PayablesOutstanding = totalPayables

	// Overdue receivables by aging bucket
	type OverdueSum struct {
		Bucket string
		Amount float64
	}
	var overdueBuckets []OverdueSum
	a.db.Model(&Invoice{}).
		Select(`
			CASE
				WHEN days_outstanding BETWEEN 30 AND 60 THEN '30-60'
				WHEN days_outstanding BETWEEN 60 AND 90 THEN '60-90'
				WHEN days_outstanding > 90 THEN '90+'
			END as bucket,
			SUM(outstanding_bhd) as amount
		`).
		Where("status != ? AND days_outstanding >= 30", "Paid").
		Group("bucket").
		Having("bucket IS NOT NULL").
		Scan(&overdueBuckets)

	data.Overdue = make([]OverdueBucket, len(overdueBuckets))
	for i, b := range overdueBuckets {
		data.Overdue[i] = OverdueBucket{
			Days:   b.Bucket,
			Amount: b.Amount,
		}
	}

	return data, nil
}

// ExportReport exports report data to CSV format
// PDF/Excel will be added later using existing generator functions
func (a *App) ExportReport(reportType string, format string, dataJSON string) (string, error) {
	// RBAC: only users with access to the underlying data may export it.
	if err := a.requireReportAccess(reportType); err != nil {
		return "", err
	}
	// Whitelist known export report types (defence against injection/unknown types).
	if !isKnownExportReportType(reportType) {
		return "", newError("INVALID_REPORT_TYPE", "Unknown report type", reportType)
	}
	// Cap the incoming payload so a hostile/oversized dataJSON cannot exhaust memory.
	if len(dataJSON) > maxReportExportPayloadBytes {
		return "", newError("EXPORT_TOO_LARGE", "Report export payload is too large", "Reduce filters and try again")
	}

	// Ensure exports directory exists
	exportDir := a.getExportDir("report", "", "", time.Now().Year())

	// Generate filename — sanitize reportType so it can never inject path
	// separators or traversal sequences into the output filename.
	timestamp := time.Now().Format("2006-01-02_150405")
	safeReportType := sanitizeFileName(strings.ToLower(strings.TrimSpace(reportType)))
	if safeReportType == "" || safeReportType == "unnamed" {
		safeReportType = "report"
	}
	filename := fmt.Sprintf("%s_report_%s.%s", safeReportType, timestamp, format)
	exportPath := filepath.Join(exportDir, filename)

	switch format {
	case "csv":
		return a.exportReportToCSV(exportPath, reportType, dataJSON)
	case "pdf":
		return "", newError("NOT_IMPLEMENTED", "PDF export coming soon", "Use CSV for now")
	case "excel":
		return "", newError("NOT_IMPLEMENTED", "Excel export coming soon", "Use CSV for now")
	default:
		return "", newError("INVALID_FORMAT", "Unsupported export format", format)
	}
}

// maxReportExportPayloadBytes caps the size of a report export request payload
// so a hostile or malformed dataJSON cannot exhaust memory during export.
const maxReportExportPayloadBytes = 15 * 1024 * 1024

// requireReportAccess enforces RBAC on report export/generation, mapping each
// report type to the permission that gates access to its underlying data.
func (a *App) requireReportAccess(reportType string) error {
	switch strings.ToLower(strings.TrimSpace(reportType)) {
	case "financial":
		return a.requirePermission("finance:view")
	case "sales":
		return a.requirePermission("offers:view")
	case "operations":
		return a.requirePermission("orders:view")
	case "customers":
		return a.requirePermission("customers:view")
	case "inventory":
		return a.requirePermission("inventory:view")
	default:
		return a.requirePermission("reports:view")
	}
}

// isKnownExportReportType whitelists the report types the exporter can produce.
func isKnownExportReportType(reportType string) bool {
	switch strings.ToLower(strings.TrimSpace(reportType)) {
	case "sales", "customers", "operations", "inventory", "financial":
		return true
	default:
		return false
	}
}

// exportReportToCSV exports report data to CSV format
func (a *App) exportReportToCSV(filePath string, reportType string, dataJSON string) (string, error) {
	file, err := os.Create(filePath)
	if err != nil {
		return "", newError("FILE_CREATE_FAILED", "Failed to create CSV file", err.Error())
	}
	defer file.Close()

	// Get fresh data
	data, err := a.GetReportData(reportType, "month")
	if err != nil {
		return "", err
	}

	// Write report-specific CSV data
	switch reportType {
	case "sales":
		file.WriteString(activeOverlay.CompanyDisplayName + " - Sales Report\n")
		file.WriteString(fmt.Sprintf("Generated: %s\n\n", time.Now().Format("2006-01-02 15:04")))
		file.WriteString("Stage,Count,Value (BHD)\n")
		for _, stage := range data.Pipeline {
			file.WriteString(fmt.Sprintf("%s,%d,%.2f\n", stage.Stage, stage.Count, stage.Value))
		}
		file.WriteString("\nMetrics\n")
		file.WriteString(fmt.Sprintf("Win Rate,%.2f%%\n", data.WinRate*100))
		file.WriteString(fmt.Sprintf("Conversion Rate,%.2f%%\n", data.ConversionRate*100))
		file.WriteString(fmt.Sprintf("Avg Deal Size,%.2f BHD\n", data.AvgDealSize))

	case "customers":
		file.WriteString(activeOverlay.CompanyDisplayName + " - Customer Report\n")
		file.WriteString(fmt.Sprintf("Generated: %s\n\n", time.Now().Format("2006-01-02 15:04")))
		file.WriteString("Grade,Count,Percentage\n")
		for _, grade := range data.GradeDistribution {
			file.WriteString(fmt.Sprintf("%s,%d,%.1f%%\n", grade.Grade, grade.Count, grade.Percentage))
		}
		file.WriteString("\nCustomer Type,Count\n")
		for _, t := range data.TypeDistribution {
			file.WriteString(fmt.Sprintf("%s,%d\n", t.Label, t.Count))
		}
		file.WriteString("\nMetrics\n")
		file.WriteString(fmt.Sprintf("Avg Payment Days,%.0f\n", data.AvgPaymentDays))
		file.WriteString(fmt.Sprintf("Collection Efficiency,%.1f%%\n", data.CollectionEff*100))

	case "operations":
		file.WriteString(activeOverlay.CompanyDisplayName + " - Operations Report\n")
		file.WriteString(fmt.Sprintf("Generated: %s\n\n", time.Now().Format("2006-01-02 15:04")))
		file.WriteString("Order Stage,Count\n")
		for _, s := range data.OrdersByStage {
			file.WriteString(fmt.Sprintf("%s,%d\n", s.Stage, s.Count))
		}
		file.WriteString("\nMetrics\n")
		file.WriteString(fmt.Sprintf("Avg Lead Time (days),%d\n", data.AvgLeadTime))
		file.WriteString(fmt.Sprintf("On-Time Delivery,%.1f%%\n", data.OnTimeDelivery*100))
		file.WriteString(fmt.Sprintf("Pending Shipments,%d\n", data.PendingShipments))

	case "inventory":
		file.WriteString(activeOverlay.CompanyDisplayName + " - Inventory Report\n")
		file.WriteString(fmt.Sprintf("Generated: %s\n\n", time.Now().Format("2006-01-02 15:04")))
		file.WriteString("Metric,Value\n")
		file.WriteString(fmt.Sprintf("Total Items,%d\n", data.TotalItems))
		file.WriteString(fmt.Sprintf("Total Value (BHD),%.2f\n", data.TotalValue))
		file.WriteString(fmt.Sprintf("Low Stock Alerts,%d\n", data.LowStockAlerts))
		file.WriteString("\nStock Movements (in report window)\n")
		file.WriteString("Direction,Count,Value (BHD)\n")
		for _, m := range data.Movements {
			file.WriteString(fmt.Sprintf("%s,%d,%.2f\n", m.Type, m.Count, m.Value))
		}

	case "financial":
		file.WriteString(activeOverlay.CompanyDisplayName + " - Financial Report\n")
		file.WriteString(fmt.Sprintf("Generated: %s\n\n", time.Now().Format("2006-01-02 15:04")))
		file.WriteString("Metric,Value\n")
		file.WriteString(fmt.Sprintf("Receivables Outstanding,%.2f BHD\n", data.ReceivablesOutstanding))
		file.WriteString(fmt.Sprintf("Payables Outstanding,%.2f BHD\n", data.PayablesOutstanding))
		file.WriteString(fmt.Sprintf("Avg Monthly Revenue,%.2f BHD\n", data.AvgMonthlyRevenue))
		file.WriteString(fmt.Sprintf("Collected,%.2f BHD\n", data.Collected))
		file.WriteString(fmt.Sprintf("Collection Target,%.2f BHD\n", data.CollectionTarget))
		file.WriteString("\nOverdue Receivables\n")
		file.WriteString("Aging,Amount (BHD)\n")
		for _, bucket := range data.Overdue {
			file.WriteString(fmt.Sprintf("%s,%.2f\n", bucket.Days, bucket.Amount))
		}

	default:
		file.WriteString(fmt.Sprintf("%s - %s Report\n", activeOverlay.CompanyDisplayName, reportType))
		file.WriteString(fmt.Sprintf("Generated: %s\n\n", time.Now().Format("2006-01-02 15:04")))
		file.WriteString("Report Type,Status\n")
		file.WriteString(fmt.Sprintf("%s,Not yet implemented\n", reportType))
	}

	return filePath, nil
}
