// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {crm} from '../models';
import {finance} from '../models';
import {payroll} from '../models';
import {banking} from '../models';
import {prediction} from '../models';
import {graph} from '../models';
import {time} from '../models';
import {butler} from '../models';
import {engines} from '../models';
import {device} from '../models';
import {infra} from '../models';
import {contract} from '../models';
import {documents} from '../models';
import {evidence} from '../models';
import {fx} from '../models';
import {cheque} from '../models';
import {posting} from '../models';
import {integration} from '../models';
import {data} from '../models';
import {assets} from '../models';
import {deletion} from '../models';
import {compliance} from '../models';

export function AIClassifyDocumentType(arg1:string,arg2:string):Promise<main.ClassificationResult>;

export function AcknowledgeAlert(arg1:number):Promise<void>;

export function ActivateLicense(arg1:string):Promise<main.LicenseActivationResult>;

export function AddCollaborativeProjectMember(arg1:string,arg2:string,arg3:string,arg4:number):Promise<main.ProjectMember>;

export function AddCollaborativeTaskComment(arg1:string,arg2:string):Promise<main.TaskComment>;

export function AddCustomerContact(arg1:crm.CustomerContact):Promise<crm.CustomerContact>;

export function AddCustomerNote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddManualCustomerMapping(arg1:string,arg2:string):Promise<void>;

export function AddOfferFollowUp(arg1:string,arg2:string,arg3:string):Promise<crm.OfferFollowUp>;

export function AddOfferNote(arg1:string,arg2:string):Promise<crm.OfferNote>;

export function AddOpportunityComment(arg1:string,arg2:string):Promise<main.OpportunityComment>;

export function AddRFQComment(arg1:number,arg2:string,arg3:string):Promise<main.RFQComment>;

export function AddSupplierContact(arg1:crm.SupplierContact):Promise<crm.SupplierContact>;

export function AddSupplierIssue(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function AddSupplierNote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AmendPurchaseOrder(arg1:string,arg2:main.POAmendment):Promise<void>;

export function AnalyzeDocumentWithButler(arg1:string,arg2:string,arg3:Record<string, any>):Promise<main.ButlerOCRInsight>;

export function ApplyCreditNote(arg1:string):Promise<void>;

export function ApplyCustomerReceiptToInvoice(arg1:string,arg2:string,arg3:number):Promise<main.CustomerReceiptAllocation>;

export function ApplyDeploymentLicenseActivationFlush():Promise<void>;

export function ApplyReconciliation(arg1:string):Promise<void>;

export function ApproveCostingSheet(arg1:number,arg2:string):Promise<void>;

export function ApproveDevice(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function ApproveExpenseEntry(arg1:string,arg2:string):Promise<finance.ExpenseEntry>;

export function ApprovePayrollRun(arg1:string,arg2:string):Promise<payroll.Run>;

export function ApprovePurchaseOrder(arg1:string,arg2:string):Promise<void>;

export function ApproveStockAdjustment(arg1:string):Promise<void>;

export function ApproveSupplierInvoice(arg1:string,arg2:string):Promise<void>;

export function ArchiveCollaborativeProject(arg1:string,arg2:string):Promise<main.Project>;

export function ArchiveStatementPDF(arg1:string,arg2:string):Promise<void>;

export function AttachCalibrationCert(arg1:string,arg2:string):Promise<void>;

export function AttachCostingSheetFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.CostingSheetAttachmentSummary>;

export function AttachCostingSheetFileWithDialog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.CostingSheetAttachmentSummary>;

export function AutoExpireOffers():Promise<void>;

export function AutoMatchBankLines(arg1:string):Promise<banking.BankReconciliationMatchResult>;

export function AutoMatchChequesToStatement(arg1:string,arg2:string):Promise<number>;

export function AutoMatchDepositsToStatement(arg1:string,arg2:string):Promise<number>;

export function BackfillBusinessCustomerIDs():Promise<Record<string, any>>;

export function BackfillInvoiceHashes():Promise<number>;

export function BackfillInvoiceItemsFromOrders():Promise<Record<string, any>>;

export function BackfillOfferItemCostBreakdown():Promise<Record<string, any>>;

export function BackfillRFQDocumentTracking():Promise<number>;

export function BackfillWonOfferItemsFromOpportunityProductDetails():Promise<Record<string, any>>;

export function BackupDatabase():Promise<string>;

export function BatchCreateInvoiceItems(arg1:Array<finance.DBInvoiceItem>):Promise<void>;

export function BatchImportCostingSheets(arg1:string):Promise<main.ExcelBatchImportResult>;

export function BatchParseMSGFiles(arg1:string):Promise<main.BatchParseResult>;

export function BatchPredict(arg1:Array<prediction.Customer>):Promise<main.BatchResult>;

export function BatchUpdateCustomerGrade(arg1:Array<string>,arg2:string):Promise<void>;

export function BatchUpdateOrderStatus(arg1:Array<string>,arg2:string):Promise<void>;

export function BlockDevice(arg1:string):Promise<void>;

export function BrowseFolder():Promise<string>;

export function BuildEntityGraph():Promise<graph.BuildStats>;

export function BulkUpdateOfferStage(arg1:Array<string>,arg2:string):Promise<void>;

export function CalculateARAgingBuckets():Promise<Array<finance.ARAgingBucket>>;

export function CalculateCosting(arg1:main.CostingRequest):Promise<main.CostingResult>;

export function CalculateFXRevaluation(arg1:string,arg2:time.Time):Promise<finance.FXRevaluation>;

export function CalculateInvoiceMargin(arg1:string):Promise<void>;

export function CalculateSupplierLeadTime(arg1:string):Promise<main.SupplierLeadTimeMetrics>;

export function CanResolveOpportunityConflicts():Promise<boolean>;

export function CanViewUserActivityMonitoring():Promise<boolean>;

export function CancelCheque(arg1:string,arg2:string):Promise<void>;

export function CancelJob(arg1:string):Promise<void>;

export function CancelOfferFollowUp(arg1:string):Promise<void>;

export function CancelScan(arg1:string):Promise<void>;

export function CategorizeTransactions(arg1:string):Promise<void>;

export function ChatWithButler(arg1:string):Promise<butler.ButlerResponse>;

export function ChatWithButlerPersistent(arg1:string,arg2:string):Promise<main.ChatResponse>;

export function CheckCompliance(arg1:engines.ComplianceData):Promise<engines.ComplianceResult>;

export function CheckDeviceStatus():Promise<device.RegistrationResult>;

export function CheckDuplicateOpportunity(arg1:string,arg2:string,arg3:string):Promise<crm.Opportunity>;

export function CheckDuplicateRFQ(arg1:string,arg2:string,arg3:string):Promise<main.RFQData>;

export function CheckDuplicateStatement(arg1:finance.BankStatement,arg2:Array<finance.BankStatementLine>):Promise<finance.DuplicateStatementCheck>;

export function CheckFirstInstall():Promise<boolean>;

export function CheckPermissionByRole(arg1:string,arg2:string):Promise<boolean>;

export function ClassifyDocument(arg1:string,arg2:string):Promise<main.ClassificationResult>;

export function ClassifyFilesystemDocuments(arg1:string):Promise<main.FilesystemClassificationSummary>;

export function CleanupOldJobs(arg1:number):Promise<void>;

export function ClearDepositInTransit(arg1:string,arg2:string,arg3:time.Time):Promise<void>;

export function ClearHistory():Promise<void>;

export function ClearSyncHistory():Promise<void>;

export function CloneCostingAsNewRevision(arg1:number,arg2:string):Promise<main.CostingSheetData>;

export function ClosePeriod(arg1:string):Promise<void>;

export function CompareWilliamsLinear(arg1:number):Promise<Record<string, any>>;

export function CompleteFollowUp(arg1:string):Promise<void>;

export function CompleteGRN(arg1:string):Promise<void>;

export function CompleteOfferFollowUp(arg1:string):Promise<void>;

export function CompleteSetup():Promise<void>;

export function ComputeStatementHash(arg1:finance.BankStatement,arg2:Array<finance.BankStatementLine>):Promise<string>;

export function ConfigureWatchPaths(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ConfirmBankStatementImport(arg1:string):Promise<finance.BankStatement>;

export function ConfirmDelivery(arg1:string):Promise<void>;

export function ConfirmDeliveryNote(arg1:string,arg2:string):Promise<string>;

export function ConfirmOneDriveDeal(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ConvertOfferToOrder(arg1:number):Promise<void>;

export function ConvertProformaToInvoice(arg1:string,arg2:string):Promise<finance.Invoice>;

export function CreateAccount(arg1:finance.ChartOfAccount):Promise<finance.ChartOfAccount>;

export function CreateBankAccount(arg1:finance.CompanyBankAccount):Promise<finance.CompanyBankAccount>;

export function CreateBankStatement(arg1:finance.BankStatement):Promise<void>;

export function CreateBankStatementLine(arg1:string,arg2:Record<string, any>):Promise<finance.BankStatementLine>;

export function CreateBookBankReconciliation(arg1:string,arg2:time.Time,arg3:number,arg4:number,arg5:number,arg6:number):Promise<finance.BookBankReconciliation>;

export function CreateChequeRegister(arg1:string,arg2:string,arg3:number,arg4:number):Promise<finance.ChequeRegister>;

export function CreateCollaborativeProject(arg1:main.Project):Promise<main.Project>;

export function CreateCollaborativeTask(arg1:main.TaskItem):Promise<main.TaskItem>;

export function CreateConversation(arg1:string):Promise<butler.Conversation>;

export function CreateCostingSheet(arg1:number,arg2:string,arg3:string):Promise<main.CostingSheetData>;

export function CreateCostingSheetVersion(arg1:string,arg2:string):Promise<crm.DBCostingSheet>;

export function CreateCreditNote(arg1:string,arg2:string,arg3:Array<main.CreditNoteItemInput>):Promise<finance.CreditNote>;

export function CreateCustomer(arg1:crm.CustomerMaster):Promise<crm.CustomerMaster>;

export function CreateCustomerFolder(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateCustomerFromButler(arg1:main.ButlerCustomerRequest):Promise<crm.CustomerMaster>;

export function CreateCustomerReceipt(arg1:main.CustomerReceiptInput):Promise<main.CustomerReceipt>;

export function CreateDNFromOrder(arg1:string,arg2:Array<crm.DeliveryNoteItem>):Promise<crm.DeliveryNote>;

export function CreateDNWithSerials(arg1:string,arg2:Array<main.DNItemInputWithSerials>,arg3:main.DeliveryNoteHeaderInput):Promise<crm.DeliveryNote>;

export function CreateDeliveryNote(arg1:crm.DeliveryNote):Promise<crm.DeliveryNote>;

export function CreateDeliveryNoteWithItems(arg1:string,arg2:Array<main.DeliveryNoteItemInput>):Promise<crm.DeliveryNote>;

export function CreateDepositInTransit(arg1:string,arg2:time.Time,arg3:number,arg4:string,arg5:string,arg6:string,arg7:any,arg8:Array<string>):Promise<finance.DepositInTransit>;

export function CreateDraftJournalFromPosting(arg1:string,arg2:string):Promise<finance.JournalEntry>;

export function CreateEmployeeAccessLink(arg1:main.EmployeeAccessLink):Promise<main.EmployeeAccessLink>;

export function CreateEmployeeDocument(arg1:main.EmployeeDocument,arg2:string):Promise<main.EmployeeDocumentDTO>;

export function CreateEmployeeProfile(arg1:main.Employee):Promise<main.Employee>;

export function CreateExpenseCategory(arg1:finance.ExpenseCategory):Promise<finance.ExpenseCategory>;

export function CreateExpenseEntry(arg1:finance.ExpenseEntry):Promise<finance.ExpenseEntry>;

export function CreateExpenseFromBankCandidate(arg1:string,arg2:string):Promise<finance.ExpenseEntry>;

export function CreateExpenseVendor(arg1:finance.ExpenseVendor):Promise<finance.ExpenseVendor>;

export function CreateFXRate(arg1:string,arg2:string,arg3:number,arg4:time.Time,arg5:string):Promise<finance.FXRate>;

export function CreateFolderStructure(arg1:string,arg2:string):Promise<main.FolderStructureResult>;

export function CreateFollowUp(arg1:crm.FollowUpTask):Promise<crm.FollowUpTask>;

export function CreateGRN(arg1:crm.GoodsReceivedNote):Promise<crm.GoodsReceivedNote>;

export function CreateInventoryItem(arg1:crm.InventoryItem):Promise<crm.InventoryItem>;

export function CreateInvoiceFromDN(arg1:string):Promise<finance.Invoice>;

export function CreateInvoiceFromOrder(arg1:string):Promise<finance.Invoice>;

export function CreateInvoiceFromOrderWithCreditOverride(arg1:string,arg2:string):Promise<finance.Invoice>;

export function CreateInvoiceFromOrderWithDN(arg1:string,arg2:string):Promise<finance.Invoice>;

export function CreateInvoiceWithCreditOverride(arg1:string,arg2:string,arg3:string,arg4:string):Promise<finance.Invoice>;

export function CreateInvoiceWithOptions(arg1:string,arg2:string,arg3:string):Promise<finance.Invoice>;

export function CreateJournalEntry(arg1:finance.JournalEntry):Promise<finance.JournalEntry>;

export function CreateOffer(arg1:string):Promise<main.OfferData>;

export function CreateOfferDraftFromButler(arg1:main.ButlerOfferDraftRequest):Promise<crm.Offer>;

export function CreateOfferRevision(arg1:string):Promise<crm.Offer>;

export function CreateOrder(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string):Promise<crm.Order>;

export function CreateOrderWithItems(arg1:crm.Order,arg2:Array<crm.OrderItem>):Promise<crm.Order>;

export function CreatePOFromOrder(arg1:string,arg2:string,arg3:Array<string>):Promise<crm.PurchaseOrder>;

export function CreatePOsFromOrder(arg1:string,arg2:Array<string>):Promise<Array<crm.PurchaseOrder>>;

export function CreatePayrollPeriod(arg1:payroll.Period):Promise<payroll.Period>;

export function CreatePostSaleNote(arg1:crm.PostSaleNote):Promise<crm.PostSaleNote>;

export function CreateProformaInvoice(arg1:string):Promise<finance.Invoice>;

export function CreateProformaInvoiceManual(arg1:string,arg2:string,arg3:Array<main.ProformaInvoiceItemInput>,arg4:string):Promise<finance.Invoice>;

export function CreatePurchaseOrder(arg1:crm.PurchaseOrder):Promise<crm.PurchaseOrder>;

export function CreateQuickCapture(arg1:string,arg2:string,arg3:string,arg4:string):Promise<number>;

export function CreateRFQ(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string):Promise<main.RFQData>;

export function CreateRFQWithReference(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<main.RFQData>;

export function CreateRecurringExpense(arg1:finance.RecurringExpense):Promise<finance.RecurringExpense>;

export function CreateReportDraft(arg1:string,arg2:string,arg3:Record<string, any>):Promise<string>;

export function CreateShipment(arg1:Array<string>,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CreateSplitAllocation(arg1:string,arg2:Array<banking.AllocationInput>,arg3:string):Promise<void>;

export function CreateStockAdjustment(arg1:crm.StockAdjustment):Promise<void>;

export function CreateSupplier(arg1:crm.SupplierMaster):Promise<crm.SupplierMaster>;

export function CreateSupplierFolder(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateSupplierFromButler(arg1:main.ButlerSupplierRequest):Promise<crm.SupplierMaster>;

export function CreateSupplierInvoice(arg1:finance.SupplierInvoice):Promise<finance.SupplierInvoice>;

export function CreateSupplierInvoiceFromOCR(arg1:string,arg2:string,arg3:string):Promise<finance.SupplierInvoice>;

export function CreateUser(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<infra.User>;

export function CreateWarehouse(arg1:crm.Warehouse):Promise<crm.Warehouse>;

export function DeactivateUser(arg1:string):Promise<void>;

export function DeleteAsset(arg1:string):Promise<void>;

export function DeleteBankAccount(arg1:string):Promise<void>;

export function DeleteBankStatement(arg1:string):Promise<void>;

export function DeleteBankStatementLine(arg1:string):Promise<void>;

export function DeleteCollaborativeProject(arg1:string,arg2:string):Promise<void>;

export function DeleteCollaborativeTask(arg1:string):Promise<void>;

export function DeleteConversation(arg1:string):Promise<void>;

export function DeleteCostingSheet(arg1:number):Promise<void>;

export function DeleteCostingSheetAttachment(arg1:string):Promise<void>;

export function DeleteCustomer(arg1:string):Promise<void>;

export function DeleteCustomerContact(arg1:string):Promise<void>;

export function DeleteCustomerInvoice(arg1:string):Promise<void>;

export function DeleteDeliveryNote(arg1:string):Promise<void>;

export function DeleteEmployeeDocument(arg1:string):Promise<void>;

export function DeleteExpenseCategory(arg1:string):Promise<void>;

export function DeleteExpenseEntry(arg1:string):Promise<void>;

export function DeleteExpenseVendor(arg1:string):Promise<void>;

export function DeleteFXRate(arg1:string):Promise<void>;

export function DeleteGRN(arg1:string):Promise<void>;

export function DeleteOffer(arg1:string):Promise<void>;

export function DeleteOfferNote(arg1:string):Promise<void>;

export function DeleteOpportunity(arg1:string):Promise<void>;

export function DeleteOpportunityComment(arg1:string):Promise<void>;

export function DeleteOrder(arg1:string):Promise<void>;

export function DeletePayment(arg1:string):Promise<void>;

export function DeletePostSaleNote(arg1:number):Promise<void>;

export function DeletePurchaseOrder(arg1:string):Promise<void>;

export function DeleteQuickCapture(arg1:string):Promise<void>;

export function DeleteRFQ(arg1:number):Promise<void>;

export function DeleteRFQWithCascade(arg1:number,arg2:boolean):Promise<main.DeleteCascadeResult>;

export function DeleteRecurringExpense(arg1:string):Promise<void>;

export function DeleteRemoteReport(arg1:string):Promise<void>;

export function DeleteSupplier(arg1:string):Promise<void>;

export function DeleteSupplierContact(arg1:string):Promise<void>;

export function DeleteSupplierInvoice(arg1:string):Promise<void>;

export function DeleteSupplierPayment(arg1:string):Promise<void>;

export function DetectGPU():Promise<main.GPUInfo>;

export function DetectOffice():Promise<main.OfficeInfo>;

export function DetectOneDrivePath():Promise<string>;

export function DetectSystemInfo():Promise<main.SystemInfo>;

export function DiscardBankStatementImportPreview(arg1:string):Promise<void>;

export function DismissAlert(arg1:number):Promise<void>;

export function DispatchDeliveryNote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DisputeSupplierInvoice(arg1:string,arg2:string):Promise<void>;

export function DownloadContract(arg1:number):Promise<string>;

export function DownloadReport(arg1:string):Promise<string>;

export function EndUserActivitySession(arg1:string):Promise<void>;

export function EnsureAssetsTable():Promise<void>;

export function EnsureCollaborativeFoundation():Promise<void>;

export function EnsureExpenseFoundation():Promise<void>;

export function EnsureLicenseTableExists():Promise<void>;

export function EnsureOpportunityConflictFoundation():Promise<void>;

export function EnsurePayrollFoundation():Promise<void>;

export function EnsurePhase7Rollout():Promise<void>;

export function EnsureUserActivityMonitoringFoundation():Promise<void>;

export function ExhaustChequeRegister(arg1:string):Promise<void>;

export function ExportBalanceSheetCSV(arg1:number):Promise<string>;

export function ExportBusinessMemoryReviewBundle(arg1:string):Promise<main.BusinessMemoryReviewExportResult>;

export function ExportCashflowEvidencePack(arg1:number):Promise<string>;

export function ExportCostingToExcel(arg1:main.CostingExportData):Promise<string>;

export function ExportCostingToPDF(arg1:main.CostingExportData):Promise<string>;

export function ExportCustomerTemplate():Promise<prediction.Customer>;

export function ExportEncryptionBackup():Promise<Record<string, string>>;

export function ExportGeneralLedgerCSV(arg1:number):Promise<string>;

export function ExportGraphJSON():Promise<string>;

export function ExportJournalCSV(arg1:number):Promise<string>;

export function ExportPilotSignoffReport():Promise<main.PilotExportResult>;

export function ExportPilotSupportBundle():Promise<main.PilotSupportBundleResult>;

export function ExportReconciliationReport(arg1:main.ReconciliationResult,arg2:string):Promise<void>;

export function ExportReport(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportVATReturnData(arg1:number,arg2:number):Promise<string>;

export function ExtractInvoiceDocument(arg1:string):Promise<main.OCRResultSimple>;

export function ExtractQuotationDocument(arg1:string):Promise<main.OCRResultSimple>;

export function ExtractRFQDocument(arg1:string):Promise<main.OCRResultSimple>;

export function FileVATReturn(arg1:number):Promise<void>;

export function FilterOrders(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<Array<crm.Order>>;

export function FinalizeBookBankReconciliation(arg1:string,arg2:string):Promise<void>;

export function FinalizeReconciliation(arg1:string,arg2:string):Promise<void>;

export function FindOfferByReference(arg1:string):Promise<crm.Offer>;

export function FirstRunSyncWithProgress():Promise<main.DBSyncResult>;

export function FixDatabaseDates():Promise<Record<string, number>>;

export function FixPurchaseOrderSupplierNames():Promise<number>;

export function ForceReimportStatement(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GenerateAuditReport(arg1:string,arg2:time.Time,arg3:time.Time):Promise<Record<string, any>>;

export function GenerateBalanceSheet(arg1:number):Promise<main.TallyBalanceSheet>;

export function GenerateBatchLicenseKeys(arg1:string,arg2:number,arg3:string,arg4:string):Promise<Array<string>>;

export function GenerateBusinessMemoryContextPack(arg1:string):Promise<main.BusinessMemoryContextPackResult>;

export function GenerateButlerReport(arg1:string,arg2:string):Promise<string>;

export function GenerateContract(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<contract.Contract>;

export function GenerateCreditNoteNumber():Promise<string>;

export function GenerateCreditNotePDF(arg1:string):Promise<string>;

export function GenerateCustomer360Report(arg1:string):Promise<string>;

export function GenerateDNNumber():Promise<string>;

export function GenerateDailyBriefing(arg1:string):Promise<main.ChatResponse>;

export function GenerateDashboardReport():Promise<string>;

export function GenerateDataImportTemplate():Promise<string>;

export function GenerateDeliveryNotePDF(arg1:string):Promise<string>;

export function GenerateEInvoiceXML(arg1:string):Promise<string>;

export function GenerateGRNNumber():Promise<string>;

export function GenerateInvoiceNumber():Promise<string>;

export function GenerateInvoicePDF(arg1:string):Promise<string>;

export function GenerateLicenseKey(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GenerateOfferPDF(arg1:string):Promise<string>;

export function GeneratePONumber():Promise<string>;

export function GeneratePayrollRun(arg1:string):Promise<payroll.Run>;

export function GeneratePredictionHistoryReport(arg1:number):Promise<string>;

export function GenerateProfitAndLoss(arg1:number):Promise<main.TallyPLReport>;

export function GeneratePurchaseOrderPDF(arg1:string):Promise<string>;

export function GenerateRecurringExpenses(arg1:string):Promise<Array<finance.ExpenseEntry>>;

export function GenerateReportAsync(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GenerateSeedData(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GenerateSupplierInvoicePDF(arg1:string):Promise<string>;

export function GenerateVATReturn(arg1:time.Time,arg2:time.Time):Promise<finance.VATReturn>;

export function GetAIProviderKeyStatus():Promise<main.AIProviderKeyStatus>;

export function GetAPAgingReport():Promise<main.ARAgingReport>;

export function GetARAgingByCustomer(arg1:string):Promise<finance.ARAgingBucket>;

export function GetARAgingReport():Promise<main.ARAgingReport>;

export function GetAccessToken():Promise<string>;

export function GetAccessTokenWithValidation():Promise<string>;

export function GetActiveBankAccounts():Promise<Array<finance.CompanyBankAccount>>;

export function GetActiveChequeRegister(arg1:string):Promise<finance.ChequeRegister>;

export function GetActiveCostingByRFQ(arg1:number):Promise<main.CostingSheetData>;

export function GetActiveCurrencyRates():Promise<Array<finance.CurrencyExchangeRate>>;

export function GetAlertSummary():Promise<main.AlertSummary>;

export function GetAllBankAccounts():Promise<Array<finance.CompanyBankAccount>>;

export function GetAllCustomers():Promise<Array<crm.CustomerMaster>>;

export function GetAllFXRates(arg1:string,arg2:time.Time):Promise<Array<finance.FXRate>>;

export function GetAllOffers():Promise<Array<crm.Offer>>;

export function GetAllPayments(arg1:number,arg2:number):Promise<Array<finance.Payment>>;

export function GetAllSupplierPayments():Promise<Array<finance.SupplierPayment>>;

export function GetApplicationPaths():Promise<main.ApplicationPaths>;

export function GetAsset(arg1:string):Promise<Array<number>>;

export function GetAssetToFile(arg1:string):Promise<string>;

export function GetAuditLogs(arg1:number,arg2:string,arg3:string):Promise<Array<infra.AuditLog>>;

export function GetAuditTrail(arg1:string):Promise<Array<finance.BankReconciliationAuditLog>>;

export function GetAuditTrailByDateRange(arg1:string,arg2:time.Time,arg3:time.Time):Promise<Array<finance.BankReconciliationAuditLog>>;

export function GetAuthState():Promise<main.AuthState>;

export function GetAvailableDeliveryNotesForOrder(arg1:string):Promise<Array<crm.DeliveryNote>>;

export function GetAvailableFinancialYears():Promise<Array<number>>;

export function GetAvailableSerials(arg1:string):Promise<Array<crm.SerialNumber>>;

export function GetBackupInfo():Promise<Record<string, any>>;

export function GetBackupPolicy():Promise<infra.BackupPolicy>;

export function GetBalanceContinuityReport(arg1:string):Promise<finance.BalanceContinuityReportData>;

export function GetBalanceSheet(arg1:time.Time):Promise<main.BalanceSheetReport>;

export function GetBankAccountByID(arg1:string):Promise<finance.CompanyBankAccount>;

export function GetBankStatementByID(arg1:string):Promise<finance.BankStatement>;

export function GetBankStatementLines(arg1:string):Promise<Array<finance.BankStatementLine>>;

export function GetBankStatements(arg1:string):Promise<Array<finance.BankStatement>>;

export function GetBookBankReconciliation(arg1:string):Promise<finance.BookBankReconciliation>;

export function GetBookBankReconciliationReport(arg1:string):Promise<main.BookBankReconciliationReport>;

export function GetBookBankReconciliations(arg1:string):Promise<Array<finance.BookBankReconciliation>>;

export function GetBusinessMemoryReviewQueue(arg1:string):Promise<documents.IntakeReviewVM>;

export function GetBusinessVATRate():Promise<number>;

export function GetButlerDailyBriefing(arg1:string):Promise<main.ChatResponse>;

export function GetCRMCustomerDashboard():Promise<main.CRMCustomerDashboard>;

export function GetCRMCustomerDashboardByYear(arg1:number):Promise<main.CRMCustomerDashboard>;

export function GetCRMSupplierDashboard():Promise<main.CRMSupplierDashboard>;

export function GetCRMSupplierDashboardByYear(arg1:number):Promise<main.CRMSupplierDashboard>;

export function GetCSRFToken():Promise<string>;

export function GetCacheStats():Promise<Record<string, any>>;

export function GetCashFlowProjection(arg1:number):Promise<main.CashFlowProjection>;

export function GetCashPosition():Promise<Record<string, any>>;

export function GetCashPositionByAccount(arg1:string):Promise<number>;

export function GetCashflowEvidenceAgentBrief(arg1:number,arg2:number):Promise<string>;

export function GetCashflowEvidenceCommandCenter(arg1:number):Promise<evidence.CommandCenter>;

export function GetChartOfAccounts(arg1:string):Promise<Array<finance.ChartOfAccount>>;

export function GetChequeByNumber(arg1:string):Promise<finance.OutstandingCheque>;

export function GetChequeRegisterReport(arg1:string,arg2:time.Time,arg3:time.Time):Promise<Record<string, any>>;

export function GetChequeRegisters(arg1:string):Promise<Array<finance.ChequeRegister>>;

export function GetChequesByStatus(arg1:string,arg2:string):Promise<Array<finance.OutstandingCheque>>;

export function GetClassificationStats():Promise<Record<string, any>>;

export function GetCollaborativeTask(arg1:string):Promise<main.TaskItem>;

export function GetCollectionPerformance():Promise<Record<string, any>>;

export function GetConfig():Promise<Record<string, any>>;

export function GetContract(arg1:number):Promise<contract.Contract>;

export function GetContractTemplates():Promise<Array<contract.Template>>;

export function GetContracts(arg1:number,arg2:number):Promise<Array<contract.Contract>>;

export function GetContractsByCustomer(arg1:number):Promise<Array<contract.Contract>>;

export function GetConversationMessages(arg1:string):Promise<Array<butler.ChatMessage>>;

export function GetCostingSheet(arg1:number):Promise<main.CostingSheetData>;

export function GetCostingSheets(arg1:number):Promise<Array<main.CostingSheetData>>;

export function GetCostingsByOpportunity(arg1:string):Promise<Array<main.CostingSheetData>>;

export function GetCostingsByRFQ(arg1:number):Promise<Array<main.CostingSheetData>>;

export function GetCreditNote(arg1:string):Promise<finance.CreditNote>;

export function GetCurrencyRateHistory(arg1:string):Promise<Array<finance.CurrencyExchangeRate>>;

export function GetCurrentDeviceInfo():Promise<infra.Device>;

export function GetCurrentEmployeeContext():Promise<main.CurrentEmployeeContext>;

export function GetCurrentExchangeRate(arg1:string):Promise<number>;

export function GetCurrentUserRole():Promise<string>;

export function GetCurrentUserStub():Promise<infra.User>;

export function GetCustomer(arg1:string):Promise<crm.CustomerMaster>;

export function GetCustomer360(arg1:string):Promise<main.Customer360Data>;

export function GetCustomer360Geometry(arg1:string):Promise<engines.Customer360>;

export function GetCustomer360Graph(arg1:string):Promise<main.Customer360Graph>;

export function GetCustomer360View(arg1:string):Promise<main.Customer360Data>;

export function GetCustomerFullProfile(arg1:string):Promise<main.CustomerFullProfile>;

export function GetCustomerGraph(arg1:string,arg2:number):Promise<graph.GraphData>;

export function GetCustomerHistory(arg1:string):Promise<Array<butler.PredictionRecord>>;

export function GetCustomerInvoiceByID(arg1:string):Promise<finance.Invoice>;

export function GetCustomerLedger(arg1:string,arg2:string,arg3:string):Promise<Array<main.OperationalLedgerEntry>>;

export function GetCustomerNameMapping():Promise<Record<string, string>>;

export function GetCustomerOpportunities(arg1:string):Promise<Array<main.OpportunitySummary>>;

export function GetCustomerOrderHistorySummary(arg1:string):Promise<main.CustomerOrderHistorySummary>;

export function GetCustomerReceiptAllocations(arg1:string):Promise<Array<main.CustomerReceiptAllocation>>;

export function GetCustomerRecentOrders(arg1:string,arg2:number):Promise<Array<main.OrderSummary>>;

export function GetCustomerRelatedProducts(arg1:string):Promise<Array<main.CustomerRelatedProduct>>;

export function GetCustomerRelatedSuppliers(arg1:string):Promise<Array<main.CustomerRelatedSupplier>>;

export function GetCustomerWinRates():Promise<Array<main.CustomerWinRate>>;

export function GetCustomersByGrade(arg1:string):Promise<Array<crm.CustomerMaster>>;

export function GetDBSyncSettings():Promise<main.DBSyncSettings>;

export function GetDBSyncStatus():Promise<Record<string, any>>;

export function GetDashboardARAgingReportYTD():Promise<main.ARAgingReport>;

export function GetDashboardEvents(arg1:number):Promise<Array<main.DashboardEvent>>;

export function GetDashboardPipelineByStageYTD():Promise<Array<main.SalesPipelineData>>;

export function GetDashboardStats():Promise<main.DashboardStats>;

export function GetDashboardStatsOptimized():Promise<Record<string, any>>;

export function GetDashboardStatsV2():Promise<main.DashboardStatsV2>;

export function GetDataQualityReviewHistory(arg1:number):Promise<Array<main.DataQualityReview>>;

export function GetDealTimeline(arg1:string):Promise<main.DealTimeline>;

export function GetDealTimelineByOrderNumber(arg1:string):Promise<main.DealTimeline>;

export function GetDeliveriesByArea(arg1:string):Promise<Array<main.DeliveryPlanningItem>>;

export function GetDeliveryAreaSummary():Promise<Record<string, number>>;

export function GetDeliveryNoteByID(arg1:string):Promise<crm.DeliveryNote>;

export function GetDeliveryNotes():Promise<Array<crm.DeliveryNote>>;

export function GetDeliveryNotesByCustomer(arg1:string):Promise<Array<crm.DeliveryNote>>;

export function GetDeliveryNotesByOrder(arg1:string):Promise<Array<crm.DeliveryNote>>;

export function GetDeploymentDataAudit():Promise<main.DeploymentDataAudit>;

export function GetDepositsInTransit(arg1:string):Promise<main.DepositsInTransitResult>;

export function GetDeviceUsers(arg1:string):Promise<Array<infra.DeviceUser>>;

export function GetDiscrepanciesByType(arg1:string,arg2:string,arg3:string):Promise<Array<main.DataDiscrepancy>>;

export function GetDynamicFinancialDashboard(arg1:number):Promise<main.FinancialDashboard>;

export function GetEmployeeAllocationSummary(arg1:string,arg2:string):Promise<main.AllocationSummary>;

export function GetEntityGraph(arg1:string,arg2:number):Promise<graph.GraphData>;

export function GetExchangeRate(arg1:string,arg2:time.Time):Promise<number>;

export function GetExpenseLedger(arg1:main.OperationalLedgerFilter):Promise<Array<main.OperationalLedgerEntry>>;

export function GetFXExposureReport():Promise<fx.ExposureResult>;

export function GetFXGainLossSummary(arg1:number):Promise<Record<string, any>>;

export function GetFXRate(arg1:string,arg2:string,arg3:time.Time):Promise<finance.FXRate>;

export function GetFXRateHistory(arg1:string,arg2:string,arg3:time.Time,arg4:time.Time):Promise<Array<finance.FXRate>>;

export function GetFXRevaluations(arg1:string):Promise<Array<finance.FXRevaluation>>;

export function GetFileHash(arg1:string):Promise<string>;

export function GetFilesystemClassificationStats(arg1:string):Promise<Record<string, any>>;

export function GetFilesystemDocumentsByCustomer(arg1:string,arg2:string):Promise<Array<main.FilesystemDocClassification>>;

export function GetFilesystemDocumentsByOfferNumber(arg1:string,arg2:string):Promise<Array<main.FilesystemDocClassification>>;

export function GetFilesystemDocumentsByType(arg1:string,arg2:string):Promise<Array<main.FilesystemDocClassification>>;

export function GetFinancialDashboard():Promise<main.FinancialDashboard>;

export function GetFinancialDashboardByDivision(arg1:number,arg2:string):Promise<main.DivisionFinancialSummary>;

export function GetFinancialDashboardForYear(arg1:number):Promise<main.FinancialDashboard>;

export function GetFinancialReportYears():Promise<Array<number>>;

export function GetFinancialYearData(arg1:number):Promise<main.FinancialYearSummary>;

export function GetFirstRunSyncStatus():Promise<Record<string, any>>;

export function GetFolderPaths():Promise<Record<string, string>>;

export function GetGRN(arg1:string):Promise<main.GRNResponse>;

export function GetGRNByID(arg1:string):Promise<crm.GoodsReceivedNote>;

export function GetGRNs():Promise<Array<crm.GoodsReceivedNote>>;

export function GetGRNsByPO(arg1:string):Promise<Array<crm.GoodsReceivedNote>>;

export function GetGraphStats():Promise<graph.GraphStats>;

export function GetHistory(arg1:number):Promise<Array<butler.PredictionRecord>>;

export function GetInboxDocuments(arg1:string):Promise<Array<main.InboxDocument>>;

export function GetInboxStats():Promise<main.InboxStats>;

export function GetInventoryAlertsLowStock(arg1:number):Promise<Array<main.InventoryAlert>>;

export function GetInventoryAlertsSlowMoving(arg1:number):Promise<Array<main.InventoryAlert>>;

export function GetInventoryAlertsSummary():Promise<Record<string, number>>;

export function GetInventoryItem(arg1:string):Promise<crm.InventoryItem>;

export function GetInventoryItems(arg1:any,arg2:string,arg3:boolean):Promise<Array<crm.InventoryItem>>;

export function GetInventoryMovementsWorkspace(arg1:number):Promise<Array<crm.StockMovement>>;

export function GetInventoryPendingFulfillmentReport(arg1:number):Promise<Array<main.InventoryPendingFulfillmentRow>>;

export function GetInventoryValuation(arg1:any):Promise<Record<string, any>>;

export function GetInvoiceAuditTrail(arg1:string):Promise<main.InvoiceAuditTrail>;

export function GetInvoiceListVM(arg1:number,arg2:number):Promise<finance.InvoiceListVM>;

export function GetInvoiceRevenueSummary():Promise<number>;

export function GetInvoiceWithItems(arg1:string):Promise<finance.Invoice>;

export function GetInvoicesByAgingBucket(arg1:string,arg2:number,arg3:number):Promise<main.AgingBucketInvoices>;

export function GetInvoicesByCustomer(arg1:string):Promise<Array<finance.Invoice>>;

export function GetInvoicesByDateRange(arg1:time.Time,arg2:time.Time):Promise<Array<finance.Invoice>>;

export function GetInvoicesByOrder(arg1:string):Promise<Array<finance.Invoice>>;

export function GetInvoicesByRFQ(arg1:string):Promise<Array<finance.Invoice>>;

export function GetInvoicesByStatus(arg1:string):Promise<Array<finance.Invoice>>;

export function GetJobStatus(arg1:string):Promise<main.JobStatusResponse>;

export function GetJournalEntries(arg1:number,arg2:number,arg3:any,arg4:number):Promise<Array<finance.JournalEntry>>;

export function GetLatePaymentInvoices():Promise<Array<finance.Invoice>>;

export function GetLateSuppliers():Promise<Array<main.SupplierLeadTimeMetrics>>;

export function GetLatestBookBankReconciliation(arg1:string):Promise<finance.BookBankReconciliation>;

export function GetLatestFXRate(arg1:string,arg2:string):Promise<finance.FXRate>;

export function GetLetterheadPath():Promise<string>;

export function GetLicenseRole():Promise<string>;

export function GetLowMarginOffers(arg1:number):Promise<Array<crm.Offer>>;

export function GetLowStockItems():Promise<Array<crm.InventoryItem>>;

export function GetMSGFileInfo(arg1:string):Promise<Record<string, any>>;

export function GetMarginAnalysisByCustomer():Promise<Array<main.MarginAnalysisByCustomer>>;

export function GetMarginAnalysisByProduct():Promise<Array<main.MarginAnalysisByProduct>>;

export function GetMasterDataCleanupAudit():Promise<main.MasterDataCleanupAudit>;

export function GetMonthlyRevenueByCustomer():Promise<Array<main.CustomerRevenueData>>;

export function GetNextChequeNumber(arg1:string):Promise<string>;

export function GetNodeRelationships(arg1:number):Promise<Array<graph.GraphEdge>>;

export function GetOCRDocumentByID(arg1:string):Promise<main.OCRDocument>;

export function GetOCRDocuments(arg1:number):Promise<Array<main.OCRDocument>>;

export function GetOCRDocumentsByType(arg1:string,arg2:number):Promise<Array<main.OCRDocument>>;

export function GetOCRPipelineStats():Promise<Record<string, any>>;

export function GetOCRProcessorStats():Promise<Record<string, any>>;

export function GetOCRStats():Promise<Record<string, any>>;

export function GetOffer(arg1:number):Promise<main.OfferData>;

export function GetOfferFollowUps(arg1:string):Promise<Array<crm.OfferFollowUp>>;

export function GetOfferNotes(arg1:string):Promise<Array<crm.OfferNote>>;

export function GetOfferRevisionHistory(arg1:string):Promise<Array<main.OfferRevision>>;

export function GetOffers(arg1:number):Promise<Array<main.OfferData>>;

export function GetOffersWithNoItems():Promise<Array<Record<string, any>>>;

export function GetOperationalBalanceSheet(arg1:string,arg2:string):Promise<main.OperationalBalanceSheetReport>;

export function GetOperationalLedger(arg1:main.OperationalLedgerFilter):Promise<Array<main.OperationalLedgerEntry>>;

export function GetOperationalProfitLoss(arg1:main.OperationalLedgerFilter):Promise<main.OperationalProfitLossReport>;

export function GetOpportunityComments(arg1:string):Promise<Array<main.OpportunityComment>>;

export function GetOpportunityLineItems(arg1:string):Promise<Array<crm.OfferItem>>;

export function GetOrder(arg1:string):Promise<crm.Order>;

export function GetOrderDeliveryStatus(arg1:string):Promise<Record<string, number>>;

export function GetOrderDeliveryStatusBatch(arg1:Array<string>):Promise<Record<string, Record<string, number>>>;

export function GetOrderFulfillmentDetail(arg1:string):Promise<main.OrderFulfillment>;

export function GetOrderFulfillmentStatus(arg1:string):Promise<main.FulfillmentStatus>;

export function GetOrderWithItems(arg1:string):Promise<crm.Order>;

export function GetOrdersWithNoItems():Promise<Array<Record<string, any>>>;

export function GetOutstandingCheques(arg1:string):Promise<cheque.OutstandingResult>;

export function GetOverdueFollowUps():Promise<Array<crm.FollowUpTask>>;

export function GetOverdueInvoices():Promise<Array<finance.Invoice>>;

export function GetOverdueOfferFollowUps():Promise<Array<crm.OfferFollowUp>>;

export function GetOverdueRFQs():Promise<Array<main.OpportunityDueData>>;

export function GetOverdueSupplierInvoices():Promise<Array<finance.SupplierInvoice>>;

export function GetPOAmendmentHistory(arg1:string):Promise<Array<main.POAmendment>>;

export function GetPayment(arg1:string):Promise<finance.Payment>;

export function GetPaymentAgingReport():Promise<main.PaymentAgingReport>;

export function GetPaymentHistory(arg1:string,arg2:number):Promise<Array<main.PaymentHistoryEntry>>;

export function GetPaymentsByInvoice(arg1:string):Promise<Array<finance.Payment>>;

export function GetPayrollRun(arg1:string):Promise<payroll.Run>;

export function GetPendingDeliveries():Promise<Array<main.DeliveryPlanningItem>>;

export function GetPendingFollowUps():Promise<Array<crm.OfferFollowUp>>;

export function GetPhase7RolloutStatus():Promise<main.Phase7RolloutStatus>;

export function GetPilotDeploymentChecklist():Promise<Array<main.PilotChecklistItem>>;

export function GetPilotReadinessSummary():Promise<main.PilotReadinessSummary>;

export function GetPipelineOpportunities(arg1:number,arg2:number):Promise<Array<crm.Opportunity>>;

export function GetPipelineStatistics():Promise<Record<string, any>>;

export function GetPostSaleNotes(arg1:string):Promise<Array<crm.PostSaleNote>>;

export function GetPostingCoverageReport():Promise<posting.CoverageReport>;

export function GetPreparedByOptions():Promise<Array<string>>;

export function GetPricingRecommendation(arg1:string,arg2:Record<string, any>):Promise<main.PricingRecommendation>;

export function GetProductByCode(arg1:string):Promise<crm.ProductMaster>;

export function GetProfitLoss(arg1:time.Time,arg2:time.Time):Promise<main.ProfitLossReport>;

export function GetProjectTaskCounts():Promise<Record<string, number>>;

export function GetPurchaseOrderByID(arg1:string):Promise<crm.PurchaseOrder>;

export function GetPurchaseOrders():Promise<Array<crm.PurchaseOrder>>;

export function GetPurchaseOrdersByOrder(arg1:string):Promise<Array<crm.PurchaseOrder>>;

export function GetPurchaseOrdersBySupplier(arg1:string):Promise<Array<crm.PurchaseOrder>>;

export function GetQuickCaptures(arg1:number):Promise<Array<main.QuickCapture>>;

export function GetRFQ(arg1:number):Promise<main.RFQData>;

export function GetRFQComments(arg1:number):Promise<Array<main.RFQComment>>;

export function GetRFQTraceability(arg1:string):Promise<main.PipelineTraceability>;

export function GetRFQs(arg1:number,arg2:number):Promise<Array<main.RFQData>>;

export function GetRFQsDueSoon(arg1:number):Promise<Array<main.OpportunityDueData>>;

export function GetReceivablesAging(arg1:string):Promise<main.ReceivablesAgingSummary>;

export function GetRecentEvents(arg1:number):Promise<Array<main.FileSyncState>>;

export function GetRecentJobs(arg1:number):Promise<Array<main.JobSummary>>;

export function GetRecentSyncEvents(arg1:number):Promise<Array<main.FileWatchEvent>>;

export function GetRecentlyDeliveredSerials(arg1:number):Promise<Array<crm.SerialNumber>>;

export function GetReconciliationStats(arg1:string):Promise<Record<string, any>>;

export function GetReconciliationStatusSummary():Promise<Array<main.ReconciliationStatusSummary>>;

export function GetReconciliationSummary(arg1:string):Promise<Record<string, any>>;

export function GetReconciliationVariances(arg1:string):Promise<Array<main.VarianceItem>>;

export function GetReorderSuggestions():Promise<Array<main.ReorderSuggestion>>;

export function GetReportData(arg1:string,arg2:string):Promise<main.ReportData>;

export function GetRole(arg1:number):Promise<infra.Role>;

export function GetRolePermissionsList(arg1:string):Promise<Array<string>>;

export function GetRoutingHistory(arg1:number):Promise<Array<engines.RoutingResult>>;

export function GetSSOTImportStatus():Promise<Record<string, any>>;

export function GetSalesPipeline():Promise<Array<main.SalesPipelineData>>;

export function GetScanProgress(arg1:string):Promise<main.ScanProgress>;

export function GetScanResult(arg1:string):Promise<main.ScanResult>;

export function GetSerialByNumber(arg1:string):Promise<crm.SerialNumber>;

export function GetSerialsByCustomer(arg1:string):Promise<Array<crm.SerialNumber>>;

export function GetSerialsByProduct(arg1:string):Promise<Array<crm.SerialNumber>>;

export function GetSerialsForInvoiceItem(arg1:string,arg2:string):Promise<Array<crm.SerialNumber>>;

export function GetSettings():Promise<Record<string, any>>;

export function GetStaleCheques(arg1:string):Promise<Array<finance.OutstandingCheque>>;

export function GetStatistics():Promise<main.Statistics>;

export function GetStockMovements(arg1:any,arg2:string,arg3:time.Time,arg4:time.Time,arg5:number):Promise<Array<crm.StockMovement>>;

export function GetSupplier(arg1:string):Promise<crm.SupplierMaster>;

export function GetSupplierFullProfile(arg1:string):Promise<main.SupplierFullProfile>;

export function GetSupplierInvoiceByID(arg1:string):Promise<finance.SupplierInvoice>;

export function GetSupplierInvoices():Promise<Array<finance.SupplierInvoice>>;

export function GetSupplierInvoicesByPO(arg1:string):Promise<Array<finance.SupplierInvoice>>;

export function GetSupplierInvoicesBySupplier(arg1:string):Promise<Array<finance.SupplierInvoice>>;

export function GetSupplierLeadTimeReport():Promise<Array<main.SupplierLeadTimeMetrics>>;

export function GetSupplierLedger(arg1:string,arg2:string,arg3:string):Promise<Array<main.OperationalLedgerEntry>>;

export function GetSupplierPayment(arg1:string):Promise<finance.SupplierPayment>;

export function GetSupplierPaymentsByInvoice(arg1:string):Promise<Array<finance.SupplierPayment>>;

export function GetSupplierPaymentsSummary():Promise<Record<string, any>>;

export function GetSupportedCurrencies():Promise<Array<Record<string, string>>>;

export function GetSurvivalMetrics():Promise<main.SurvivalMetrics>;

export function GetSurvivalMetricsOptimized():Promise<main.SurvivalMetrics>;

export function GetSyncHealth():Promise<main.SyncHealth>;

export function GetSyncStatus():Promise<Record<string, any>>;

export function GetToolInstallInstructions():Promise<string>;

export function GetToolsStatus():Promise<integration.ToolsReport>;

export function GetTrialBalanceGate(arg1:number,arg2:number):Promise<posting.TrialBalanceGate>;

export function GetUnifiedOfferThread(arg1:string):Promise<Array<main.UnifiedThreadEntry>>;

export function GetUnmatchedLines(arg1:string):Promise<Array<finance.BankStatementLine>>;

export function GetUnpaidInvoices():Promise<Array<finance.Invoice>>;

export function GetUnpaidSupplierInvoices():Promise<Array<finance.SupplierInvoice>>;

export function GetUnpostedRevaluations():Promise<fx.RevaluationBatchResult>;

export function GetUnreadNotificationsCount():Promise<number>;

export function GetUser(arg1:string):Promise<infra.User>;

export function GetUserPermissions(arg1:string):Promise<Array<string>>;

export function GetVATReconciliation(arg1:string,arg2:string):Promise<main.VATReconciliation>;

export function GetVATReturns(arg1:number,arg2:string):Promise<Array<finance.VATReturn>>;

export function GetWarehouses():Promise<Array<crm.Warehouse>>;

export function GetWatcherStatus():Promise<Record<string, any>>;

export function GetWeeklyUserActivityReport(arg1:string):Promise<main.UserActivityWeeklyReport>;

export function GetWilliamsMetrics(arg1:number):Promise<engines.WilliamsMetrics>;

export function Greet(arg1:string):Promise<string>;

export function HasAsset(arg1:string):Promise<boolean>;

export function HasLicensePermission(arg1:string):Promise<boolean>;

export function HasPermission(arg1:string,arg2:string):Promise<boolean>;

export function Import2026BusinessData(arg1:string):Promise<Record<string, any>>;

export function ImportARDefaulters():Promise<main.TallyImportResult>;

export function ImportAllTallyData():Promise<main.TallyImportResult>;

export function ImportBankStatementCSV(arg1:string,arg2:string):Promise<finance.BankStatement>;

export function ImportBankStatementPDF(arg1:string,arg2:string):Promise<finance.BankStatement>;

export function ImportBankStatementWithDialog(arg1:string):Promise<finance.BankStatement>;

export function ImportCostingToOpportunity(arg1:main.ExcelCostingData):Promise<void>;

export function ImportEncryptionBackup(arg1:string,arg2:string):Promise<void>;

export function ImportOneDriveDeals(arg1:Array<main.DiscoveredDeal>):Promise<Array<main.OneDriveImportResult>>;

export function ImportSSOTData():Promise<data.ImportResult>;

export function ImportSupplierPaymentsFromFile():Promise<main.TallyImportResult>;

export function ImportTallyInvoices(arg1:number):Promise<main.TallyImportResult>;

export function ImportTallyPurchases(arg1:number):Promise<main.TallyImportResult>;

export function ImportTenderFolders(arg1:string):Promise<Array<main.TenderFolderPreview>>;

export function InitDBManager():Promise<void>;

export function InitializeDefaultAssets():Promise<void>;

export function InitializeJobQueue():Promise<void>;

export function InvalidateCache(arg1:string):Promise<void>;

export function IsPeriodClosed(arg1:string):Promise<boolean>;

export function IssueCheque(arg1:string,arg2:number,arg3:string,arg4:string,arg5:any,arg6:string):Promise<finance.OutstandingCheque>;

export function IssueCreditNote(arg1:string):Promise<finance.CreditNote>;

export function LinkInvoiceToOrder(arg1:string,arg2:string):Promise<void>;

export function LinkInvoiceToRFQ(arg1:string,arg2:string):Promise<void>;

export function ListAllDevices():Promise<Array<infra.Device>>;

export function ListAssets():Promise<Array<assets.Info>>;

export function ListBankExpenseCandidates(arg1:boolean):Promise<Array<finance.BankExpenseEntry>>;

export function ListCashflowEvidenceProposalReviews(arg1:number,arg2:boolean):Promise<Array<main.CashflowEvidenceProposalReview>>;

export function ListCollaborativePendingOperations(arg1:string,arg2:number):Promise<Array<main.CollaborativePendingOperation>>;

export function ListCollaborativeProjectActivity(arg1:string):Promise<Array<main.TaskActivity>>;

export function ListCollaborativeProjectMembers(arg1:string):Promise<Array<main.ProjectMember>>;

export function ListCollaborativeProjectTasks(arg1:string,arg2:boolean):Promise<Array<main.TaskItem>>;

export function ListCollaborativeProjects(arg1:boolean):Promise<Array<main.Project>>;

export function ListCollaborativeTaskActivity(arg1:string):Promise<Array<main.TaskActivity>>;

export function ListCollaborativeTaskComments(arg1:string):Promise<Array<main.TaskComment>>;

export function ListCollaborativeTasksForEmployee(arg1:string,arg2:boolean):Promise<Array<main.TaskItem>>;

export function ListCollaborativeTeamTasks(arg1:boolean):Promise<Array<main.TaskItem>>;

export function ListConversations():Promise<Array<butler.Conversation>>;

export function ListCostingSheetAttachments(arg1:string):Promise<Array<main.CostingSheetAttachmentSummary>>;

export function ListCreditNotes(arg1:number,arg2:number):Promise<Array<finance.CreditNote>>;

export function ListCustomerContacts(arg1:string):Promise<Array<crm.CustomerContact>>;

export function ListCustomerInvoices(arg1:number,arg2:number):Promise<Array<finance.Invoice>>;

export function ListCustomerReceipts(arg1:number,arg2:number):Promise<Array<main.CustomerReceipt>>;

export function ListCustomers(arg1:number,arg2:number):Promise<Array<crm.CustomerMaster>>;

export function ListCustomersOptimized(arg1:number):Promise<Array<crm.CustomerMaster>>;

export function ListCustomersPaginated(arg1:number,arg2:number):Promise<main.PaginationResult>;

export function ListDeleteApprovalRequests(arg1:string):Promise<Array<deletion.Request>>;

export function ListEmployeeAccessLinks():Promise<Array<main.EmployeeAccessLink>>;

export function ListEmployeeArchiveRequests(arg1:string):Promise<Array<main.EmployeeArchiveRequest>>;

export function ListEmployeeCompensationProfiles(arg1:boolean):Promise<Array<payroll.CompensationProfile>>;

export function ListEmployeeContributionSummaries():Promise<Array<main.EmployeeContributionSummary>>;

export function ListEmployeeDocuments(arg1:string):Promise<Array<main.EmployeeDocumentDTO>>;

export function ListEmployeeProfiles(arg1:boolean):Promise<Array<main.Employee>>;

export function ListEmployeeProjectAssignments(arg1:string):Promise<Array<main.ProjectMember>>;

export function ListExpenseCategories(arg1:boolean):Promise<Array<finance.ExpenseCategory>>;

export function ListExpenseDashboardSummary():Promise<main.ExpenseDashboardSummary>;

export function ListExpenseEntries(arg1:string,arg2:boolean):Promise<Array<finance.ExpenseEntry>>;

export function ListExpenseVendors(arg1:boolean):Promise<Array<finance.ExpenseVendor>>;

export function ListFollowUps(arg1:number):Promise<Array<crm.FollowUpTask>>;

export function ListGRNs(arg1:number,arg2:number,arg3:string):Promise<Array<main.GRNResponse>>;

export function ListInvoicesPaginated(arg1:number,arg2:number,arg3:string):Promise<main.PaginationResult>;

export function ListLicenseKeys():Promise<Array<main.LicenseKey>>;

export function ListMSGFilesInDirectory(arg1:string):Promise<Array<Record<string, any>>>;

export function ListMyCollaborativeTasks(arg1:boolean):Promise<Array<main.TaskItem>>;

export function ListNotificationFeed(arg1:number,arg2:boolean):Promise<Array<main.Notification>>;

export function ListOffersPaginated(arg1:number,arg2:number,arg3:string):Promise<main.PaginationResult>;

export function ListOpportunityEditConflicts(arg1:string,arg2:number):Promise<Array<main.OpportunityEditConflict>>;

export function ListOrders(arg1:number,arg2:number):Promise<Array<crm.Order>>;

export function ListOrdersPaginated(arg1:number,arg2:number,arg3:string):Promise<main.PaginationResult>;

export function ListPayrollDashboardSummary():Promise<payroll.DashboardSummary>;

export function ListPayrollPayouts(arg1:string):Promise<Array<payroll.Payout>>;

export function ListPayrollPeriods(arg1:boolean):Promise<Array<payroll.Period>>;

export function ListPayrollRuns(arg1:string):Promise<Array<payroll.Run>>;

export function ListPendingDevices():Promise<Array<infra.Device>>;

export function ListPilotReadinessRows(arg1:boolean):Promise<Array<main.PilotReadinessRow>>;

export function ListProductsOptimized(arg1:number,arg2:boolean):Promise<Array<crm.ProductMaster>>;

export function ListProductsPaginated(arg1:number,arg2:number,arg3:string,arg4:boolean):Promise<main.PaginationResult>;

export function ListPurchaseOrdersPaginated(arg1:number,arg2:number,arg3:string):Promise<main.PaginationResult>;

export function ListRecurringExpenses(arg1:boolean):Promise<Array<finance.RecurringExpense>>;

export function ListRemoteReports():Promise<Array<main.ReportMetadata>>;

export function ListRoles():Promise<Array<infra.Role>>;

export function ListShipments():Promise<Array<Record<string, any>>>;

export function ListSupplierContacts(arg1:string):Promise<Array<crm.SupplierContact>>;

export function ListSuppliers(arg1:number,arg2:number):Promise<Array<crm.SupplierMaster>>;

export function ListSuppliersOptimized(arg1:number):Promise<Array<crm.SupplierMaster>>;

export function ListSuppliersPaginated(arg1:number,arg2:number):Promise<main.PaginationResult>;

export function ListUnreconciledPayrollPayouts():Promise<Array<payroll.Payout>>;

export function ListUsers():Promise<Array<infra.User>>;

export function LogMarginAlert(arg1:string,arg2:string,arg3:main.MarginAlert):Promise<void>;

export function LogReconciliationAction(arg1:string,arg2:any,arg3:string,arg4:any,arg5:string,arg6:boolean,arg7:number,arg8:string):Promise<void>;

export function LoginDevice(arg1:string,arg2:string):Promise<device.RegistrationResult>;

export function Logout():Promise<void>;

export function LogoutInteractiveSession():Promise<void>;

export function LogoutWithSession():Promise<void>;

export function ManualMatchLine(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function MarkChequeBounced(arg1:string,arg2:string):Promise<void>;

export function MarkChequeCleared(arg1:string,arg2:string,arg3:time.Time):Promise<void>;

export function MarkChequePresented(arg1:string):Promise<void>;

export function MarkChequeStale(arg1:string):Promise<void>;

export function MarkCustomerInvoiceOverdue(arg1:string):Promise<void>;

export function MarkCustomerInvoicePaid(arg1:string,arg2:time.Time,arg3:string):Promise<void>;

export function MarkExpenseEntryPaid(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<finance.ExpenseEntry>;

export function MarkInboxDocumentProcessed(arg1:string,arg2:string):Promise<void>;

export function MarkNotificationAsRead(arg1:string):Promise<void>;

export function MarkOfferLost(arg1:string,arg2:string):Promise<void>;

export function MarkOfferWon(arg1:string,arg2:string):Promise<crm.Order>;

export function MarkPayrollRunPaid(arg1:string,arg2:string,arg3:string,arg4:string):Promise<payroll.Run>;

export function MarkSupplierInvoicePaid(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MigrateBankAccountEncryption():Promise<void>;

export function NeedsLicenseActivation():Promise<boolean>;

export function NeedsSetup():Promise<boolean>;

export function OpenCostingSheetAttachment(arg1:string):Promise<void>;

export function OpenExportedFile(arg1:string):Promise<void>;

export function ParseCostingSheetFile(arg1:string):Promise<main.ExcelCostingData>;

export function ParseCostingSheetWithDialog():Promise<main.ExcelCostingData>;

export function ParseMSGFile(arg1:string):Promise<main.ParsedRFQEmail>;

export function ParseMSGFileToJSON(arg1:string):Promise<string>;

export function PerformFirstRunSync():Promise<Record<string, any>>;

export function PerformThreeWayMatch(arg1:string):Promise<main.ThreeWayMatchResult>;

export function PickCSVFile(arg1:string):Promise<string>;

export function PickExcelFile():Promise<string>;

export function PickFile(arg1:string):Promise<string>;

export function PostExpenseEntry(arg1:string):Promise<finance.ExpenseEntry>;

export function PostFXRevaluation(arg1:string,arg2:string):Promise<void>;

export function PostJournalEntry(arg1:number):Promise<void>;

export function PostPayrollRun(arg1:string):Promise<payroll.Run>;

export function PredictPayment(arg1:prediction.Customer):Promise<prediction.PaymentPrediction>;

export function PreviewBankStatementImportWithDialog(arg1:string):Promise<finance.BankStatement>;

export function PreviewCustomerDataQuality(arg1:number):Promise<Array<main.DataQualityIssue>>;

export function PreviewCustomerInvoicePosting(arg1:string):Promise<posting.Entry>;

export function PreviewCustomerPaymentPosting(arg1:string):Promise<posting.Entry>;

export function PreviewOrderDeleteCascade(arg1:string):Promise<Record<string, any>>;

export function PreviewSupplierInvoicePosting(arg1:string):Promise<posting.Entry>;

export function PreviewSupplierPaymentPosting(arg1:string):Promise<posting.Entry>;

export function PreviewTenderFolders(arg1:string):Promise<Array<main.TenderFolderPreview>>;

export function ProcessDocumentWithOCR(arg1:string,arg2:string):Promise<main.OCRResultSimple>;

export function ProcessDocumentsBatch(arg1:Array<string>,arg2:string):Promise<Array<main.OCRResultSimple>>;

export function ProcessInboxDocument(arg1:string,arg2:string):Promise<main.InboxProcessResult>;

export function ProcessInvoice(arg1:engines.InvoiceGeometry):Promise<engines.InvoiceResult>;

export function ProcessOffersBatch(arg1:string):Promise<main.BatchOfferResult>;

export function ProcessRFQToOrder(arg1:engines.TenderGeometry,arg2:prediction.Customer):Promise<main.CompleteFlowResult>;

export function ProcessTender(arg1:engines.TenderGeometry):Promise<engines.TenderResult>;

export function ProcessWithFlorence2(arg1:string):Promise<main.OCRResultSimple>;

export function ProcessWithGPU(arg1:string):Promise<main.OCRResultSimple>;

export function ProcessWithGoFitz(arg1:string):Promise<main.OCRResultSimple>;

export function ProcessWithTesseract(arg1:string):Promise<main.OCRResultSimple>;

export function ProgressOrderOnDelivery(arg1:string):Promise<void>;

export function ProgressOrderOnInvoice(arg1:string):Promise<void>;

export function PullChanges(arg1:time.Time):Promise<void>;

export function PurgeAllConversations():Promise<void>;

export function PushChanges():Promise<void>;

export function QuickCaptureDocument(arg1:string):Promise<Record<string, any>>;

export function QuickCaptureDocumentFromBase64(arg1:string,arg2:string):Promise<Record<string, any>>;

export function QuickMarkOrderDelivered(arg1:string):Promise<string>;

export function RaiseGRNDiscrepancy(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<void>;

export function ReassignCollaborativeTask(arg1:string,arg2:string):Promise<void>;

export function ReassignEmployeeLicenseAccess(arg1:string,arg2:string,arg3:boolean):Promise<main.EmployeeAccessLink>;

export function ReassignEmployeeManager(arg1:string,arg2:string):Promise<main.Employee>;

export function RebuildEntityGraph():Promise<graph.BuildStats>;

export function RecalculateAllInvoiceMargins():Promise<number>;

export function RecalculateInvoiceItemCosts():Promise<Record<string, any>>;

export function ReceiveAgainstPO(arg1:string,arg2:Array<crm.GRNItem>):Promise<crm.GoodsReceivedNote>;

export function ReceiveAgainstPOWithSerials(arg1:string,arg2:Array<main.GRNItemWithSerials>):Promise<crm.GoodsReceivedNote>;

export function ReceiveAndCompletePO(arg1:string,arg2:Array<crm.GRNItem>):Promise<main.GRNResponse>;

export function ReceiveAndCompletePOWithSerials(arg1:string,arg2:Array<main.GRNItemWithSerials>):Promise<main.GRNResponse>;

export function RecentComplianceValidations(arg1:number):Promise<Array<compliance.ValidationEntry>>;

export function RecomputeAllCustomerAggregates():Promise<Record<string, any>>;

export function RecomputeCustomerPrediction(arg1:string):Promise<butler.PredictionRecord>;

export function ReconcileOfferData(arg1:string):Promise<main.ReconciliationResult>;

export function RecordBusinessMemoryReviewDecision(arg1:main.BusinessMemoryReviewDecisionRequest):Promise<main.BusinessMemoryReviewResult>;

export function RecordPartialPayment(arg1:string,arg2:number,arg3:time.Time,arg4:string):Promise<void>;

export function RecordPartialShipment(arg1:string,arg2:Record<string, number>,arg3:string,arg4:string,arg5:string):Promise<void>;

export function RecordPayment(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<finance.Payment>;

export function RecordStockMovement(arg1:crm.StockMovement):Promise<crm.StockMovement>;

export function RecordSupplierPayment(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number):Promise<finance.SupplierPayment>;

export function RecordUserActivityBatch(arg1:Array<main.UserActivityEventInput>):Promise<void>;

export function RecordUserActivityHeartbeat(arg1:main.UserActivityHeartbeatInput):Promise<void>;

export function RefreshAuth():Promise<void>;

export function RefreshAuthWithSession(arg1:infra.UserSession):Promise<void>;

export function RefreshCollaborativeWorkspace():Promise<void>;

export function RefreshToolsStatus():Promise<integration.ToolsReport>;

export function RegisterDevice():Promise<device.RegistrationResult>;

export function RegisterReportHandlers():Promise<void>;

export function RegisterSerials(arg1:string,arg2:Array<string>):Promise<Array<crm.SerialNumber>>;

export function ReissueCheque(arg1:string,arg2:string):Promise<finance.OutstandingCheque>;

export function RejectCostingSheet(arg1:number,arg2:string):Promise<void>;

export function RejectExpenseEntry(arg1:string,arg2:string):Promise<finance.ExpenseEntry>;

export function RenewOffer(arg1:string):Promise<crm.Offer>;

export function ReopenReconciliation(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RequestDeleteApproval(arg1:string,arg2:string,arg3:string,arg4:string):Promise<deletion.Request>;

export function RequestEmployeeArchive(arg1:string,arg2:string):Promise<main.EmployeeArchiveRequest>;

export function RerunPhase7FollowUpBackfill():Promise<main.Phase7ActionResult>;

export function ResetUserPassword(arg1:string,arg2:string):Promise<void>;

export function ResolveOpportunityEditConflict(arg1:string,arg2:string,arg3:string):Promise<main.OpportunityConflictResolutionResult>;

export function ResolveSupplierIssue(arg1:string,arg2:string):Promise<void>;

export function RetrieveOriginalPDF(arg1:string):Promise<main.ArchivedFileResult>;

export function RetryCollaborativePendingOperation(arg1:string):Promise<void>;

export function RetryCollaborativePendingOperations(arg1:string,arg2:number):Promise<main.Phase7ActionResult>;

export function RetryFailedSyncs():Promise<number>;

export function ReturnDeposit(arg1:string,arg2:string):Promise<void>;

export function RevalueAllForeignAccounts(arg1:time.Time):Promise<fx.RevaluationBatchResult>;

export function ReverseAction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReverseCustomerReceipt(arg1:string,arg2:string):Promise<main.CustomerReceipt>;

export function ReverseJournalEntry(arg1:string,arg2:string):Promise<finance.JournalEntry>;

export function ReverseRevaluation(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReviewCashflowEvidenceProposal(arg1:string,arg2:string,arg3:string):Promise<main.CashflowEvidenceProposalReview>;

export function ReviewDataQualityIssue(arg1:main.DataQualityIssue,arg2:string,arg3:string):Promise<main.DataQualityReview>;

export function ReviewDeleteApprovalRequest(arg1:string,arg2:string,arg3:string):Promise<deletion.Request>;

export function ReviewEmployeeArchiveRequest(arg1:string,arg2:string,arg3:string):Promise<main.EmployeeArchiveRequest>;

export function RevokeLicense(arg1:string):Promise<void>;

export function RotateEncryptionKey():Promise<void>;

export function RouteEvent(arg1:engines.ERPEvent):Promise<engines.RoutingResult>;

export function RunAllDataFixes():Promise<Record<string, any>>;

export function RunBatchOCR(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function RunInitialScan():Promise<main.InitialScanResult>;

export function RunIntegrityCheck():Promise<string>;

export function RunScheduledBackupIfDue(arg1:string):Promise<Record<string, any>>;

export function SaveBackupPolicy(arg1:boolean,arg2:number):Promise<infra.BackupPolicy>;

export function SaveCostingAsOffer(arg1:main.CostingExportData):Promise<crm.Offer>;

export function SaveDocumentToEntity(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:string,arg8:string):Promise<Record<string, any>>;

export function SaveOCRDocument(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:string,arg8:string):Promise<main.OCRDocument>;

export function SaveParsedEmailAsRFQ(arg1:main.ParsedRFQEmail):Promise<number>;

export function SaveStatementHash(arg1:finance.BankStatement,arg2:Array<finance.BankStatementLine>):Promise<void>;

export function ScanExpiringEmployeeDocuments():Promise<main.EmployeeDocumentScanResult>;

export function ScanOfferFolders(arg1:string):Promise<main.ExcelBatchImportResult>;

export function ScanOneDrivePaths(arg1:Array<string>):Promise<main.OneDriveScanResult>;

export function SearchGraphEntities(arg1:string,arg2:number):Promise<Array<graph.GraphNode>>;

export function SearchOffers(arg1:string):Promise<Array<main.OfferSearchResult>>;

export function SearchOrders(arg1:string):Promise<Array<main.OrderSearchResult>>;

export function SearchProducts(arg1:string):Promise<Array<crm.ProductMaster>>;

export function SearchSerials(arg1:string,arg2:number):Promise<Array<crm.SerialNumber>>;

export function SeedAdditionalBankAccounts():Promise<void>;

export function SeedBankDemoData():Promise<void>;

export function SeedCompanyBankAccounts():Promise<void>;

export function SeedContractData():Promise<void>;

export function SeedCustomerDatabase():Promise<void>;

export function SeedDatabaseFromOpportunities(arg1:string):Promise<Record<string, any>>;

export function SeedDefaultChartOfAccounts():Promise<void>;

export function SeedDefaultExchangeRates():Promise<void>;

export function SeedDefaultRoles():Promise<void>;

export function SeedEmployeeKeys():Promise<void>;

export function SeedLicenseKeys():Promise<void>;

export function SeedProductDatabase():Promise<void>;

export function SendCustomerInvoice(arg1:string):Promise<void>;

export function SendPurchaseOrder(arg1:string):Promise<void>;

export function SendReportByEmail(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function SetAPIKeys(arg1:Record<string, string>):Promise<void>;

export function SetActiveCostingRevision(arg1:number):Promise<void>;

export function SetEmployeeEmploymentState(arg1:string,arg2:boolean,arg3:string):Promise<main.Employee>;

export function SetExchangeRate(arg1:string,arg2:number,arg3:time.Time,arg4:string):Promise<void>;

export function SetupAdminAccount(arg1:string,arg2:string,arg3:string,arg4:string):Promise<infra.User>;

export function ShelveCollaborativeProject(arg1:string,arg2:string):Promise<main.Project>;

export function ShutdownJobQueue():Promise<void>;

export function SimulateMargin(arg1:string,arg2:number):Promise<main.MarginSimulation>;

export function SimulateSurvivalGarden(arg1:number,arg2:number,arg3:Array<Record<string, any>>,arg4:number):Promise<Array<Record<string, any>>>;

export function StartArchaeologyScan(arg1:string,arg2:boolean,arg3:string):Promise<string>;

export function StartBackgroundDBSync():Promise<void>;

export function StartCollaborativeSyncLoop(arg1:time.Duration):Promise<void>;

export function StartFileWatcher():Promise<void>;

export function StartLogin():Promise<string>;

export function StartPeriodicSync(arg1:time.Duration):Promise<void>;

export function StartUserActivitySession(arg1:string):Promise<main.UserActivitySession>;

export function StopBackgroundDBSync():Promise<void>;

export function StopCollaborativeSyncLoop():Promise<void>;

export function StopFileWatcher():Promise<void>;

export function StopPeriodicSync():Promise<void>;

export function StoreCustomerGraph(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function SubmitExpenseEntry(arg1:string):Promise<finance.ExpenseEntry>;

export function SyncCashflowEvidenceProposalReviews(arg1:number):Promise<Array<main.CashflowEvidenceProposalReview>>;

export function SyncNowWithProgress():Promise<main.DBSyncResult>;

export function TestAIConnection(arg1:string,arg2:string):Promise<void>;

export function TestMistralConnection():Promise<boolean>;

export function TestSupabaseConnection(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<boolean>;

export function TimeNow():Promise<time.Time>;

export function TrackLatePaymentHistory(arg1:string):Promise<number>;

export function TriggerBackup():Promise<Record<string, any>>;

export function TriggerCollaborativeSyncNow():Promise<void>;

export function TriggerManualSync():Promise<Record<string, any>>;

export function TriggerSync(arg1:string):Promise<void>;

export function UnblockDevice(arg1:string):Promise<void>;

export function UnmatchLine(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateAccount(arg1:string,arg2:Record<string, any>):Promise<void>;

export function UpdateBankAccount(arg1:string,arg2:Record<string, any>):Promise<finance.CompanyBankAccount>;

export function UpdateBankStatement(arg1:string,arg2:Record<string, any>):Promise<void>;

export function UpdateBankStatementLine(arg1:string,arg2:Record<string, any>):Promise<void>;

export function UpdateBookBankReconciliation(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number,arg7:string):Promise<finance.BookBankReconciliation>;

export function UpdateBookBankReconciliationAdjustments(arg1:string,arg2:number,arg3:number):Promise<void>;

export function UpdateCollaborativeProject(arg1:string,arg2:Record<string, any>):Promise<main.Project>;

export function UpdateCollaborativeTask(arg1:main.TaskItem):Promise<main.TaskItem>;

export function UpdateCollaborativeTaskDueDate(arg1:string,arg2:string):Promise<void>;

export function UpdateCollaborativeTaskStatus(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateCostingSheet(arg1:number,arg2:main.CostingSheetData):Promise<main.CostingSheetData>;

export function UpdateCostingSheetWithVersionCheck(arg1:string,arg2:Record<string, any>,arg3:string):Promise<void>;

export function UpdateCustomer(arg1:crm.CustomerMaster):Promise<crm.CustomerMaster>;

export function UpdateCustomerContact(arg1:crm.CustomerContact):Promise<crm.CustomerContact>;

export function UpdateCustomerInvoice(arg1:finance.Invoice):Promise<finance.Invoice>;

export function UpdateDBSyncSettings(arg1:boolean,arg2:number):Promise<void>;

export function UpdateDeliveryNote(arg1:crm.DeliveryNote):Promise<crm.DeliveryNote>;

export function UpdateEmployeeDocument(arg1:string,arg2:main.EmployeeDocument,arg3:string):Promise<main.EmployeeDocumentDTO>;

export function UpdateEmployeeProfile(arg1:main.Employee):Promise<main.Employee>;

export function UpdateFolderPaths(arg1:Record<string, string>):Promise<void>;

export function UpdateFollowUp(arg1:number,arg2:crm.FollowUpTask):Promise<void>;

export function UpdateGRN(arg1:crm.GoodsReceivedNote):Promise<crm.GoodsReceivedNote>;

export function UpdateGRNQCStatus(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateInventoryItem(arg1:string,arg2:Record<string, any>):Promise<void>;

export function UpdateLicenseDisplayName(arg1:string,arg2:string):Promise<main.LicenseKey>;

export function UpdateOfferFull(arg1:string,arg2:main.OfferUpdateData):Promise<crm.Offer>;

export function UpdateOfferStatus(arg1:number,arg2:string):Promise<void>;

export function UpdateOpportunityCommercialFields(arg1:string,arg2:Record<string, any>):Promise<crm.Opportunity>;

export function UpdateOpportunityDetails(arg1:string,arg2:string,arg3:string):Promise<crm.Opportunity>;

export function UpdateOpportunityDetailsWithVersion(arg1:string,arg2:number,arg3:string,arg4:string):Promise<crm.Opportunity>;

export function UpdateOpportunityStage(arg1:string,arg2:string):Promise<void>;

export function UpdateOpportunityStageWithVersion(arg1:string,arg2:string,arg3:number):Promise<crm.Opportunity>;

export function UpdateOrder(arg1:string,arg2:crm.Order):Promise<crm.Order>;

export function UpdateOrderItemInvoiced(arg1:number,arg2:number):Promise<void>;

export function UpdateOrderItemShipped(arg1:number,arg2:number):Promise<void>;

export function UpdateOrderStage(arg1:string,arg2:string):Promise<void>;

export function UpdatePOStatus(arg1:string,arg2:string):Promise<void>;

export function UpdatePayment(arg1:string,arg2:finance.Payment):Promise<finance.Payment>;

export function UpdatePilotDeploymentChecklistItem(arg1:string,arg2:boolean,arg3:string):Promise<Array<main.PilotChecklistItem>>;

export function UpdatePostSaleNote(arg1:crm.PostSaleNote):Promise<crm.PostSaleNote>;

export function UpdatePurchaseOrder(arg1:crm.PurchaseOrder):Promise<crm.PurchaseOrder>;

export function UpdateQuickCapture(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function UpdateRFQ(arg1:number,arg2:main.RFQUpdateRequest):Promise<main.RFQData>;

export function UpdateRFQNotes(arg1:number,arg2:string):Promise<main.RFQData>;

export function UpdateRFQStage(arg1:number,arg2:string):Promise<void>;

export function UpdateRFQStatus(arg1:number,arg2:string):Promise<void>;

export function UpdateSerialWarranty(arg1:string,arg2:number):Promise<void>;

export function UpdateSettings(arg1:Record<string, any>):Promise<void>;

export function UpdateShipment(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateSupplier(arg1:crm.SupplierMaster):Promise<crm.SupplierMaster>;

export function UpdateSupplierContact(arg1:crm.SupplierContact):Promise<crm.SupplierContact>;

export function UpdateSupplierGoals(arg1:number,arg2:number,arg3:number):Promise<void>;

export function UpdateSupplierInvoice(arg1:finance.SupplierInvoice):Promise<finance.SupplierInvoice>;

export function UpdateSupplierPayment(arg1:string,arg2:finance.SupplierPayment):Promise<finance.SupplierPayment>;

export function UpdateUser(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean):Promise<void>;

export function UploadAsset(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UploadReportToStorage(arg1:string):Promise<string>;

export function UpsertEmployeeCompensationProfile(arg1:payroll.CompensationProfile):Promise<payroll.CompensationProfile>;

export function ValidateCSRFToken(arg1:string):Promise<boolean>;

export function ValidateCustomer(arg1:prediction.Customer):Promise<main.ValidationResult>;

export function ValidateFolder(arg1:string):Promise<boolean>;

export function ValidateJournalEntryBalance(arg1:string):Promise<boolean>;

export function ValidateLicense():Promise<main.LicenseValidationResult>;

export function ValidateOneDrivePath(arg1:string):Promise<Record<string, any>>;

export function ValidateStatementBalance(arg1:string):Promise<finance.StatementBalanceValidation>;

export function ValidateStatementContinuity(arg1:string,arg2:finance.BankStatement):Promise<void>;

export function VerifyInvoiceHash(arg1:string):Promise<main.InvoiceHashVerification>;

export function WatchInboxForTestFile(arg1:string):Promise<void>;

export function WriteMasterDataCleanupReport(arg1:string):Promise<string>;
