// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {finance} from '../models';
import {prediction} from '../models';
import {butler} from '../models';
import {integration} from '../models';

export function AcknowledgeAlert(arg1:number):Promise<void>;

export function AnalyzeDocumentWithButler(arg1:string,arg2:string,arg3:Record<string, any>):Promise<main.ButlerOCRInsight>;

export function BatchCreateInvoiceItems(arg1:Array<finance.DBInvoiceItem>):Promise<void>;

export function BatchPredict(arg1:Array<prediction.Customer>):Promise<main.BatchResult>;

export function BatchUpdateCustomerGrade(arg1:Array<string>,arg2:string):Promise<void>;

export function BatchUpdateOrderStatus(arg1:Array<string>,arg2:string):Promise<void>;

export function ChatWithButler(arg1:string):Promise<butler.ButlerResponse>;

export function ChatWithButlerPersistent(arg1:string,arg2:string):Promise<main.ChatResponse>;

export function ClearHistory():Promise<void>;

export function CreateConversation(arg1:string):Promise<butler.Conversation>;

export function DeleteConversation(arg1:string):Promise<void>;

export function DismissAlert(arg1:number):Promise<void>;

export function ExportCustomerTemplate():Promise<prediction.Customer>;

export function GenerateButlerReport(arg1:string,arg2:string):Promise<string>;

export function GenerateDailyBriefing(arg1:string):Promise<main.ChatResponse>;

export function GetAlertSummary():Promise<main.AlertSummary>;

export function GetButlerDailyBriefing(arg1:string):Promise<main.ChatResponse>;

export function GetCashflowEvidenceAgentBrief(arg1:number,arg2:number):Promise<string>;

export function GetConfig():Promise<Record<string, any>>;

export function GetConversationMessages(arg1:string):Promise<Array<butler.ChatMessage>>;

export function GetCustomerHistory(arg1:string):Promise<Array<butler.PredictionRecord>>;

export function GetDashboardEvents(arg1:number):Promise<Array<main.DashboardEvent>>;

export function GetDashboardStats():Promise<main.DashboardStats>;

export function GetHistory(arg1:number):Promise<Array<butler.PredictionRecord>>;

export function GetMonthlyRevenueByCustomer():Promise<Array<main.CustomerRevenueData>>;

export function GetStatistics():Promise<main.Statistics>;

export function GetSurvivalMetrics():Promise<main.SurvivalMetrics>;

export function GetToolInstallInstructions():Promise<string>;

export function GetToolsStatus():Promise<integration.ToolsReport>;

export function Greet(arg1:string):Promise<string>;

export function ListConversations():Promise<Array<butler.Conversation>>;

export function PredictPayment(arg1:prediction.Customer):Promise<prediction.PaymentPrediction>;

export function PurgeAllConversations():Promise<void>;

export function RefreshToolsStatus():Promise<integration.ToolsReport>;

export function TestMistralConnection():Promise<boolean>;

export function ValidateCustomer(arg1:prediction.Customer):Promise<main.ValidationResult>;
