// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyCreditNote(arg1) {
  return window['go']['main']['FinanceService']['ApplyCreditNote'](arg1);
}

export function ApproveExpenseEntry(arg1, arg2) {
  return window['go']['main']['FinanceService']['ApproveExpenseEntry'](arg1, arg2);
}

export function ApprovePayrollRun(arg1, arg2) {
  return window['go']['main']['FinanceService']['ApprovePayrollRun'](arg1, arg2);
}

export function ApproveStockAdjustment(arg1) {
  return window['go']['main']['FinanceService']['ApproveStockAdjustment'](arg1);
}

export function ApproveSupplierInvoice(arg1, arg2) {
  return window['go']['main']['FinanceService']['ApproveSupplierInvoice'](arg1, arg2);
}

export function ArchiveStatementPDF(arg1, arg2) {
  return window['go']['main']['FinanceService']['ArchiveStatementPDF'](arg1, arg2);
}

export function AutoMatchBankLines(arg1) {
  return window['go']['main']['FinanceService']['AutoMatchBankLines'](arg1);
}

export function BackfillInvoiceItemsFromOrders() {
  return window['go']['main']['FinanceService']['BackfillInvoiceItemsFromOrders']();
}

export function CalculateARAgingBuckets() {
  return window['go']['main']['FinanceService']['CalculateARAgingBuckets']();
}

export function CalculateFXRevaluation(arg1, arg2) {
  return window['go']['main']['FinanceService']['CalculateFXRevaluation'](arg1, arg2);
}

export function CalculateInvoiceMargin(arg1) {
  return window['go']['main']['FinanceService']['CalculateInvoiceMargin'](arg1);
}

export function CalculateSupplierLeadTime(arg1) {
  return window['go']['main']['FinanceService']['CalculateSupplierLeadTime'](arg1);
}

export function CancelCheque(arg1, arg2) {
  return window['go']['main']['FinanceService']['CancelCheque'](arg1, arg2);
}

export function CategorizeTransactions(arg1) {
  return window['go']['main']['FinanceService']['CategorizeTransactions'](arg1);
}

export function CheckDuplicateStatement(arg1, arg2) {
  return window['go']['main']['FinanceService']['CheckDuplicateStatement'](arg1, arg2);
}

export function ClosePeriod(arg1) {
  return window['go']['main']['FinanceService']['ClosePeriod'](arg1);
}

export function ComputeStatementHash(arg1, arg2) {
  return window['go']['main']['FinanceService']['ComputeStatementHash'](arg1, arg2);
}

export function CreateAccount(arg1) {
  return window['go']['main']['FinanceService']['CreateAccount'](arg1);
}

export function CreateBankAccount(arg1) {
  return window['go']['main']['FinanceService']['CreateBankAccount'](arg1);
}

export function CreateBankStatement(arg1) {
  return window['go']['main']['FinanceService']['CreateBankStatement'](arg1);
}

export function CreateBankStatementLine(arg1, arg2) {
  return window['go']['main']['FinanceService']['CreateBankStatementLine'](arg1, arg2);
}

export function CreateChequeRegister(arg1, arg2, arg3, arg4) {
  return window['go']['main']['FinanceService']['CreateChequeRegister'](arg1, arg2, arg3, arg4);
}

export function CreateCreditNote(arg1, arg2, arg3) {
  return window['go']['main']['FinanceService']['CreateCreditNote'](arg1, arg2, arg3);
}

export function CreateDraftJournalFromPosting(arg1, arg2) {
  return window['go']['main']['FinanceService']['CreateDraftJournalFromPosting'](arg1, arg2);
}

export function CreateExpenseCategory(arg1) {
  return window['go']['main']['FinanceService']['CreateExpenseCategory'](arg1);
}

export function CreateExpenseEntry(arg1) {
  return window['go']['main']['FinanceService']['CreateExpenseEntry'](arg1);
}

export function CreateExpenseFromBankCandidate(arg1, arg2) {
  return window['go']['main']['FinanceService']['CreateExpenseFromBankCandidate'](arg1, arg2);
}

export function CreateExpenseVendor(arg1) {
  return window['go']['main']['FinanceService']['CreateExpenseVendor'](arg1);
}

export function CreateFXRate(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['FinanceService']['CreateFXRate'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateInventoryItem(arg1) {
  return window['go']['main']['FinanceService']['CreateInventoryItem'](arg1);
}

export function CreateInvoiceFromDN(arg1) {
  return window['go']['main']['FinanceService']['CreateInvoiceFromDN'](arg1);
}

export function CreateInvoiceFromOrder(arg1) {
  return window['go']['main']['FinanceService']['CreateInvoiceFromOrder'](arg1);
}

export function CreateInvoiceFromOrderWithDN(arg1, arg2) {
  return window['go']['main']['FinanceService']['CreateInvoiceFromOrderWithDN'](arg1, arg2);
}

export function CreateInvoiceWithCreditOverride(arg1, arg2, arg3, arg4) {
  return window['go']['main']['FinanceService']['CreateInvoiceWithCreditOverride'](arg1, arg2, arg3, arg4);
}

export function CreateInvoiceWithOptions(arg1, arg2, arg3) {
  return window['go']['main']['FinanceService']['CreateInvoiceWithOptions'](arg1, arg2, arg3);
}

export function CreateJournalEntry(arg1) {
  return window['go']['main']['FinanceService']['CreateJournalEntry'](arg1);
}

export function CreatePayrollPeriod(arg1) {
  return window['go']['main']['FinanceService']['CreatePayrollPeriod'](arg1);
}

export function CreatePostSaleNote(arg1) {
  return window['go']['main']['FinanceService']['CreatePostSaleNote'](arg1);
}

export function CreateProformaInvoice(arg1) {
  return window['go']['main']['FinanceService']['CreateProformaInvoice'](arg1);
}

export function CreateRecurringExpense(arg1) {
  return window['go']['main']['FinanceService']['CreateRecurringExpense'](arg1);
}

export function CreateSplitAllocation(arg1, arg2, arg3) {
  return window['go']['main']['FinanceService']['CreateSplitAllocation'](arg1, arg2, arg3);
}

export function CreateStockAdjustment(arg1) {
  return window['go']['main']['FinanceService']['CreateStockAdjustment'](arg1);
}

export function CreateSupplierInvoice(arg1) {
  return window['go']['main']['FinanceService']['CreateSupplierInvoice'](arg1);
}

export function CreateSupplierInvoiceFromOCR(arg1, arg2, arg3) {
  return window['go']['main']['FinanceService']['CreateSupplierInvoiceFromOCR'](arg1, arg2, arg3);
}

export function CreateWarehouse(arg1) {
  return window['go']['main']['FinanceService']['CreateWarehouse'](arg1);
}

export function DeleteBankAccount(arg1) {
  return window['go']['main']['FinanceService']['DeleteBankAccount'](arg1);
}

export function DeleteBankStatement(arg1) {
  return window['go']['main']['FinanceService']['DeleteBankStatement'](arg1);
}

export function DeleteBankStatementLine(arg1) {
  return window['go']['main']['FinanceService']['DeleteBankStatementLine'](arg1);
}

export function DeleteCustomerInvoice(arg1) {
  return window['go']['main']['FinanceService']['DeleteCustomerInvoice'](arg1);
}

export function DeleteExpenseCategory(arg1) {
  return window['go']['main']['FinanceService']['DeleteExpenseCategory'](arg1);
}

export function DeleteExpenseEntry(arg1) {
  return window['go']['main']['FinanceService']['DeleteExpenseEntry'](arg1);
}

export function DeleteExpenseVendor(arg1) {
  return window['go']['main']['FinanceService']['DeleteExpenseVendor'](arg1);
}

export function DeleteFXRate(arg1) {
  return window['go']['main']['FinanceService']['DeleteFXRate'](arg1);
}

export function DeletePayment(arg1) {
  return window['go']['main']['FinanceService']['DeletePayment'](arg1);
}

export function DeletePostSaleNote(arg1) {
  return window['go']['main']['FinanceService']['DeletePostSaleNote'](arg1);
}

export function DeleteRecurringExpense(arg1) {
  return window['go']['main']['FinanceService']['DeleteRecurringExpense'](arg1);
}

export function DeleteSupplierInvoice(arg1) {
  return window['go']['main']['FinanceService']['DeleteSupplierInvoice'](arg1);
}

export function DeleteSupplierPayment(arg1) {
  return window['go']['main']['FinanceService']['DeleteSupplierPayment'](arg1);
}

export function DisputeSupplierInvoice(arg1, arg2) {
  return window['go']['main']['FinanceService']['DisputeSupplierInvoice'](arg1, arg2);
}

export function EnsureExpenseFoundation() {
  return window['go']['main']['FinanceService']['EnsureExpenseFoundation']();
}

export function EnsurePayrollFoundation() {
  return window['go']['main']['FinanceService']['EnsurePayrollFoundation']();
}

export function ExhaustChequeRegister(arg1) {
  return window['go']['main']['FinanceService']['ExhaustChequeRegister'](arg1);
}

export function ExportBalanceSheetCSV(arg1) {
  return window['go']['main']['FinanceService']['ExportBalanceSheetCSV'](arg1);
}

export function ExportCashflowEvidencePack(arg1) {
  return window['go']['main']['FinanceService']['ExportCashflowEvidencePack'](arg1);
}

export function ExportGeneralLedgerCSV(arg1) {
  return window['go']['main']['FinanceService']['ExportGeneralLedgerCSV'](arg1);
}

export function ExportJournalCSV(arg1) {
  return window['go']['main']['FinanceService']['ExportJournalCSV'](arg1);
}

export function ExportVATReturnData(arg1, arg2) {
  return window['go']['main']['FinanceService']['ExportVATReturnData'](arg1, arg2);
}

export function FileVATReturn(arg1) {
  return window['go']['main']['FinanceService']['FileVATReturn'](arg1);
}

export function FinalizeReconciliation(arg1, arg2) {
  return window['go']['main']['FinanceService']['FinalizeReconciliation'](arg1, arg2);
}

export function ForceReimportStatement(arg1, arg2, arg3) {
  return window['go']['main']['FinanceService']['ForceReimportStatement'](arg1, arg2, arg3);
}

export function GenerateAuditReport(arg1, arg2, arg3) {
  return window['go']['main']['FinanceService']['GenerateAuditReport'](arg1, arg2, arg3);
}

export function GenerateBalanceSheet(arg1) {
  return window['go']['main']['FinanceService']['GenerateBalanceSheet'](arg1);
}

export function GenerateCreditNoteNumber() {
  return window['go']['main']['FinanceService']['GenerateCreditNoteNumber']();
}

export function GenerateCreditNotePDF(arg1) {
  return window['go']['main']['FinanceService']['GenerateCreditNotePDF'](arg1);
}

export function GenerateEInvoiceXML(arg1) {
  return window['go']['main']['FinanceService']['GenerateEInvoiceXML'](arg1);
}

export function GenerateInvoiceNumber() {
  return window['go']['main']['FinanceService']['GenerateInvoiceNumber']();
}

export function GeneratePayrollRun(arg1) {
  return window['go']['main']['FinanceService']['GeneratePayrollRun'](arg1);
}

export function GeneratePayslipPDF(arg1, arg2) {
  return window['go']['main']['FinanceService']['GeneratePayslipPDF'](arg1, arg2);
}

export function GenerateProfitAndLoss(arg1) {
  return window['go']['main']['FinanceService']['GenerateProfitAndLoss'](arg1);
}

export function GenerateRecurringExpenses(arg1) {
  return window['go']['main']['FinanceService']['GenerateRecurringExpenses'](arg1);
}

export function GenerateVATReturn(arg1, arg2) {
  return window['go']['main']['FinanceService']['GenerateVATReturn'](arg1, arg2);
}

export function GetAPAgingReport() {
  return window['go']['main']['FinanceService']['GetAPAgingReport']();
}

export function GetARAgingByCustomer(arg1) {
  return window['go']['main']['FinanceService']['GetARAgingByCustomer'](arg1);
}

export function GetARAgingReport() {
  return window['go']['main']['FinanceService']['GetARAgingReport']();
}

export function GetActiveBankAccounts() {
  return window['go']['main']['FinanceService']['GetActiveBankAccounts']();
}

export function GetActiveChequeRegister(arg1) {
  return window['go']['main']['FinanceService']['GetActiveChequeRegister'](arg1);
}

export function GetAllBankAccounts() {
  return window['go']['main']['FinanceService']['GetAllBankAccounts']();
}

export function GetAllFXRates(arg1, arg2) {
  return window['go']['main']['FinanceService']['GetAllFXRates'](arg1, arg2);
}

export function GetAllPayments(arg1, arg2) {
  return window['go']['main']['FinanceService']['GetAllPayments'](arg1, arg2);
}

export function GetAllSupplierPayments() {
  return window['go']['main']['FinanceService']['GetAllSupplierPayments']();
}

export function GetAuditTrail(arg1) {
  return window['go']['main']['FinanceService']['GetAuditTrail'](arg1);
}

export function GetAuditTrailByDateRange(arg1, arg2, arg3) {
  return window['go']['main']['FinanceService']['GetAuditTrailByDateRange'](arg1, arg2, arg3);
}

export function GetAvailableDeliveryNotesForOrder(arg1) {
  return window['go']['main']['FinanceService']['GetAvailableDeliveryNotesForOrder'](arg1);
}

export function GetAvailableFinancialYears() {
  return window['go']['main']['FinanceService']['GetAvailableFinancialYears']();
}

export function GetBalanceContinuityReport(arg1) {
  return window['go']['main']['FinanceService']['GetBalanceContinuityReport'](arg1);
}

export function GetBalanceSheet(arg1) {
  return window['go']['main']['FinanceService']['GetBalanceSheet'](arg1);
}

export function GetBankAccountByID(arg1) {
  return window['go']['main']['FinanceService']['GetBankAccountByID'](arg1);
}

export function GetBankStatementByID(arg1) {
  return window['go']['main']['FinanceService']['GetBankStatementByID'](arg1);
}

export function GetBankStatementLines(arg1) {
  return window['go']['main']['FinanceService']['GetBankStatementLines'](arg1);
}

export function GetBankStatements(arg1) {
  return window['go']['main']['FinanceService']['GetBankStatements'](arg1);
}

export function GetCashFlowProjection(arg1) {
  return window['go']['main']['FinanceService']['GetCashFlowProjection'](arg1);
}

export function GetCashPosition() {
  return window['go']['main']['FinanceService']['GetCashPosition']();
}

export function GetCashPositionByAccount(arg1) {
  return window['go']['main']['FinanceService']['GetCashPositionByAccount'](arg1);
}

export function GetCashflowEvidenceCommandCenter(arg1) {
  return window['go']['main']['FinanceService']['GetCashflowEvidenceCommandCenter'](arg1);
}

export function GetChartOfAccounts(arg1) {
  return window['go']['main']['FinanceService']['GetChartOfAccounts'](arg1);
}

export function GetChequeByNumber(arg1) {
  return window['go']['main']['FinanceService']['GetChequeByNumber'](arg1);
}

export function GetChequeRegisterReport(arg1, arg2, arg3) {
  return window['go']['main']['FinanceService']['GetChequeRegisterReport'](arg1, arg2, arg3);
}

export function GetChequeRegisters(arg1) {
  return window['go']['main']['FinanceService']['GetChequeRegisters'](arg1);
}

export function GetChequesByStatus(arg1, arg2) {
  return window['go']['main']['FinanceService']['GetChequesByStatus'](arg1, arg2);
}

export function GetCreditNote(arg1) {
  return window['go']['main']['FinanceService']['GetCreditNote'](arg1);
}

export function GetCustomerInvoiceByID(arg1) {
  return window['go']['main']['FinanceService']['GetCustomerInvoiceByID'](arg1);
}

export function GetDynamicFinancialDashboard(arg1) {
  return window['go']['main']['FinanceService']['GetDynamicFinancialDashboard'](arg1);
}

export function GetFXExposureReport() {
  return window['go']['main']['FinanceService']['GetFXExposureReport']();
}

export function GetFXGainLossSummary(arg1) {
  return window['go']['main']['FinanceService']['GetFXGainLossSummary'](arg1);
}

export function GetFXRate(arg1, arg2, arg3) {
  return window['go']['main']['FinanceService']['GetFXRate'](arg1, arg2, arg3);
}

export function GetFXRateHistory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['FinanceService']['GetFXRateHistory'](arg1, arg2, arg3, arg4);
}

export function GetFXRevaluations(arg1) {
  return window['go']['main']['FinanceService']['GetFXRevaluations'](arg1);
}

export function GetFileHash(arg1) {
  return window['go']['main']['FinanceService']['GetFileHash'](arg1);
}

export function GetFinancialDashboardByDivision(arg1, arg2) {
  return window['go']['main']['FinanceService']['GetFinancialDashboardByDivision'](arg1, arg2);
}

export function GetFinancialReportYears() {
  return window['go']['main']['FinanceService']['GetFinancialReportYears']();
}

export function GetFinancialYearData(arg1) {
  return window['go']['main']['FinanceService']['GetFinancialYearData'](arg1);
}

export function GetInventoryItem(arg1) {
  return window['go']['main']['FinanceService']['GetInventoryItem'](arg1);
}

export function GetInventoryItems(arg1, arg2, arg3) {
  return window['go']['main']['FinanceService']['GetInventoryItems'](arg1, arg2, arg3);
}

export function GetInventoryValuation(arg1) {
  return window['go']['main']['FinanceService']['GetInventoryValuation'](arg1);
}

export function GetInvoiceAuditTrail(arg1) {
  return window['go']['main']['FinanceService']['GetInvoiceAuditTrail'](arg1);
}

export function GetInvoiceListVM(arg1, arg2) {
  return window['go']['main']['FinanceService']['GetInvoiceListVM'](arg1, arg2);
}

export function GetInvoiceRevenueSummary() {
  return window['go']['main']['FinanceService']['GetInvoiceRevenueSummary']();
}

export function GetInvoicesByCustomer(arg1) {
  return window['go']['main']['FinanceService']['GetInvoicesByCustomer'](arg1);
}

export function GetInvoicesByDateRange(arg1, arg2) {
  return window['go']['main']['FinanceService']['GetInvoicesByDateRange'](arg1, arg2);
}

export function GetInvoicesByOrder(arg1) {
  return window['go']['main']['FinanceService']['GetInvoicesByOrder'](arg1);
}

export function GetInvoicesByRFQ(arg1) {
  return window['go']['main']['FinanceService']['GetInvoicesByRFQ'](arg1);
}

export function GetInvoicesByStatus(arg1) {
  return window['go']['main']['FinanceService']['GetInvoicesByStatus'](arg1);
}

export function GetJournalEntries(arg1, arg2, arg3, arg4) {
  return window['go']['main']['FinanceService']['GetJournalEntries'](arg1, arg2, arg3, arg4);
}

export function GetLatePaymentInvoices() {
  return window['go']['main']['FinanceService']['GetLatePaymentInvoices']();
}

export function GetLateSuppliers() {
  return window['go']['main']['FinanceService']['GetLateSuppliers']();
}

export function GetLatestFXRate(arg1, arg2) {
  return window['go']['main']['FinanceService']['GetLatestFXRate'](arg1, arg2);
}

export function GetLowStockItems() {
  return window['go']['main']['FinanceService']['GetLowStockItems']();
}

export function GetMarginAnalysisByCustomer() {
  return window['go']['main']['FinanceService']['GetMarginAnalysisByCustomer']();
}

export function GetMarginAnalysisByProduct() {
  return window['go']['main']['FinanceService']['GetMarginAnalysisByProduct']();
}

export function GetNextChequeNumber(arg1) {
  return window['go']['main']['FinanceService']['GetNextChequeNumber'](arg1);
}

export function GetOutstandingCheques(arg1) {
  return window['go']['main']['FinanceService']['GetOutstandingCheques'](arg1);
}

export function GetOverdueInvoices() {
  return window['go']['main']['FinanceService']['GetOverdueInvoices']();
}

export function GetOverdueSupplierInvoices() {
  return window['go']['main']['FinanceService']['GetOverdueSupplierInvoices']();
}

export function GetPayment(arg1) {
  return window['go']['main']['FinanceService']['GetPayment'](arg1);
}

export function GetPaymentAgingReport() {
  return window['go']['main']['FinanceService']['GetPaymentAgingReport']();
}

export function GetPaymentsByInvoice(arg1) {
  return window['go']['main']['FinanceService']['GetPaymentsByInvoice'](arg1);
}

export function GetPayrollRun(arg1) {
  return window['go']['main']['FinanceService']['GetPayrollRun'](arg1);
}

export function GetPostSaleNotes(arg1) {
  return window['go']['main']['FinanceService']['GetPostSaleNotes'](arg1);
}

export function GetPostingCoverageReport() {
  return window['go']['main']['FinanceService']['GetPostingCoverageReport']();
}

export function GetProfitLoss(arg1, arg2) {
  return window['go']['main']['FinanceService']['GetProfitLoss'](arg1, arg2);
}

export function GetReconciliationStats(arg1) {
  return window['go']['main']['FinanceService']['GetReconciliationStats'](arg1);
}

export function GetReconciliationSummary(arg1) {
  return window['go']['main']['FinanceService']['GetReconciliationSummary'](arg1);
}

export function GetSalesPipeline() {
  return window['go']['main']['FinanceService']['GetSalesPipeline']();
}

export function GetStaleCheques(arg1) {
  return window['go']['main']['FinanceService']['GetStaleCheques'](arg1);
}

export function GetStockMovements(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['FinanceService']['GetStockMovements'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSupplierInvoiceByID(arg1) {
  return window['go']['main']['FinanceService']['GetSupplierInvoiceByID'](arg1);
}

export function GetSupplierInvoices() {
  return window['go']['main']['FinanceService']['GetSupplierInvoices']();
}

export function GetSupplierInvoicesByPO(arg1) {
  return window['go']['main']['FinanceService']['GetSupplierInvoicesByPO'](arg1);
}

export function GetSupplierInvoicesBySupplier(arg1) {
  return window['go']['main']['FinanceService']['GetSupplierInvoicesBySupplier'](arg1);
}

export function GetSupplierLeadTimeReport() {
  return window['go']['main']['FinanceService']['GetSupplierLeadTimeReport']();
}

export function GetSupplierPayment(arg1) {
  return window['go']['main']['FinanceService']['GetSupplierPayment'](arg1);
}

export function GetSupplierPaymentsByInvoice(arg1) {
  return window['go']['main']['FinanceService']['GetSupplierPaymentsByInvoice'](arg1);
}

export function GetSupplierPaymentsSummary() {
  return window['go']['main']['FinanceService']['GetSupplierPaymentsSummary']();
}

export function GetTrialBalanceGate(arg1, arg2) {
  return window['go']['main']['FinanceService']['GetTrialBalanceGate'](arg1, arg2);
}

export function GetUnmatchedLines(arg1) {
  return window['go']['main']['FinanceService']['GetUnmatchedLines'](arg1);
}

export function GetUnpaidInvoices() {
  return window['go']['main']['FinanceService']['GetUnpaidInvoices']();
}

export function GetUnpaidSupplierInvoices() {
  return window['go']['main']['FinanceService']['GetUnpaidSupplierInvoices']();
}

export function GetUnpostedRevaluations() {
  return window['go']['main']['FinanceService']['GetUnpostedRevaluations']();
}

export function GetVATReconciliation(arg1, arg2) {
  return window['go']['main']['FinanceService']['GetVATReconciliation'](arg1, arg2);
}

export function GetVATReturns(arg1, arg2) {
  return window['go']['main']['FinanceService']['GetVATReturns'](arg1, arg2);
}

export function GetWarehouses() {
  return window['go']['main']['FinanceService']['GetWarehouses']();
}

export function ImportARDefaulters() {
  return window['go']['main']['FinanceService']['ImportARDefaulters']();
}

export function ImportAllTallyData() {
  return window['go']['main']['FinanceService']['ImportAllTallyData']();
}

export function ImportBankStatementCSV(arg1, arg2) {
  return window['go']['main']['FinanceService']['ImportBankStatementCSV'](arg1, arg2);
}

export function ImportBankStatementPDF(arg1, arg2) {
  return window['go']['main']['FinanceService']['ImportBankStatementPDF'](arg1, arg2);
}

export function ImportSupplierPaymentsFromFile() {
  return window['go']['main']['FinanceService']['ImportSupplierPaymentsFromFile']();
}

export function ImportTallyInvoices(arg1) {
  return window['go']['main']['FinanceService']['ImportTallyInvoices'](arg1);
}

export function ImportTallyPurchases(arg1) {
  return window['go']['main']['FinanceService']['ImportTallyPurchases'](arg1);
}

export function IsPeriodClosed(arg1) {
  return window['go']['main']['FinanceService']['IsPeriodClosed'](arg1);
}

export function IssueCheque(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['FinanceService']['IssueCheque'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function IssueCreditNote(arg1) {
  return window['go']['main']['FinanceService']['IssueCreditNote'](arg1);
}

export function LinkInvoiceToOrder(arg1, arg2) {
  return window['go']['main']['FinanceService']['LinkInvoiceToOrder'](arg1, arg2);
}

export function LinkInvoiceToRFQ(arg1, arg2) {
  return window['go']['main']['FinanceService']['LinkInvoiceToRFQ'](arg1, arg2);
}

export function ListBankExpenseCandidates(arg1) {
  return window['go']['main']['FinanceService']['ListBankExpenseCandidates'](arg1);
}

export function ListCashflowEvidenceProposalReviews(arg1, arg2) {
  return window['go']['main']['FinanceService']['ListCashflowEvidenceProposalReviews'](arg1, arg2);
}

export function ListCreditNotes(arg1, arg2) {
  return window['go']['main']['FinanceService']['ListCreditNotes'](arg1, arg2);
}

export function ListCustomerInvoices(arg1, arg2) {
  return window['go']['main']['FinanceService']['ListCustomerInvoices'](arg1, arg2);
}

export function ListEmployeeCompensationProfiles(arg1) {
  return window['go']['main']['FinanceService']['ListEmployeeCompensationProfiles'](arg1);
}

export function ListExpenseCategories(arg1) {
  return window['go']['main']['FinanceService']['ListExpenseCategories'](arg1);
}

export function ListExpenseDashboardSummary() {
  return window['go']['main']['FinanceService']['ListExpenseDashboardSummary']();
}

export function ListExpenseEntries(arg1, arg2) {
  return window['go']['main']['FinanceService']['ListExpenseEntries'](arg1, arg2);
}

export function ListExpenseVendors(arg1) {
  return window['go']['main']['FinanceService']['ListExpenseVendors'](arg1);
}

export function ListPayrollDashboardSummary() {
  return window['go']['main']['FinanceService']['ListPayrollDashboardSummary']();
}

export function ListPayrollPayouts(arg1) {
  return window['go']['main']['FinanceService']['ListPayrollPayouts'](arg1);
}

export function ListPayrollPeriods(arg1) {
  return window['go']['main']['FinanceService']['ListPayrollPeriods'](arg1);
}

export function ListPayrollRuns(arg1) {
  return window['go']['main']['FinanceService']['ListPayrollRuns'](arg1);
}

export function ListRecurringExpenses(arg1) {
  return window['go']['main']['FinanceService']['ListRecurringExpenses'](arg1);
}

export function ListUnreconciledPayrollPayouts() {
  return window['go']['main']['FinanceService']['ListUnreconciledPayrollPayouts']();
}

export function LogReconciliationAction(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['FinanceService']['LogReconciliationAction'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function ManualMatchLine(arg1, arg2, arg3, arg4) {
  return window['go']['main']['FinanceService']['ManualMatchLine'](arg1, arg2, arg3, arg4);
}

export function MarkChequeBounced(arg1, arg2) {
  return window['go']['main']['FinanceService']['MarkChequeBounced'](arg1, arg2);
}

export function MarkChequeCleared(arg1, arg2, arg3) {
  return window['go']['main']['FinanceService']['MarkChequeCleared'](arg1, arg2, arg3);
}

export function MarkChequePresented(arg1) {
  return window['go']['main']['FinanceService']['MarkChequePresented'](arg1);
}

export function MarkChequeStale(arg1) {
  return window['go']['main']['FinanceService']['MarkChequeStale'](arg1);
}

export function MarkCustomerInvoiceOverdue(arg1) {
  return window['go']['main']['FinanceService']['MarkCustomerInvoiceOverdue'](arg1);
}

export function MarkCustomerInvoicePaid(arg1, arg2, arg3) {
  return window['go']['main']['FinanceService']['MarkCustomerInvoicePaid'](arg1, arg2, arg3);
}

export function MarkExpenseEntryPaid(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['FinanceService']['MarkExpenseEntryPaid'](arg1, arg2, arg3, arg4, arg5);
}

export function MarkPayrollRunPaid(arg1, arg2, arg3, arg4) {
  return window['go']['main']['FinanceService']['MarkPayrollRunPaid'](arg1, arg2, arg3, arg4);
}

export function MarkSupplierInvoicePaid(arg1, arg2, arg3) {
  return window['go']['main']['FinanceService']['MarkSupplierInvoicePaid'](arg1, arg2, arg3);
}

export function MigrateBankAccountEncryption() {
  return window['go']['main']['FinanceService']['MigrateBankAccountEncryption']();
}

export function PerformThreeWayMatch(arg1) {
  return window['go']['main']['FinanceService']['PerformThreeWayMatch'](arg1);
}

export function PostExpenseEntry(arg1) {
  return window['go']['main']['FinanceService']['PostExpenseEntry'](arg1);
}

export function PostFXRevaluation(arg1, arg2) {
  return window['go']['main']['FinanceService']['PostFXRevaluation'](arg1, arg2);
}

export function PostJournalEntry(arg1) {
  return window['go']['main']['FinanceService']['PostJournalEntry'](arg1);
}

export function PostPayrollRun(arg1) {
  return window['go']['main']['FinanceService']['PostPayrollRun'](arg1);
}

export function PreviewCustomerInvoicePosting(arg1) {
  return window['go']['main']['FinanceService']['PreviewCustomerInvoicePosting'](arg1);
}

export function PreviewCustomerPaymentPosting(arg1) {
  return window['go']['main']['FinanceService']['PreviewCustomerPaymentPosting'](arg1);
}

export function PreviewSupplierInvoicePosting(arg1) {
  return window['go']['main']['FinanceService']['PreviewSupplierInvoicePosting'](arg1);
}

export function PreviewSupplierPaymentPosting(arg1) {
  return window['go']['main']['FinanceService']['PreviewSupplierPaymentPosting'](arg1);
}

export function ProgressOrderOnDelivery(arg1) {
  return window['go']['main']['FinanceService']['ProgressOrderOnDelivery'](arg1);
}

export function ProgressOrderOnInvoice(arg1) {
  return window['go']['main']['FinanceService']['ProgressOrderOnInvoice'](arg1);
}

export function RecalculateAllInvoiceMargins() {
  return window['go']['main']['FinanceService']['RecalculateAllInvoiceMargins']();
}

export function RecordPartialPayment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['FinanceService']['RecordPartialPayment'](arg1, arg2, arg3, arg4);
}

export function RecordPayment(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['FinanceService']['RecordPayment'](arg1, arg2, arg3, arg4, arg5);
}

export function RecordStockMovement(arg1) {
  return window['go']['main']['FinanceService']['RecordStockMovement'](arg1);
}

export function RecordSupplierPayment(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['FinanceService']['RecordSupplierPayment'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ReissueCheque(arg1, arg2) {
  return window['go']['main']['FinanceService']['ReissueCheque'](arg1, arg2);
}

export function RejectExpenseEntry(arg1, arg2) {
  return window['go']['main']['FinanceService']['RejectExpenseEntry'](arg1, arg2);
}

export function ReopenReconciliation(arg1, arg2, arg3) {
  return window['go']['main']['FinanceService']['ReopenReconciliation'](arg1, arg2, arg3);
}

export function RetrieveOriginalPDF(arg1) {
  return window['go']['main']['FinanceService']['RetrieveOriginalPDF'](arg1);
}

export function RevalueAllForeignAccounts(arg1) {
  return window['go']['main']['FinanceService']['RevalueAllForeignAccounts'](arg1);
}

export function ReverseAction(arg1, arg2, arg3) {
  return window['go']['main']['FinanceService']['ReverseAction'](arg1, arg2, arg3);
}

export function ReverseJournalEntry(arg1, arg2) {
  return window['go']['main']['FinanceService']['ReverseJournalEntry'](arg1, arg2);
}

export function ReverseRevaluation(arg1, arg2, arg3) {
  return window['go']['main']['FinanceService']['ReverseRevaluation'](arg1, arg2, arg3);
}

export function ReviewCashflowEvidenceProposal(arg1, arg2, arg3) {
  return window['go']['main']['FinanceService']['ReviewCashflowEvidenceProposal'](arg1, arg2, arg3);
}

export function SaveStatementHash(arg1, arg2) {
  return window['go']['main']['FinanceService']['SaveStatementHash'](arg1, arg2);
}

export function SeedCompanyBankAccounts() {
  return window['go']['main']['FinanceService']['SeedCompanyBankAccounts']();
}

export function SeedDefaultChartOfAccounts() {
  return window['go']['main']['FinanceService']['SeedDefaultChartOfAccounts']();
}

export function SendCustomerInvoice(arg1) {
  return window['go']['main']['FinanceService']['SendCustomerInvoice'](arg1);
}

export function SubmitExpenseEntry(arg1) {
  return window['go']['main']['FinanceService']['SubmitExpenseEntry'](arg1);
}

export function SyncCashflowEvidenceProposalReviews(arg1) {
  return window['go']['main']['FinanceService']['SyncCashflowEvidenceProposalReviews'](arg1);
}

export function TrackLatePaymentHistory(arg1) {
  return window['go']['main']['FinanceService']['TrackLatePaymentHistory'](arg1);
}

export function UnmatchLine(arg1, arg2, arg3) {
  return window['go']['main']['FinanceService']['UnmatchLine'](arg1, arg2, arg3);
}

export function UpdateAccount(arg1, arg2) {
  return window['go']['main']['FinanceService']['UpdateAccount'](arg1, arg2);
}

export function UpdateBankAccount(arg1, arg2) {
  return window['go']['main']['FinanceService']['UpdateBankAccount'](arg1, arg2);
}

export function UpdateBankStatement(arg1, arg2) {
  return window['go']['main']['FinanceService']['UpdateBankStatement'](arg1, arg2);
}

export function UpdateBankStatementLine(arg1, arg2) {
  return window['go']['main']['FinanceService']['UpdateBankStatementLine'](arg1, arg2);
}

export function UpdateCustomerInvoice(arg1) {
  return window['go']['main']['FinanceService']['UpdateCustomerInvoice'](arg1);
}

export function UpdateInventoryItem(arg1, arg2) {
  return window['go']['main']['FinanceService']['UpdateInventoryItem'](arg1, arg2);
}

export function UpdatePayment(arg1, arg2) {
  return window['go']['main']['FinanceService']['UpdatePayment'](arg1, arg2);
}

export function UpdatePostSaleNote(arg1) {
  return window['go']['main']['FinanceService']['UpdatePostSaleNote'](arg1);
}

export function UpdateSupplierInvoice(arg1) {
  return window['go']['main']['FinanceService']['UpdateSupplierInvoice'](arg1);
}

export function UpdateSupplierPayment(arg1, arg2) {
  return window['go']['main']['FinanceService']['UpdateSupplierPayment'](arg1, arg2);
}

export function UpsertEmployeeCompensationProfile(arg1) {
  return window['go']['main']['FinanceService']['UpsertEmployeeCompensationProfile'](arg1);
}

export function ValidateJournalEntryBalance(arg1) {
  return window['go']['main']['FinanceService']['ValidateJournalEntryBalance'](arg1);
}

export function ValidateStatementBalance(arg1) {
  return window['go']['main']['FinanceService']['ValidateStatementBalance'](arg1);
}

export function ValidateStatementContinuity(arg1, arg2) {
  return window['go']['main']['FinanceService']['ValidateStatementContinuity'](arg1, arg2);
}
