// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {time} from '../models';

export function AddCollaborativeProjectMember(arg1:string,arg2:string,arg3:string,arg4:number):Promise<main.ProjectMember>;

export function AddCollaborativeTaskComment(arg1:string,arg2:string):Promise<main.TaskComment>;

export function ArchiveCollaborativeProject(arg1:string,arg2:string):Promise<main.Project>;

export function CreateCollaborativeProject(arg1:main.Project):Promise<main.Project>;

export function CreateCollaborativeTask(arg1:main.TaskItem):Promise<main.TaskItem>;

export function CreateEmployeeAccessLink(arg1:main.EmployeeAccessLink):Promise<main.EmployeeAccessLink>;

export function CreateEmployeeProfile(arg1:main.Employee):Promise<main.Employee>;

export function DeleteCollaborativeProject(arg1:string,arg2:string):Promise<void>;

export function DeleteCollaborativeTask(arg1:string):Promise<void>;

export function EnsureCollaborativeFoundation():Promise<void>;

export function FirstRunSyncWithProgress():Promise<main.DBSyncResult>;

export function GetCollaborativeTask(arg1:string):Promise<main.TaskItem>;

export function GetCurrentEmployeeContext():Promise<main.CurrentEmployeeContext>;

export function GetDBSyncSettings():Promise<main.DBSyncSettings>;

export function GetDBSyncStatus():Promise<Record<string, any>>;

export function GetFirstRunSyncStatus():Promise<Record<string, any>>;

export function GetProjectTaskCounts():Promise<Record<string, number>>;

export function GetSyncHealth():Promise<main.SyncHealth>;

export function GetUnreadNotificationsCount():Promise<number>;

export function InitDBManager():Promise<void>;

export function ListCollaborativeProjectActivity(arg1:string):Promise<Array<main.TaskActivity>>;

export function ListCollaborativeProjectMembers(arg1:string):Promise<Array<main.ProjectMember>>;

export function ListCollaborativeProjectTasks(arg1:string,arg2:boolean):Promise<Array<main.TaskItem>>;

export function ListCollaborativeProjects(arg1:boolean):Promise<Array<main.Project>>;

export function ListCollaborativeTaskActivity(arg1:string):Promise<Array<main.TaskActivity>>;

export function ListCollaborativeTaskComments(arg1:string):Promise<Array<main.TaskComment>>;

export function ListCollaborativeTasksForEmployee(arg1:string,arg2:boolean):Promise<Array<main.TaskItem>>;

export function ListCollaborativeTeamTasks(arg1:boolean):Promise<Array<main.TaskItem>>;

export function ListEmployeeAccessLinks():Promise<Array<main.EmployeeAccessLink>>;

export function ListEmployeeContributionSummaries():Promise<Array<main.EmployeeContributionSummary>>;

export function ListEmployeeProfiles(arg1:boolean):Promise<Array<main.Employee>>;

export function ListEmployeeProjectAssignments(arg1:string):Promise<Array<main.ProjectMember>>;

export function ListMyCollaborativeTasks(arg1:boolean):Promise<Array<main.TaskItem>>;

export function ListNotificationFeed(arg1:number,arg2:boolean):Promise<Array<main.Notification>>;

export function MarkNotificationAsRead(arg1:string):Promise<void>;

export function PerformFirstRunSync():Promise<Record<string, any>>;

export function PullChanges(arg1:time.Time):Promise<void>;

export function PushChanges():Promise<void>;

export function ReassignCollaborativeTask(arg1:string,arg2:string):Promise<void>;

export function ReassignEmployeeLicenseAccess(arg1:string,arg2:string,arg3:boolean):Promise<main.EmployeeAccessLink>;

export function ReassignEmployeeManager(arg1:string,arg2:string):Promise<main.Employee>;

export function RefreshCollaborativeWorkspace():Promise<void>;

export function SetEmployeeEmploymentState(arg1:string,arg2:boolean,arg3:string):Promise<main.Employee>;

export function ShelveCollaborativeProject(arg1:string,arg2:string):Promise<main.Project>;

export function StartBackgroundDBSync():Promise<void>;

export function StartCollaborativeSyncLoop(arg1:time.Duration):Promise<void>;

export function StartPeriodicSync(arg1:time.Duration):Promise<void>;

export function StopBackgroundDBSync():Promise<void>;

export function StopCollaborativeSyncLoop():Promise<void>;

export function StopPeriodicSync():Promise<void>;

export function SyncNowWithProgress():Promise<main.DBSyncResult>;

export function TestSupabaseConnection(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<boolean>;

export function TriggerManualSync():Promise<Record<string, any>>;

export function UpdateCollaborativeProject(arg1:string,arg2:Record<string, any>):Promise<main.Project>;

export function UpdateCollaborativeTask(arg1:main.TaskItem):Promise<main.TaskItem>;

export function UpdateCollaborativeTaskDueDate(arg1:string,arg2:string):Promise<void>;

export function UpdateCollaborativeTaskStatus(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateDBSyncSettings(arg1:boolean,arg2:number):Promise<void>;

export function UpdateEmployeeProfile(arg1:main.Employee):Promise<main.Employee>;
