// Code generated by capnpc-go. DO NOT EDIT.

package butler

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	math "math"
	common "ph_holdings_app/schemas/go/common"
	crm "ph_holdings_app/schemas/go/crm"
)

type ChatRole uint16

// ChatRole_TypeID is the unique identifier for the type ChatRole.
const ChatRole_TypeID = 0xaede905ffa6eab98

// Values of ChatRole.
const (
	ChatRole_user      ChatRole = 0
	ChatRole_assistant ChatRole = 1
	ChatRole_system    ChatRole = 2
)

// String returns the enum's constant name.
func (c ChatRole) String() string {
	switch c {
	case ChatRole_user:
		return "user"
	case ChatRole_assistant:
		return "assistant"
	case ChatRole_system:
		return "system"

	default:
		return ""
	}
}

// ChatRoleFromString returns the enum value with a name,
// or the zero value if there's no such value.
func ChatRoleFromString(c string) ChatRole {
	switch c {
	case "user":
		return ChatRole_user
	case "assistant":
		return ChatRole_assistant
	case "system":
		return ChatRole_system

	default:
		return 0
	}
}

type ChatRole_List = capnp.EnumList[ChatRole]

func NewChatRole_List(s *capnp.Segment, sz int32) (ChatRole_List, error) {
	return capnp.NewEnumList[ChatRole](s, sz)
}

type ActionStatus uint16

// ActionStatus_TypeID is the unique identifier for the type ActionStatus.
const ActionStatus_TypeID = 0xd9c81720af726530

// Values of ActionStatus.
const (
	ActionStatus_none      ActionStatus = 0
	ActionStatus_pending   ActionStatus = 1
	ActionStatus_executed  ActionStatus = 2
	ActionStatus_failed    ActionStatus = 3
	ActionStatus_dismissed ActionStatus = 4
)

// String returns the enum's constant name.
func (c ActionStatus) String() string {
	switch c {
	case ActionStatus_none:
		return "none"
	case ActionStatus_pending:
		return "pending"
	case ActionStatus_executed:
		return "executed"
	case ActionStatus_failed:
		return "failed"
	case ActionStatus_dismissed:
		return "dismissed"

	default:
		return ""
	}
}

// ActionStatusFromString returns the enum value with a name,
// or the zero value if there's no such value.
func ActionStatusFromString(c string) ActionStatus {
	switch c {
	case "none":
		return ActionStatus_none
	case "pending":
		return ActionStatus_pending
	case "executed":
		return ActionStatus_executed
	case "failed":
		return ActionStatus_failed
	case "dismissed":
		return ActionStatus_dismissed

	default:
		return 0
	}
}

type ActionStatus_List = capnp.EnumList[ActionStatus]

func NewActionStatus_List(s *capnp.Segment, sz int32) (ActionStatus_List, error) {
	return capnp.NewEnumList[ActionStatus](s, sz)
}

type ButlerResponse capnp.Struct

// ButlerResponse_TypeID is the unique identifier for the type ButlerResponse.
const ButlerResponse_TypeID = 0x943df422f7e3be04

func NewButlerResponse(s *capnp.Segment) (ButlerResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return ButlerResponse(st), err
}

func NewRootButlerResponse(s *capnp.Segment) (ButlerResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return ButlerResponse(st), err
}

func ReadRootButlerResponse(msg *capnp.Message) (ButlerResponse, error) {
	root, err := msg.Root()
	return ButlerResponse(root.Struct()), err
}

func (s ButlerResponse) String() string {
	str, _ := text.Marshal(0x943df422f7e3be04, capnp.Struct(s))
	return str
}

func (s ButlerResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ButlerResponse) DecodeFromPtr(p capnp.Ptr) ButlerResponse {
	return ButlerResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ButlerResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ButlerResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ButlerResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ButlerResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ButlerResponse) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ButlerResponse) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ButlerResponse) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ButlerResponse) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ButlerResponse) Actions() (ButlerAction_List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return ButlerAction_List(p.List()), err
}

func (s ButlerResponse) HasActions() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ButlerResponse) SetActions(v ButlerAction_List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewActions sets the actions field to a newly
// allocated ButlerAction_List, preferring placement in s's segment.
func (s ButlerResponse) NewActions(n int32) (ButlerAction_List, error) {
	l, err := NewButlerAction_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return ButlerAction_List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s ButlerResponse) Confidence() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s ButlerResponse) SetConfidence(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s ButlerResponse) Context() (common.KeyValue_List, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return common.KeyValue_List(p.List()), err
}

func (s ButlerResponse) HasContext() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ButlerResponse) SetContext(v common.KeyValue_List) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewContext sets the context field to a newly
// allocated common.KeyValue_List, preferring placement in s's segment.
func (s ButlerResponse) NewContext(n int32) (common.KeyValue_List, error) {
	l, err := common.NewKeyValue_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return common.KeyValue_List{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}
func (s ButlerResponse) Metadata() (ButlerResponseMetadata, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return ButlerResponseMetadata(p.Struct()), err
}

func (s ButlerResponse) HasMetadata() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ButlerResponse) SetMetadata(v ButlerResponseMetadata) error {
	return capnp.Struct(s).SetPtr(3, capnp.Struct(v).ToPtr())
}

// NewMetadata sets the metadata field to a newly
// allocated ButlerResponseMetadata struct, preferring placement in s's segment.
func (s ButlerResponse) NewMetadata() (ButlerResponseMetadata, error) {
	ss, err := NewButlerResponseMetadata(capnp.Struct(s).Segment())
	if err != nil {
		return ButlerResponseMetadata{}, err
	}
	err = capnp.Struct(s).SetPtr(3, capnp.Struct(ss).ToPtr())
	return ss, err
}

// ButlerResponse_List is a list of ButlerResponse.
type ButlerResponse_List = capnp.StructList[ButlerResponse]

// NewButlerResponse creates a new list of ButlerResponse.
func NewButlerResponse_List(s *capnp.Segment, sz int32) (ButlerResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4}, sz)
	return capnp.StructList[ButlerResponse](l), err
}

// ButlerResponse_Future is a wrapper for a ButlerResponse promised by a client call.
type ButlerResponse_Future struct{ *capnp.Future }

func (f ButlerResponse_Future) Struct() (ButlerResponse, error) {
	p, err := f.Future.Ptr()
	return ButlerResponse(p.Struct()), err
}
func (p ButlerResponse_Future) Metadata() ButlerResponseMetadata_Future {
	return ButlerResponseMetadata_Future{Future: p.Future.Field(3, nil)}
}

type ButlerResponseMetadata capnp.Struct

// ButlerResponseMetadata_TypeID is the unique identifier for the type ButlerResponseMetadata.
const ButlerResponseMetadata_TypeID = 0xadf3d4cfe127f1cd

func NewButlerResponseMetadata(s *capnp.Segment) (ButlerResponseMetadata, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 9})
	return ButlerResponseMetadata(st), err
}

func NewRootButlerResponseMetadata(s *capnp.Segment) (ButlerResponseMetadata, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 9})
	return ButlerResponseMetadata(st), err
}

func ReadRootButlerResponseMetadata(msg *capnp.Message) (ButlerResponseMetadata, error) {
	root, err := msg.Root()
	return ButlerResponseMetadata(root.Struct()), err
}

func (s ButlerResponseMetadata) String() string {
	str, _ := text.Marshal(0xadf3d4cfe127f1cd, capnp.Struct(s))
	return str
}

func (s ButlerResponseMetadata) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ButlerResponseMetadata) DecodeFromPtr(p capnp.Ptr) ButlerResponseMetadata {
	return ButlerResponseMetadata(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ButlerResponseMetadata) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ButlerResponseMetadata) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ButlerResponseMetadata) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ButlerResponseMetadata) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ButlerResponseMetadata) UsedBackend() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ButlerResponseMetadata) HasUsedBackend() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ButlerResponseMetadata) UsedBackendBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ButlerResponseMetadata) SetUsedBackend(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ButlerResponseMetadata) RequestedModel() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ButlerResponseMetadata) HasRequestedModel() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ButlerResponseMetadata) RequestedModelBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ButlerResponseMetadata) SetRequestedModel(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ButlerResponseMetadata) UsedModel() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ButlerResponseMetadata) HasUsedModel() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ButlerResponseMetadata) UsedModelBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ButlerResponseMetadata) SetUsedModel(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s ButlerResponseMetadata) FallbackReason() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s ButlerResponseMetadata) HasFallbackReason() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ButlerResponseMetadata) FallbackReasonBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s ButlerResponseMetadata) SetFallbackReason(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s ButlerResponseMetadata) FinanceDataAccess() bool {
	return capnp.Struct(s).Bit(0)
}

func (s ButlerResponseMetadata) SetFinanceDataAccess(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s ButlerResponseMetadata) ContextMode() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s ButlerResponseMetadata) HasContextMode() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s ButlerResponseMetadata) ContextModeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s ButlerResponseMetadata) SetContextMode(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s ButlerResponseMetadata) DataCoverage() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return capnp.TextList(p.List()), err
}

func (s ButlerResponseMetadata) HasDataCoverage() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s ButlerResponseMetadata) SetDataCoverage(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(5, v.ToPtr())
}

// NewDataCoverage sets the dataCoverage field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s ButlerResponseMetadata) NewDataCoverage(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(5, l.ToPtr())
	return l, err
}
func (s ButlerResponseMetadata) EntityResolution() (common.KeyValue_List, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return common.KeyValue_List(p.List()), err
}

func (s ButlerResponseMetadata) HasEntityResolution() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s ButlerResponseMetadata) SetEntityResolution(v common.KeyValue_List) error {
	return capnp.Struct(s).SetPtr(6, v.ToPtr())
}

// NewEntityResolution sets the entityResolution field to a newly
// allocated common.KeyValue_List, preferring placement in s's segment.
func (s ButlerResponseMetadata) NewEntityResolution(n int32) (common.KeyValue_List, error) {
	l, err := common.NewKeyValue_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return common.KeyValue_List{}, err
	}
	err = capnp.Struct(s).SetPtr(6, l.ToPtr())
	return l, err
}
func (s ButlerResponseMetadata) GeneratedAt() (string, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.Text(), err
}

func (s ButlerResponseMetadata) HasGeneratedAt() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s ButlerResponseMetadata) GeneratedAtBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.TextBytes(), err
}

func (s ButlerResponseMetadata) SetGeneratedAt(v string) error {
	return capnp.Struct(s).SetText(7, v)
}

func (s ButlerResponseMetadata) Error() (string, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.Text(), err
}

func (s ButlerResponseMetadata) HasError() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s ButlerResponseMetadata) ErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.TextBytes(), err
}

func (s ButlerResponseMetadata) SetError(v string) error {
	return capnp.Struct(s).SetText(8, v)
}

// ButlerResponseMetadata_List is a list of ButlerResponseMetadata.
type ButlerResponseMetadata_List = capnp.StructList[ButlerResponseMetadata]

// NewButlerResponseMetadata creates a new list of ButlerResponseMetadata.
func NewButlerResponseMetadata_List(s *capnp.Segment, sz int32) (ButlerResponseMetadata_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 9}, sz)
	return capnp.StructList[ButlerResponseMetadata](l), err
}

// ButlerResponseMetadata_Future is a wrapper for a ButlerResponseMetadata promised by a client call.
type ButlerResponseMetadata_Future struct{ *capnp.Future }

func (f ButlerResponseMetadata_Future) Struct() (ButlerResponseMetadata, error) {
	p, err := f.Future.Ptr()
	return ButlerResponseMetadata(p.Struct()), err
}

type ButlerAction capnp.Struct

// ButlerAction_TypeID is the unique identifier for the type ButlerAction.
const ButlerAction_TypeID = 0x9a46140df81b5147

func NewButlerAction(s *capnp.Segment) (ButlerAction, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return ButlerAction(st), err
}

func NewRootButlerAction(s *capnp.Segment) (ButlerAction, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return ButlerAction(st), err
}

func ReadRootButlerAction(msg *capnp.Message) (ButlerAction, error) {
	root, err := msg.Root()
	return ButlerAction(root.Struct()), err
}

func (s ButlerAction) String() string {
	str, _ := text.Marshal(0x9a46140df81b5147, capnp.Struct(s))
	return str
}

func (s ButlerAction) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ButlerAction) DecodeFromPtr(p capnp.Ptr) ButlerAction {
	return ButlerAction(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ButlerAction) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ButlerAction) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ButlerAction) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ButlerAction) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ButlerAction) Type() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ButlerAction) HasType() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ButlerAction) TypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ButlerAction) SetType(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ButlerAction) Target() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ButlerAction) HasTarget() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ButlerAction) TargetBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ButlerAction) SetTarget(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ButlerAction) Label() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ButlerAction) HasLabel() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ButlerAction) LabelBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ButlerAction) SetLabel(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s ButlerAction) Data() (common.KeyValue_List, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return common.KeyValue_List(p.List()), err
}

func (s ButlerAction) HasData() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ButlerAction) SetData(v common.KeyValue_List) error {
	return capnp.Struct(s).SetPtr(3, v.ToPtr())
}

// NewData sets the data field to a newly
// allocated common.KeyValue_List, preferring placement in s's segment.
func (s ButlerAction) NewData(n int32) (common.KeyValue_List, error) {
	l, err := common.NewKeyValue_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return common.KeyValue_List{}, err
	}
	err = capnp.Struct(s).SetPtr(3, l.ToPtr())
	return l, err
}

// ButlerAction_List is a list of ButlerAction.
type ButlerAction_List = capnp.StructList[ButlerAction]

// NewButlerAction creates a new list of ButlerAction.
func NewButlerAction_List(s *capnp.Segment, sz int32) (ButlerAction_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[ButlerAction](l), err
}

// ButlerAction_Future is a wrapper for a ButlerAction promised by a client call.
type ButlerAction_Future struct{ *capnp.Future }

func (f ButlerAction_Future) Struct() (ButlerAction, error) {
	p, err := f.Future.Ptr()
	return ButlerAction(p.Struct()), err
}

type Intent capnp.Struct

// Intent_TypeID is the unique identifier for the type Intent.
const Intent_TypeID = 0x83b3cc4d458f667e

func NewIntent(s *capnp.Segment) (Intent, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 6})
	return Intent(st), err
}

func NewRootIntent(s *capnp.Segment) (Intent, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 6})
	return Intent(st), err
}

func ReadRootIntent(msg *capnp.Message) (Intent, error) {
	root, err := msg.Root()
	return Intent(root.Struct()), err
}

func (s Intent) String() string {
	str, _ := text.Marshal(0x83b3cc4d458f667e, capnp.Struct(s))
	return str
}

func (s Intent) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Intent) DecodeFromPtr(p capnp.Ptr) Intent {
	return Intent(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Intent) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Intent) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Intent) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Intent) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Intent) RawQuery() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Intent) HasRawQuery() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Intent) RawQueryBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Intent) SetRawQuery(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Intent) Domain() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Intent) HasDomain() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Intent) DomainBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Intent) SetDomain(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Intent) EntityName() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Intent) HasEntityName() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Intent) EntityNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Intent) SetEntityName(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Intent) PersonName() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Intent) HasPersonName() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Intent) PersonNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Intent) SetPersonName(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Intent) ReferenceKind() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s Intent) HasReferenceKind() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Intent) ReferenceKindBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s Intent) SetReferenceKind(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s Intent) Confidence() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Intent) SetConfidence(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s Intent) Keywords() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return capnp.TextList(p.List()), err
}

func (s Intent) HasKeywords() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Intent) SetKeywords(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(5, v.ToPtr())
}

// NewKeywords sets the keywords field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s Intent) NewKeywords(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(5, l.ToPtr())
	return l, err
}
func (s Intent) NeedsScraper() bool {
	return capnp.Struct(s).Bit(64)
}

func (s Intent) SetNeedsScraper(v bool) {
	capnp.Struct(s).SetBit(64, v)
}

func (s Intent) IsComplex() bool {
	return capnp.Struct(s).Bit(65)
}

func (s Intent) SetIsComplex(v bool) {
	capnp.Struct(s).SetBit(65, v)
}

// Intent_List is a list of Intent.
type Intent_List = capnp.StructList[Intent]

// NewIntent creates a new list of Intent.
func NewIntent_List(s *capnp.Segment, sz int32) (Intent_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 6}, sz)
	return capnp.StructList[Intent](l), err
}

// Intent_Future is a wrapper for a Intent promised by a client call.
type Intent_Future struct{ *capnp.Future }

func (f Intent_Future) Struct() (Intent, error) {
	p, err := f.Future.Ptr()
	return Intent(p.Struct()), err
}

type ButlerResolvedEntity capnp.Struct

// ButlerResolvedEntity_TypeID is the unique identifier for the type ButlerResolvedEntity.
const ButlerResolvedEntity_TypeID = 0xe617be76b966e2d5

func NewButlerResolvedEntity(s *capnp.Segment) (ButlerResolvedEntity, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 7})
	return ButlerResolvedEntity(st), err
}

func NewRootButlerResolvedEntity(s *capnp.Segment) (ButlerResolvedEntity, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 7})
	return ButlerResolvedEntity(st), err
}

func ReadRootButlerResolvedEntity(msg *capnp.Message) (ButlerResolvedEntity, error) {
	root, err := msg.Root()
	return ButlerResolvedEntity(root.Struct()), err
}

func (s ButlerResolvedEntity) String() string {
	str, _ := text.Marshal(0xe617be76b966e2d5, capnp.Struct(s))
	return str
}

func (s ButlerResolvedEntity) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ButlerResolvedEntity) DecodeFromPtr(p capnp.Ptr) ButlerResolvedEntity {
	return ButlerResolvedEntity(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ButlerResolvedEntity) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ButlerResolvedEntity) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ButlerResolvedEntity) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ButlerResolvedEntity) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ButlerResolvedEntity) EntityType() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ButlerResolvedEntity) HasEntityType() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ButlerResolvedEntity) EntityTypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ButlerResolvedEntity) SetEntityType(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ButlerResolvedEntity) EntityId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ButlerResolvedEntity) HasEntityId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ButlerResolvedEntity) EntityIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ButlerResolvedEntity) SetEntityId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ButlerResolvedEntity) DisplayName() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ButlerResolvedEntity) HasDisplayName() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ButlerResolvedEntity) DisplayNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ButlerResolvedEntity) SetDisplayName(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s ButlerResolvedEntity) Confidence() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s ButlerResolvedEntity) SetConfidence(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s ButlerResolvedEntity) MatchReason() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s ButlerResolvedEntity) HasMatchReason() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ButlerResolvedEntity) MatchReasonBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s ButlerResolvedEntity) SetMatchReason(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s ButlerResolvedEntity) RelatedCustomerId() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s ButlerResolvedEntity) HasRelatedCustomerId() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s ButlerResolvedEntity) RelatedCustomerIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s ButlerResolvedEntity) SetRelatedCustomerId(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s ButlerResolvedEntity) RelatedCustomer() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s ButlerResolvedEntity) HasRelatedCustomer() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s ButlerResolvedEntity) RelatedCustomerBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s ButlerResolvedEntity) SetRelatedCustomer(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s ButlerResolvedEntity) Ambiguous() bool {
	return capnp.Struct(s).Bit(64)
}

func (s ButlerResolvedEntity) SetAmbiguous(v bool) {
	capnp.Struct(s).SetBit(64, v)
}

func (s ButlerResolvedEntity) Alternatives() (common.KeyValue_List, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return common.KeyValue_List(p.List()), err
}

func (s ButlerResolvedEntity) HasAlternatives() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s ButlerResolvedEntity) SetAlternatives(v common.KeyValue_List) error {
	return capnp.Struct(s).SetPtr(6, v.ToPtr())
}

// NewAlternatives sets the alternatives field to a newly
// allocated common.KeyValue_List, preferring placement in s's segment.
func (s ButlerResolvedEntity) NewAlternatives(n int32) (common.KeyValue_List, error) {
	l, err := common.NewKeyValue_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return common.KeyValue_List{}, err
	}
	err = capnp.Struct(s).SetPtr(6, l.ToPtr())
	return l, err
}

// ButlerResolvedEntity_List is a list of ButlerResolvedEntity.
type ButlerResolvedEntity_List = capnp.StructList[ButlerResolvedEntity]

// NewButlerResolvedEntity creates a new list of ButlerResolvedEntity.
func NewButlerResolvedEntity_List(s *capnp.Segment, sz int32) (ButlerResolvedEntity_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 7}, sz)
	return capnp.StructList[ButlerResolvedEntity](l), err
}

// ButlerResolvedEntity_Future is a wrapper for a ButlerResolvedEntity promised by a client call.
type ButlerResolvedEntity_Future struct{ *capnp.Future }

func (f ButlerResolvedEntity_Future) Struct() (ButlerResolvedEntity, error) {
	p, err := f.Future.Ptr()
	return ButlerResolvedEntity(p.Struct()), err
}

type PredictionRecord capnp.Struct

// PredictionRecord_TypeID is the unique identifier for the type PredictionRecord.
const PredictionRecord_TypeID = 0xd4a91df025854b79

func NewPredictionRecord(s *capnp.Segment) (PredictionRecord, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 48, PointerCount: 3})
	return PredictionRecord(st), err
}

func NewRootPredictionRecord(s *capnp.Segment) (PredictionRecord, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 48, PointerCount: 3})
	return PredictionRecord(st), err
}

func ReadRootPredictionRecord(msg *capnp.Message) (PredictionRecord, error) {
	root, err := msg.Root()
	return PredictionRecord(root.Struct()), err
}

func (s PredictionRecord) String() string {
	str, _ := text.Marshal(0xd4a91df025854b79, capnp.Struct(s))
	return str
}

func (s PredictionRecord) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PredictionRecord) DecodeFromPtr(p capnp.Ptr) PredictionRecord {
	return PredictionRecord(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PredictionRecord) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PredictionRecord) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PredictionRecord) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PredictionRecord) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PredictionRecord) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s PredictionRecord) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PredictionRecord) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s PredictionRecord) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s PredictionRecord) CustomerId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s PredictionRecord) HasCustomerId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s PredictionRecord) CustomerIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s PredictionRecord) SetCustomerId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s PredictionRecord) CustomerName() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s PredictionRecord) HasCustomerName() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s PredictionRecord) CustomerNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s PredictionRecord) SetCustomerName(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s PredictionRecord) Grade() crm.CustomerGrade {
	return crm.CustomerGrade(capnp.Struct(s).Uint16(0))
}

func (s PredictionRecord) SetGrade(v crm.CustomerGrade) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s PredictionRecord) PredictedDays() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s PredictionRecord) SetPredictedDays(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s PredictionRecord) Confidence() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(16))
}

func (s PredictionRecord) SetConfidence(v float64) {
	capnp.Struct(s).SetUint64(16, math.Float64bits(v))
}

func (s PredictionRecord) R1() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(24))
}

func (s PredictionRecord) SetR1(v float64) {
	capnp.Struct(s).SetUint64(24, math.Float64bits(v))
}

func (s PredictionRecord) R2() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(32))
}

func (s PredictionRecord) SetR2(v float64) {
	capnp.Struct(s).SetUint64(32, math.Float64bits(v))
}

func (s PredictionRecord) R3() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(40))
}

func (s PredictionRecord) SetR3(v float64) {
	capnp.Struct(s).SetUint64(40, math.Float64bits(v))
}

// PredictionRecord_List is a list of PredictionRecord.
type PredictionRecord_List = capnp.StructList[PredictionRecord]

// NewPredictionRecord creates a new list of PredictionRecord.
func NewPredictionRecord_List(s *capnp.Segment, sz int32) (PredictionRecord_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 48, PointerCount: 3}, sz)
	return capnp.StructList[PredictionRecord](l), err
}

// PredictionRecord_Future is a wrapper for a PredictionRecord promised by a client call.
type PredictionRecord_Future struct{ *capnp.Future }

func (f PredictionRecord_Future) Struct() (PredictionRecord, error) {
	p, err := f.Future.Ptr()
	return PredictionRecord(p.Struct()), err
}
func (p PredictionRecord_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}

type WinProbabilityPrediction capnp.Struct

// WinProbabilityPrediction_TypeID is the unique identifier for the type WinProbabilityPrediction.
const WinProbabilityPrediction_TypeID = 0xb8da332c086bb68b

func NewWinProbabilityPrediction(s *capnp.Segment) (WinProbabilityPrediction, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return WinProbabilityPrediction(st), err
}

func NewRootWinProbabilityPrediction(s *capnp.Segment) (WinProbabilityPrediction, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return WinProbabilityPrediction(st), err
}

func ReadRootWinProbabilityPrediction(msg *capnp.Message) (WinProbabilityPrediction, error) {
	root, err := msg.Root()
	return WinProbabilityPrediction(root.Struct()), err
}

func (s WinProbabilityPrediction) String() string {
	str, _ := text.Marshal(0xb8da332c086bb68b, capnp.Struct(s))
	return str
}

func (s WinProbabilityPrediction) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (WinProbabilityPrediction) DecodeFromPtr(p capnp.Ptr) WinProbabilityPrediction {
	return WinProbabilityPrediction(capnp.Struct{}.DecodeFromPtr(p))
}

func (s WinProbabilityPrediction) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s WinProbabilityPrediction) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s WinProbabilityPrediction) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s WinProbabilityPrediction) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s WinProbabilityPrediction) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s WinProbabilityPrediction) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s WinProbabilityPrediction) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s WinProbabilityPrediction) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s WinProbabilityPrediction) OfferId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s WinProbabilityPrediction) HasOfferId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s WinProbabilityPrediction) OfferIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s WinProbabilityPrediction) SetOfferId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s WinProbabilityPrediction) PredictedProbability() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s WinProbabilityPrediction) SetPredictedProbability(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

// WinProbabilityPrediction_List is a list of WinProbabilityPrediction.
type WinProbabilityPrediction_List = capnp.StructList[WinProbabilityPrediction]

// NewWinProbabilityPrediction creates a new list of WinProbabilityPrediction.
func NewWinProbabilityPrediction_List(s *capnp.Segment, sz int32) (WinProbabilityPrediction_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[WinProbabilityPrediction](l), err
}

// WinProbabilityPrediction_Future is a wrapper for a WinProbabilityPrediction promised by a client call.
type WinProbabilityPrediction_Future struct{ *capnp.Future }

func (f WinProbabilityPrediction_Future) Struct() (WinProbabilityPrediction, error) {
	p, err := f.Future.Ptr()
	return WinProbabilityPrediction(p.Struct()), err
}
func (p WinProbabilityPrediction_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}

type DiscountRecommendationRecord capnp.Struct

// DiscountRecommendationRecord_TypeID is the unique identifier for the type DiscountRecommendationRecord.
const DiscountRecommendationRecord_TypeID = 0xed73475137e563d3

func NewDiscountRecommendationRecord(s *capnp.Segment) (DiscountRecommendationRecord, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return DiscountRecommendationRecord(st), err
}

func NewRootDiscountRecommendationRecord(s *capnp.Segment) (DiscountRecommendationRecord, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return DiscountRecommendationRecord(st), err
}

func ReadRootDiscountRecommendationRecord(msg *capnp.Message) (DiscountRecommendationRecord, error) {
	root, err := msg.Root()
	return DiscountRecommendationRecord(root.Struct()), err
}

func (s DiscountRecommendationRecord) String() string {
	str, _ := text.Marshal(0xed73475137e563d3, capnp.Struct(s))
	return str
}

func (s DiscountRecommendationRecord) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (DiscountRecommendationRecord) DecodeFromPtr(p capnp.Ptr) DiscountRecommendationRecord {
	return DiscountRecommendationRecord(capnp.Struct{}.DecodeFromPtr(p))
}

func (s DiscountRecommendationRecord) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s DiscountRecommendationRecord) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s DiscountRecommendationRecord) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s DiscountRecommendationRecord) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s DiscountRecommendationRecord) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s DiscountRecommendationRecord) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s DiscountRecommendationRecord) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s DiscountRecommendationRecord) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s DiscountRecommendationRecord) OfferId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s DiscountRecommendationRecord) HasOfferId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s DiscountRecommendationRecord) OfferIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s DiscountRecommendationRecord) SetOfferId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s DiscountRecommendationRecord) RecommendedDiscount() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s DiscountRecommendationRecord) SetRecommendedDiscount(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

// DiscountRecommendationRecord_List is a list of DiscountRecommendationRecord.
type DiscountRecommendationRecord_List = capnp.StructList[DiscountRecommendationRecord]

// NewDiscountRecommendationRecord creates a new list of DiscountRecommendationRecord.
func NewDiscountRecommendationRecord_List(s *capnp.Segment, sz int32) (DiscountRecommendationRecord_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[DiscountRecommendationRecord](l), err
}

// DiscountRecommendationRecord_Future is a wrapper for a DiscountRecommendationRecord promised by a client call.
type DiscountRecommendationRecord_Future struct{ *capnp.Future }

func (f DiscountRecommendationRecord_Future) Struct() (DiscountRecommendationRecord, error) {
	p, err := f.Future.Ptr()
	return DiscountRecommendationRecord(p.Struct()), err
}
func (p DiscountRecommendationRecord_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}

type CustomerSnapshot capnp.Struct

// CustomerSnapshot_TypeID is the unique identifier for the type CustomerSnapshot.
const CustomerSnapshot_TypeID = 0xf7229628c7d89e67

func NewCustomerSnapshot(s *capnp.Segment) (CustomerSnapshot, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return CustomerSnapshot(st), err
}

func NewRootCustomerSnapshot(s *capnp.Segment) (CustomerSnapshot, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return CustomerSnapshot(st), err
}

func ReadRootCustomerSnapshot(msg *capnp.Message) (CustomerSnapshot, error) {
	root, err := msg.Root()
	return CustomerSnapshot(root.Struct()), err
}

func (s CustomerSnapshot) String() string {
	str, _ := text.Marshal(0xf7229628c7d89e67, capnp.Struct(s))
	return str
}

func (s CustomerSnapshot) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomerSnapshot) DecodeFromPtr(p capnp.Ptr) CustomerSnapshot {
	return CustomerSnapshot(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomerSnapshot) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomerSnapshot) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomerSnapshot) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomerSnapshot) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CustomerSnapshot) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s CustomerSnapshot) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CustomerSnapshot) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s CustomerSnapshot) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s CustomerSnapshot) CustomerId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s CustomerSnapshot) HasCustomerId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CustomerSnapshot) CustomerIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s CustomerSnapshot) SetCustomerId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s CustomerSnapshot) OrderValue() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s CustomerSnapshot) SetOrderValue(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

// CustomerSnapshot_List is a list of CustomerSnapshot.
type CustomerSnapshot_List = capnp.StructList[CustomerSnapshot]

// NewCustomerSnapshot creates a new list of CustomerSnapshot.
func NewCustomerSnapshot_List(s *capnp.Segment, sz int32) (CustomerSnapshot_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[CustomerSnapshot](l), err
}

// CustomerSnapshot_Future is a wrapper for a CustomerSnapshot promised by a client call.
type CustomerSnapshot_Future struct{ *capnp.Future }

func (f CustomerSnapshot_Future) Struct() (CustomerSnapshot, error) {
	p, err := f.Future.Ptr()
	return CustomerSnapshot(p.Struct()), err
}
func (p CustomerSnapshot_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}

type ActualOutcome capnp.Struct

// ActualOutcome_TypeID is the unique identifier for the type ActualOutcome.
const ActualOutcome_TypeID = 0xc58caa5a72a15cfc

func NewActualOutcome(s *capnp.Segment) (ActualOutcome, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return ActualOutcome(st), err
}

func NewRootActualOutcome(s *capnp.Segment) (ActualOutcome, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return ActualOutcome(st), err
}

func ReadRootActualOutcome(msg *capnp.Message) (ActualOutcome, error) {
	root, err := msg.Root()
	return ActualOutcome(root.Struct()), err
}

func (s ActualOutcome) String() string {
	str, _ := text.Marshal(0xc58caa5a72a15cfc, capnp.Struct(s))
	return str
}

func (s ActualOutcome) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ActualOutcome) DecodeFromPtr(p capnp.Ptr) ActualOutcome {
	return ActualOutcome(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ActualOutcome) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ActualOutcome) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ActualOutcome) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ActualOutcome) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ActualOutcome) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s ActualOutcome) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ActualOutcome) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s ActualOutcome) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s ActualOutcome) CustomerId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ActualOutcome) HasCustomerId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ActualOutcome) CustomerIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ActualOutcome) SetCustomerId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ActualOutcome) WasPaid() bool {
	return capnp.Struct(s).Bit(0)
}

func (s ActualOutcome) SetWasPaid(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

// ActualOutcome_List is a list of ActualOutcome.
type ActualOutcome_List = capnp.StructList[ActualOutcome]

// NewActualOutcome creates a new list of ActualOutcome.
func NewActualOutcome_List(s *capnp.Segment, sz int32) (ActualOutcome_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[ActualOutcome](l), err
}

// ActualOutcome_Future is a wrapper for a ActualOutcome promised by a client call.
type ActualOutcome_Future struct{ *capnp.Future }

func (f ActualOutcome_Future) Struct() (ActualOutcome, error) {
	p, err := f.Future.Ptr()
	return ActualOutcome(p.Struct()), err
}
func (p ActualOutcome_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}

type PaymentPredictionAccuracy capnp.Struct

// PaymentPredictionAccuracy_TypeID is the unique identifier for the type PaymentPredictionAccuracy.
const PaymentPredictionAccuracy_TypeID = 0xa86c764b2337eb0c

func NewPaymentPredictionAccuracy(s *capnp.Segment) (PaymentPredictionAccuracy, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return PaymentPredictionAccuracy(st), err
}

func NewRootPaymentPredictionAccuracy(s *capnp.Segment) (PaymentPredictionAccuracy, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return PaymentPredictionAccuracy(st), err
}

func ReadRootPaymentPredictionAccuracy(msg *capnp.Message) (PaymentPredictionAccuracy, error) {
	root, err := msg.Root()
	return PaymentPredictionAccuracy(root.Struct()), err
}

func (s PaymentPredictionAccuracy) String() string {
	str, _ := text.Marshal(0xa86c764b2337eb0c, capnp.Struct(s))
	return str
}

func (s PaymentPredictionAccuracy) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PaymentPredictionAccuracy) DecodeFromPtr(p capnp.Ptr) PaymentPredictionAccuracy {
	return PaymentPredictionAccuracy(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PaymentPredictionAccuracy) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PaymentPredictionAccuracy) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PaymentPredictionAccuracy) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PaymentPredictionAccuracy) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PaymentPredictionAccuracy) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s PaymentPredictionAccuracy) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PaymentPredictionAccuracy) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s PaymentPredictionAccuracy) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s PaymentPredictionAccuracy) CustomerId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s PaymentPredictionAccuracy) HasCustomerId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s PaymentPredictionAccuracy) CustomerIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s PaymentPredictionAccuracy) SetCustomerId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s PaymentPredictionAccuracy) WasAccurate() bool {
	return capnp.Struct(s).Bit(0)
}

func (s PaymentPredictionAccuracy) SetWasAccurate(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

// PaymentPredictionAccuracy_List is a list of PaymentPredictionAccuracy.
type PaymentPredictionAccuracy_List = capnp.StructList[PaymentPredictionAccuracy]

// NewPaymentPredictionAccuracy creates a new list of PaymentPredictionAccuracy.
func NewPaymentPredictionAccuracy_List(s *capnp.Segment, sz int32) (PaymentPredictionAccuracy_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[PaymentPredictionAccuracy](l), err
}

// PaymentPredictionAccuracy_Future is a wrapper for a PaymentPredictionAccuracy promised by a client call.
type PaymentPredictionAccuracy_Future struct{ *capnp.Future }

func (f PaymentPredictionAccuracy_Future) Struct() (PaymentPredictionAccuracy, error) {
	p, err := f.Future.Ptr()
	return PaymentPredictionAccuracy(p.Struct()), err
}
func (p PaymentPredictionAccuracy_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}

type Conversation capnp.Struct

// Conversation_TypeID is the unique identifier for the type Conversation.
const Conversation_TypeID = 0xea0275ab566ead00

func NewConversation(s *capnp.Segment) (Conversation, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return Conversation(st), err
}

func NewRootConversation(s *capnp.Segment) (Conversation, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return Conversation(st), err
}

func ReadRootConversation(msg *capnp.Message) (Conversation, error) {
	root, err := msg.Root()
	return Conversation(root.Struct()), err
}

func (s Conversation) String() string {
	str, _ := text.Marshal(0xea0275ab566ead00, capnp.Struct(s))
	return str
}

func (s Conversation) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Conversation) DecodeFromPtr(p capnp.Ptr) Conversation {
	return Conversation(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Conversation) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Conversation) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Conversation) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Conversation) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Conversation) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s Conversation) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Conversation) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s Conversation) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Conversation) Title() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Conversation) HasTitle() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Conversation) TitleBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Conversation) SetTitle(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Conversation) Summary() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Conversation) HasSummary() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Conversation) SummaryBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Conversation) SetSummary(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Conversation) IsActive() bool {
	return capnp.Struct(s).Bit(0)
}

func (s Conversation) SetIsActive(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s Conversation) LastMsgAt() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Conversation) HasLastMsgAt() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Conversation) LastMsgAtBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Conversation) SetLastMsgAt(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

// Conversation_List is a list of Conversation.
type Conversation_List = capnp.StructList[Conversation]

// NewConversation creates a new list of Conversation.
func NewConversation_List(s *capnp.Segment, sz int32) (Conversation_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4}, sz)
	return capnp.StructList[Conversation](l), err
}

// Conversation_Future is a wrapper for a Conversation promised by a client call.
type Conversation_Future struct{ *capnp.Future }

func (f Conversation_Future) Struct() (Conversation, error) {
	p, err := f.Future.Ptr()
	return Conversation(p.Struct()), err
}
func (p Conversation_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}

type ChatMessage capnp.Struct

// ChatMessage_TypeID is the unique identifier for the type ChatMessage.
const ChatMessage_TypeID = 0x9a4f921948468c06

func NewChatMessage(s *capnp.Segment) (ChatMessage, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 9})
	return ChatMessage(st), err
}

func NewRootChatMessage(s *capnp.Segment) (ChatMessage, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 9})
	return ChatMessage(st), err
}

func ReadRootChatMessage(msg *capnp.Message) (ChatMessage, error) {
	root, err := msg.Root()
	return ChatMessage(root.Struct()), err
}

func (s ChatMessage) String() string {
	str, _ := text.Marshal(0x9a4f921948468c06, capnp.Struct(s))
	return str
}

func (s ChatMessage) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ChatMessage) DecodeFromPtr(p capnp.Ptr) ChatMessage {
	return ChatMessage(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ChatMessage) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ChatMessage) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ChatMessage) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ChatMessage) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ChatMessage) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s ChatMessage) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ChatMessage) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s ChatMessage) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s ChatMessage) ConversationId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ChatMessage) HasConversationId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ChatMessage) ConversationIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ChatMessage) SetConversationId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ChatMessage) Role() ChatRole {
	return ChatRole(capnp.Struct(s).Uint16(0))
}

func (s ChatMessage) SetRole(v ChatRole) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s ChatMessage) Content() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ChatMessage) HasContent() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ChatMessage) ContentBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ChatMessage) SetContent(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s ChatMessage) TokensUsed() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s ChatMessage) SetTokensUsed(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s ChatMessage) MessageType() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s ChatMessage) HasMessageType() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ChatMessage) MessageTypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s ChatMessage) SetMessageType(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s ChatMessage) ActionType() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s ChatMessage) HasActionType() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s ChatMessage) ActionTypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s ChatMessage) SetActionType(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s ChatMessage) ActionTarget() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s ChatMessage) HasActionTarget() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s ChatMessage) ActionTargetBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s ChatMessage) SetActionTarget(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s ChatMessage) ActionLabel() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s ChatMessage) HasActionLabel() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s ChatMessage) ActionLabelBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s ChatMessage) SetActionLabel(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

func (s ChatMessage) ActionData() (string, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.Text(), err
}

func (s ChatMessage) HasActionData() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s ChatMessage) ActionDataBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.TextBytes(), err
}

func (s ChatMessage) SetActionData(v string) error {
	return capnp.Struct(s).SetText(7, v)
}

func (s ChatMessage) ActionStatus() ActionStatus {
	return ActionStatus(capnp.Struct(s).Uint16(2))
}

func (s ChatMessage) SetActionStatus(v ActionStatus) {
	capnp.Struct(s).SetUint16(2, uint16(v))
}

func (s ChatMessage) ActionMetadata() (string, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.Text(), err
}

func (s ChatMessage) HasActionMetadata() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s ChatMessage) ActionMetadataBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.TextBytes(), err
}

func (s ChatMessage) SetActionMetadata(v string) error {
	return capnp.Struct(s).SetText(8, v)
}

// ChatMessage_List is a list of ChatMessage.
type ChatMessage_List = capnp.StructList[ChatMessage]

// NewChatMessage creates a new list of ChatMessage.
func NewChatMessage_List(s *capnp.Segment, sz int32) (ChatMessage_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 9}, sz)
	return capnp.StructList[ChatMessage](l), err
}

// ChatMessage_Future is a wrapper for a ChatMessage promised by a client call.
type ChatMessage_Future struct{ *capnp.Future }

func (f ChatMessage_Future) Struct() (ChatMessage, error) {
	p, err := f.Future.Ptr()
	return ChatMessage(p.Struct()), err
}
func (p ChatMessage_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}

const schema_d61eab82bab79d77 = "x\xda\x9cWml\x14\xd7\x15\xbdwf\xd7k\x82\x9d" +
	"\xf5f\xd6JHKm\x08V\x0d\xb8\x80\xedX\x04D" +
	"dl\xec\x04\x03\x06\xcf.\xa4\xc8\"j\x9eg\x9e\xed" +
	"\x0d\xbb3\x9b\x997\x86E$N\xd3 AKU\x82" +
	"h\x8bP\xa8\xda\xfei\x1bDI\xd4\xef\xaaI\x7fE" +
	"m\xa5\xa6U\xd4\xb4jZ\xb5RS\xf5+m\xa4\xa4" +
	"\x05\x85T\xa4S\xdd7\xbb3\xc3z\xa9\x0b\xf2\x9f\xd9" +
	"\xe3;o\xee{\xf7\x9c{\xee\xdb\xf0|\xeb\xd6Do" +
	"\xeb\xa5!P\xf2\xd7\x94d\x93\xff\xc4\xf4gF\xc7\x7f" +
	"\xfa\x8dO\x80\xde\x8e\x8a\x7f\xe8\xfcw\xbe\xff\xd4\x85\x0f" +
	"\xfd\x0a\x92M)\x00\xed\xc5\xce7\xb4\x9ft\xa6\x00\xfa" +
	"_\xee\xf4\x11\xd0O\xbc\xf4\xc7wW^\xbe\xff\x0cE" +
	"c,:A1WV\xaeD-y\x0f=\xe2=\x1d" +
	"\x14\xfe\xa0\xfe\x81\xab\xad\xd9\x07\xceA\xa6}A\xf4\xa6" +
	"Uw\xa06\xb6\x8a>3\xba\xea/\x80~\xd3\xc9\x07" +
	"\xb6/;\xbd\xe7\\}&K(zu\xd7m\xa8m" +
	"\xea\xa2\xc7\x81\xae\xaf(\x80~\xcb\xdf7\xde\xb3s\xae" +
	"\xf8\xd5\xfaT\x14\x8ai\xed>\x82\xda\x8anZ|y" +
	"\xf7%@\xff\x95w>\xfc\x87\x9f\xbf\xf6\xaf\x8b\xf5\xd1" +
	"r\xf1\x17\xbb\xa7P{\x95\xa2\xfb_\xe9\xdeH\x8b\x9f" +
	"\xbd`\xfd\xfbc\xa7~\xffu\xc8\xb4\xc7R\x01\xd4\xf6" +
	"\xad\xfd\xa7\xc6\xd6\xd2\xba\x0f\xaf\xdd\x03\xe8\x7f\xea\xdb\x07" +
	"\x9b{\xfa\x7f\xf3\xdd\x86Yxk\x1d\xd4N\xc8\xe8c" +
	"k)\x8bk\x07\xbe\xe4L>w\xf2\xe5\x86\xd1]=" +
	"w\xa36\xd0C\xd1\xbd=\x14]\xd9y\xac\xeb\xed\xe5" +
	"_{\x8d\xa2\x9bb\xd1\xaaL\xb4\xa7\x0f\xb5\xdfQt" +
	"\xff\xeb=\xb26\x1b\xb8s\xa9\xf3\xce\x1f\xbf^\x9fs" +
	"\xff\xdf\xd6\xdd\x81\xda{\xebh\xe1+\xeb\xe6\x01\xfd_" +
	"\xbe1\xfd\xbd\xb9\x97\xee\xfcs\xfdI\xa7h\xb5\xde\xf5" +
	"9\xd4F\xd7\xd3\xe3\xd0zZ\xf8?\x17\xad\x87.x" +
	"\xca\x9b\x8dJ^\xe9\xbd\x03\xb5\x13\xbd\xf4x\xacW\x96" +
	"\xfc\x17\xc6\x9f6\xea\x0f\xbao5\xdc\xe2\xf9\xbe\xd3\xa8" +
	"}\xab\x8f2y\xa1\x8f\xb68\xf3\x85_\xff\xa8\xfbs" +
	"+\xdfm\x18\xad\xf7\xf7\xa1\xc6\xfa\xe5a\xf7_\x02\xff" +
	"\xba\xbfg|\xd7\x98\xe5%\xe6\xaeW\xa6<Q\xe4\xce" +
	":\x83\x95\xad\xf2\xe61K\xa4\xb8%&\x10\xf5Uj" +
	"\x02 \x81\x00\x99\xb7v\x00\xe8\xffPQ\xbf\xaa`\x06" +
	"1\x8b\x04^\xd9\x0c\xa0\xbf\xad\xa2~M\xc1\x8c\xa2d" +
	"Q\x01\xc8\xbc7\x09\xa0_U1\x9f@\x053\xaa\x9a" +
	"E\x15@C\x9c\x04\xc8\xa1\x8a\xf9\x16\x82\x13\x89,&" +
	"\x00\xb4%\xe8\x00\xe4\x9b\x09\xcf\xa2\x82\x98\xccb\x12@" +
	"\xcbPt\xbe\x8d\xe0\x0fRxS2\x8bM\x00\xda2" +
	"\xdc\x01\x90\xbf\x8b\xf0{\x09Om\xcd\xa2\xac6>\x0a" +
	"\x90\xdf@\xf8\x16\xc2\x9b\x87\xb2\xd8\x0c\xa0m\xc2\x1c@" +
	"\xfe>\xc2GPA\xdfa\x87t\x8f;\x15\x00\xc0\x16" +
	"P\xb0\x05p\xd0\xb4K\xac`\xd5~\xfa\xdc\x12\x05Q" +
	"\xd9\xcd@-\xf1\x10,s\xc7\xb5\xad:\xd0\xe1\xd3\xdc" +
	"\xe1\x96\x01\x1d|g\xc12C\xdc\xb0\xad\xe9\x82\xc9-" +
	"P\x0d\x8eKA\xc1\xa5\x80\xfeA^9d;\xa6K" +
	"_\xbe\x1dpBE\x19\x7f;\xa0oqn\xbay\xc3" +
	"\x814+s\x07\x11\x14$\x1a\x14\xdcmv\xa9\\\xe4" +
	"\x80\x87C\xacV0\xf5\xba\x82\x0d\xcb\x1f9\xee\x96\xed" +
	"\x94\xe5r*\\6,\xdc\xe3\xc3\x00\xfaa\x15\xf5\xa7" +
	"c\x85\xfb8\x81GU\xd4\xcf*\x88\xd5\xba}\x96\xea" +
	"vFE\xfd\x8bT6E\x96-s\x9e\x02\xcf\xaa\xa8" +
	"\x7f\x93\x8a\xa6\xca\xa2e^ .<\xaf\xa2\xfe\x03\x05" +
	"\xe7K\xdcu\xd9Lx*\xf3\xcc\x10\x05\xdbrk\x9b" +
	"l\x8b:\x18\xa0\xdcn\xa3\xe3\x997lK\xf0\xc3\"" +
	"zk\xe0\xdc\x13\x9fW\xd9\x9a\x1f\xd6\xde*q\xc1L" +
	"&\x18\x9d_[\xd4\x8b\x00\xb1m\x91s\x19\xa2\x84\xd0" +
	"\xa2Si\x0bO\x85\xad\x01\xd0\x0f\xa8\xa8\xcf\xc6N\x85" +
	"\x13\x9d\x1fQQ/\xc6\xe8\\\xe8\x03\xd0M\x15\xf5r" +
	"\xc4\xe6L\x89^\x9f\x0d\x0e5-*\xe5p\xfb\x83\x82" +
	"93\\\xd4~v\x14\xd9\x14/\xd6~\xa5i\x037" +
	"\xdeb\xe3Ml\x9beb<8c\x00\xda\xc4\x86\xda" +
	"&\xb4!\\\x03\x90\xdfB\xec\xde\x8e\xd1>\xb4Q<" +
	"\x02\x90\x1f!|\x02\xc3\x02k\xe32|;\xc1{1" +
	"\xaa\xb1\xa6\xe30@~\x17\xe1\xfb\xa561\xd0\xe6>" +
	")\xc2\xbd\x84?BxR\x0d\xc4\xf90N\x01\xe4\x0f" +
	"\x10>+\xc5\x99\x08\xc4\xc9e\xbcIxY\x8a3\x19" +
	"\x88\xb3$\xc5Y$\xfc\xb0\x14gS NO\xae#" +
	"\x08\x7f\x92\xf0%\xa9,.\x01\xd0\x1e\x97\xeb\x1c%\xfc" +
	"8\xe1\xb7a\x16o#\x03\x90\xeb<M\xf8)\xc2\x97" +
	"6gq)\x80\xf6i\xb9\xdd\x93\x84\x9fE\x05\xd3S" +
	"\xcc\xe5\xd8\xe6+?{\xf3\xfd\xe1g/\xbfZ\xe3\x88" +
	"a[s\xdcq\x19\x0c\x12A\xc7B\xbd\xa6\x1d\xbb\xc8" +
	"1\x1d\x19\x16 \xa6k\x94\xb4\xc2R\xfa\xc2>\xc8-" +
	"w\x9f\x0b*71\x09\x0a&%-ee\xf6B*" +
	"F\x02?\xd0\xc0\xde\x0a\xa8\x0bA\x06\xe98C\xaa\xf0" +
	".\x06\xa9\x18S\xaa\xe8\x08\x03U\xb0:0/ \xcd" +
	"\x84\xe7b:\xf2\xab \xe5j\xc08\x87\xc1@,\xe1" +
	"\x9b5j%\xae\xa3\xd6\x04\xab\x94\xa8\xd1;\xdc,\xc8" +
	"7\x87\x8cA\xc3s\x98Q!\x9e\xb5\x84b\x19%\xb6" +
	"oUQ\xdf\x15\x13\xcb\x18\xb5\x8b\xed*\xea{\xa3\x16" +
	"\xa2O\x01\xe8\x13*\xea\x07\xfeG\x19<W\xd8%\xee" +
	"\x80\x1a\x95\xc0?\xc4\xdc!\xc3\xf0\x1cH1\xc1\x17t" +
	"\xbb\xc4\x8d\xba\x9d\xe5\xf2q\xea\x0b)&\x18\xa5\xdc\x1d" +
	"Jc\x89\xe4V\xe8+\xa142\x92+\x91\xb1TU" +
	"\xae-\x93F!\x8deU\xdc\xb6V\xc8\xf8N\xc2{" +
	"HJU\xdbZ\x8d\xa7\x01\xf2=\x04\xdf'\xa5\x91\x08" +
	"\xa41 ?{/\xe1[\xe3\xbeu\xbf\xa4\xee\x96P" +
	"b\xa9\xa6@\x1a\xfb\xf0\x93\x00\xf9\xfd\x84\x0b)\x8dT" +
	" \x8d\xc7\xe4:e\xc2\x8fJi4\x07\xd2\xa8`_" +
	"\\2\xbe\xe7rs\x98\x19\x07!\xc5c\x06\xe4\xf0\xc7" +
	"<\xee\x0a\x0e\x83\xe6\xb8m\xc6XE\xe1\x84\x00F\xd8" +
	"4+\x16\xa7h\x89\xc1\x1cg\xae\x1d\x19\xe1t\xc1b" +
	"\x96\xc1G\x90\x096d\x18\xdcE7\xacL\xb5]\x8f" +
	"C\xca6#\x86\x13\xe5\xb6\xd9s\x1c\xd2\x0e9B\x9d" +
	"\xcd\x05\xc6\x9a\xe3\xe8\xdaE\x8f\xd8\x169\xe1\xc2^8" +
	"\xc3-\xee0\xc1!e\x0eE\xdd\x94;\x8e\xed, " +
	"\xb5R\xdf/;D\xce.J\x1bl\x91\xb4\\\xbe\x86" +
	"\x96\xcd\xb4\xe7\x00P\xc9d6\x03\xa4=\x97;>s" +
	"\xdd\x82+\x98\x05(\x06\xdd\x8a+x\xe9\x06\x94\xfbh" +
	"\xc1\x9ap\xec)6U(\x16DE\xea\xa5C\x0a\xe6" +
	"\xff\xd1\x099\xe8\x88\x8a\xfaD\xa4\x93\xf1\xe7\x16\xd5\xc9" +
	"\xbc==\xcd\x9d\x98D\xca\x81J9\x9a\xd5T\xd2\x94" +
	"K8_46\x8f!Cx\xac\xb8\xc7\x13\x86\xad\x96" +
	"\xf8\xad\xaa\x9av\xb0KE}\xff\xcd\xa9z\xfe\x10s" +
	"'X\xc1\\dz\x89\xdaO\xae\x83\x1b\xb6c\xd6\x0d" +
	"\x9e\x94\xe6_U\xd4/\xc7\xd2|g\xb2\xd1\xe0\xf9h" +
	"l\xf0\xc4p\xee$\xff\xbe\xa6b\xbe9\xeemI9" +
	"w&HHmR\xc0J \xe0V\xe9=-\x84\xdf" +
	"%\x05\xac\x06\x02n\xc7\xbb\xaf\xeb\x1b\xa9D \xe0e" +
	"\x12\xcf\x12\xde)\x05\x9c\x0c\x04\xbc\\\xe2a?\xb9\xa9" +
	"f\x18\x82\xe9\xdd,\x1a7;f\x1cf\x92O\xad\xdb" +
	"|\xf4\xc8\xa6\x81\xdf^\xac5\xfd\x1a1\xa0\xc3\x1ca" +
	"\x157\xb4\xa6Fs\x96\xea\xf4F\x8f}\xd1c\xff\xe2" +
	"<\x92\xce\xc3\x84\x87\xae\x9c/\xe5\x89\x0f\x04\xc2\xfa\xc8" +
	"\xb0\x14V\xd7\x0e\x00T3+6\x03`\"\xb3,\x07" +
	"\x90\xb6l\x8b\xcf\x97\xb9e\x16\xac\x19\x9f\x1f\xe6\x86'" +
	"\xb8\x09\x00\x83\xd3\xacP\xe4\xa6o\x16\xdcR\xc1u9" +
	"\xa0\xb9X\xb7\xb7\x8bs\xdc\x1c\xa5\x1e\x82\x95:\x86L" +
	"6\xba\x9a\xd0\x8czY\xc5\\\xac\xcbg\xde\x9f\x8aq" +
	"\xa1\xc6\x90\xa4,yD\x85\xea\x94\xab\xb5\xca\x1e\x1cQ" +
	"\xa1\xd6\xe3\xdbe\xef\x8f\xac\xa2\xd6\xe3W\xe0Sq\xab" +
	"\x08\xef&\xab\xa5\xb5t\x87w\x96\xda\xf8\x13\xbb\xb3\xec" +
	"\xa2^\x1e\xf4\xc7\xba\xa1!\x00\xc7\xcc\xd8\x85\x85\x0e\xad" +
	"\\d\x95\xdd\x90\x8a\xd1\xa3\xf1\xad\xa3\xc4\x841\x9b\xe3" +
	"\x0cR\xf1\xce\xee\xf0\"\x13\xdc\xdc\x86U\xa2\x8d\xa1y" +
	"\xc3\xffE\x9fe\xa5\xa9\xc2\x8cg{\x10\xf3\x01V\x14" +
	"\xdc\xb1\x98\x80ta\x8e\xbb7=\xdaV'\xb2p>" +
	"\x8f\xddZ\xd64\xba\xb5\xf4Uo-\xc7c5=F" +
	"\xdd\xe9I\x15\xf5\x93aI3'\xa8\xf8\xc7U\xd4\xcf" +
	"\xc4n-\xcf\xe4\x00\xf4S*\xea\xcf\xdeP\x8f\x1d\xa2" +
	" \x8a\xd1U\xc6\xf5J%\xe6T\xc2\x13(\xb8\xa4\x83" +
	"9N\xc5\xa8\x9d@\x91\xb9b\xdc\x9d\x19\x02\x14\x0b\x8c" +
	")y\xddnG\x0a\xaea{\x96\xc8q\xc3.\x95\xb8" +
	"e2\xd9\xf3\xa8\xe5\xa1y\xabF\xf2\xe5\x9b7\x12\xa7" +
	"\xfa}4\xb9)sJy\x96XD\xff\xdb\xaal\xc8" +
	"[\xac\xa3\xec\xce\xda\xe2V\xadd\xf2\x16\x07D\xdb1" +
	"\xb9\xf3\x10+\x82\xea\x85\xec\xfeo\x00\x00\x00\xff\xff/" +
	"\x8bp^"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_d61eab82bab79d77,
		Nodes: []uint64{
			0x83b3cc4d458f667e,
			0x943df422f7e3be04,
			0x9a46140df81b5147,
			0x9a4f921948468c06,
			0xa86c764b2337eb0c,
			0xadf3d4cfe127f1cd,
			0xaede905ffa6eab98,
			0xb8da332c086bb68b,
			0xc58caa5a72a15cfc,
			0xd4a91df025854b79,
			0xd9c81720af726530,
			0xe617be76b966e2d5,
			0xea0275ab566ead00,
			0xed73475137e563d3,
			0xf7229628c7d89e67,
		},
		Compressed: true,
	})
}
