// Code generated by capnpc-go. DO NOT EDIT.

package common

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	math "math"
)

type RecordStatus uint16

// RecordStatus_TypeID is the unique identifier for the type RecordStatus.
const RecordStatus_TypeID = 0xa3a4807098b1e4d1

// Values of RecordStatus.
const (
	RecordStatus_active   RecordStatus = 0
	RecordStatus_inactive RecordStatus = 1
	RecordStatus_archived RecordStatus = 2
	RecordStatus_deleted  RecordStatus = 3
	RecordStatus_draft    RecordStatus = 4
)

// String returns the enum's constant name.
func (c RecordStatus) String() string {
	switch c {
	case RecordStatus_active:
		return "active"
	case RecordStatus_inactive:
		return "inactive"
	case RecordStatus_archived:
		return "archived"
	case RecordStatus_deleted:
		return "deleted"
	case RecordStatus_draft:
		return "draft"

	default:
		return ""
	}
}

// RecordStatusFromString returns the enum value with a name,
// or the zero value if there's no such value.
func RecordStatusFromString(c string) RecordStatus {
	switch c {
	case "active":
		return RecordStatus_active
	case "inactive":
		return RecordStatus_inactive
	case "archived":
		return RecordStatus_archived
	case "deleted":
		return RecordStatus_deleted
	case "draft":
		return RecordStatus_draft

	default:
		return 0
	}
}

type RecordStatus_List = capnp.EnumList[RecordStatus]

func NewRecordStatus_List(s *capnp.Segment, sz int32) (RecordStatus_List, error) {
	return capnp.NewEnumList[RecordStatus](s, sz)
}

type ApprovalStatus uint16

// ApprovalStatus_TypeID is the unique identifier for the type ApprovalStatus.
const ApprovalStatus_TypeID = 0xc727137f5fbd7bda

// Values of ApprovalStatus.
const (
	ApprovalStatus_pending     ApprovalStatus = 0
	ApprovalStatus_approved    ApprovalStatus = 1
	ApprovalStatus_rejected    ApprovalStatus = 2
	ApprovalStatus_cancelled   ApprovalStatus = 3
	ApprovalStatus_notRequired ApprovalStatus = 4
)

// String returns the enum's constant name.
func (c ApprovalStatus) String() string {
	switch c {
	case ApprovalStatus_pending:
		return "pending"
	case ApprovalStatus_approved:
		return "approved"
	case ApprovalStatus_rejected:
		return "rejected"
	case ApprovalStatus_cancelled:
		return "cancelled"
	case ApprovalStatus_notRequired:
		return "notRequired"

	default:
		return ""
	}
}

// ApprovalStatusFromString returns the enum value with a name,
// or the zero value if there's no such value.
func ApprovalStatusFromString(c string) ApprovalStatus {
	switch c {
	case "pending":
		return ApprovalStatus_pending
	case "approved":
		return ApprovalStatus_approved
	case "rejected":
		return ApprovalStatus_rejected
	case "cancelled":
		return ApprovalStatus_cancelled
	case "notRequired":
		return ApprovalStatus_notRequired

	default:
		return 0
	}
}

type ApprovalStatus_List = capnp.EnumList[ApprovalStatus]

func NewApprovalStatus_List(s *capnp.Segment, sz int32) (ApprovalStatus_List, error) {
	return capnp.NewEnumList[ApprovalStatus](s, sz)
}

type CurrencyCode uint16

// CurrencyCode_TypeID is the unique identifier for the type CurrencyCode.
const CurrencyCode_TypeID = 0xbc922863cb2ae41a

// Values of CurrencyCode.
const (
	CurrencyCode_bhd CurrencyCode = 0
	CurrencyCode_usd CurrencyCode = 1
	CurrencyCode_eur CurrencyCode = 2
	CurrencyCode_gbp CurrencyCode = 3
	CurrencyCode_sar CurrencyCode = 4
	CurrencyCode_aed CurrencyCode = 5
	CurrencyCode_qar CurrencyCode = 6
	CurrencyCode_omr CurrencyCode = 7
	CurrencyCode_kwd CurrencyCode = 8
	CurrencyCode_inr CurrencyCode = 9
)

// String returns the enum's constant name.
func (c CurrencyCode) String() string {
	switch c {
	case CurrencyCode_bhd:
		return "bhd"
	case CurrencyCode_usd:
		return "usd"
	case CurrencyCode_eur:
		return "eur"
	case CurrencyCode_gbp:
		return "gbp"
	case CurrencyCode_sar:
		return "sar"
	case CurrencyCode_aed:
		return "aed"
	case CurrencyCode_qar:
		return "qar"
	case CurrencyCode_omr:
		return "omr"
	case CurrencyCode_kwd:
		return "kwd"
	case CurrencyCode_inr:
		return "inr"

	default:
		return ""
	}
}

// CurrencyCodeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func CurrencyCodeFromString(c string) CurrencyCode {
	switch c {
	case "bhd":
		return CurrencyCode_bhd
	case "usd":
		return CurrencyCode_usd
	case "eur":
		return CurrencyCode_eur
	case "gbp":
		return CurrencyCode_gbp
	case "sar":
		return CurrencyCode_sar
	case "aed":
		return CurrencyCode_aed
	case "qar":
		return CurrencyCode_qar
	case "omr":
		return CurrencyCode_omr
	case "kwd":
		return CurrencyCode_kwd
	case "inr":
		return CurrencyCode_inr

	default:
		return 0
	}
}

type CurrencyCode_List = capnp.EnumList[CurrencyCode]

func NewCurrencyCode_List(s *capnp.Segment, sz int32) (CurrencyCode_List, error) {
	return capnp.NewEnumList[CurrencyCode](s, sz)
}

type DocumentStatus uint16

// DocumentStatus_TypeID is the unique identifier for the type DocumentStatus.
const DocumentStatus_TypeID = 0x9863e6b79b1d4af7

// Values of DocumentStatus.
const (
	DocumentStatus_draft         DocumentStatus = 0
	DocumentStatus_prepared      DocumentStatus = 1
	DocumentStatus_sent          DocumentStatus = 2
	DocumentStatus_acknowledged  DocumentStatus = 3
	DocumentStatus_issued        DocumentStatus = 4
	DocumentStatus_partiallyPaid DocumentStatus = 5
	DocumentStatus_paid          DocumentStatus = 6
	DocumentStatus_overdue       DocumentStatus = 7
	DocumentStatus_voided        DocumentStatus = 8
	DocumentStatus_cancelled     DocumentStatus = 9
	DocumentStatus_closed        DocumentStatus = 10
)

// String returns the enum's constant name.
func (c DocumentStatus) String() string {
	switch c {
	case DocumentStatus_draft:
		return "draft"
	case DocumentStatus_prepared:
		return "prepared"
	case DocumentStatus_sent:
		return "sent"
	case DocumentStatus_acknowledged:
		return "acknowledged"
	case DocumentStatus_issued:
		return "issued"
	case DocumentStatus_partiallyPaid:
		return "partiallyPaid"
	case DocumentStatus_paid:
		return "paid"
	case DocumentStatus_overdue:
		return "overdue"
	case DocumentStatus_voided:
		return "voided"
	case DocumentStatus_cancelled:
		return "cancelled"
	case DocumentStatus_closed:
		return "closed"

	default:
		return ""
	}
}

// DocumentStatusFromString returns the enum value with a name,
// or the zero value if there's no such value.
func DocumentStatusFromString(c string) DocumentStatus {
	switch c {
	case "draft":
		return DocumentStatus_draft
	case "prepared":
		return DocumentStatus_prepared
	case "sent":
		return DocumentStatus_sent
	case "acknowledged":
		return DocumentStatus_acknowledged
	case "issued":
		return DocumentStatus_issued
	case "partiallyPaid":
		return DocumentStatus_partiallyPaid
	case "paid":
		return DocumentStatus_paid
	case "overdue":
		return DocumentStatus_overdue
	case "voided":
		return DocumentStatus_voided
	case "cancelled":
		return DocumentStatus_cancelled
	case "closed":
		return DocumentStatus_closed

	default:
		return 0
	}
}

type DocumentStatus_List = capnp.EnumList[DocumentStatus]

func NewDocumentStatus_List(s *capnp.Segment, sz int32) (DocumentStatus_List, error) {
	return capnp.NewEnumList[DocumentStatus](s, sz)
}

type SyncState uint16

// SyncState_TypeID is the unique identifier for the type SyncState.
const SyncState_TypeID = 0xe215a92283e9cba1

// Values of SyncState.
const (
	SyncState_localOnly   SyncState = 0
	SyncState_pendingPush SyncState = 1
	SyncState_pendingPull SyncState = 2
	SyncState_synced      SyncState = 3
	SyncState_conflicted  SyncState = 4
	SyncState_failed      SyncState = 5
)

// String returns the enum's constant name.
func (c SyncState) String() string {
	switch c {
	case SyncState_localOnly:
		return "localOnly"
	case SyncState_pendingPush:
		return "pendingPush"
	case SyncState_pendingPull:
		return "pendingPull"
	case SyncState_synced:
		return "synced"
	case SyncState_conflicted:
		return "conflicted"
	case SyncState_failed:
		return "failed"

	default:
		return ""
	}
}

// SyncStateFromString returns the enum value with a name,
// or the zero value if there's no such value.
func SyncStateFromString(c string) SyncState {
	switch c {
	case "localOnly":
		return SyncState_localOnly
	case "pendingPush":
		return SyncState_pendingPush
	case "pendingPull":
		return SyncState_pendingPull
	case "synced":
		return SyncState_synced
	case "conflicted":
		return SyncState_conflicted
	case "failed":
		return SyncState_failed

	default:
		return 0
	}
}

type SyncState_List = capnp.EnumList[SyncState]

func NewSyncState_List(s *capnp.Segment, sz int32) (SyncState_List, error) {
	return capnp.NewEnumList[SyncState](s, sz)
}

type RiskLevel uint16

// RiskLevel_TypeID is the unique identifier for the type RiskLevel.
const RiskLevel_TypeID = 0xc0be48726ee19ebe

// Values of RiskLevel.
const (
	RiskLevel_unknown  RiskLevel = 0
	RiskLevel_low      RiskLevel = 1
	RiskLevel_medium   RiskLevel = 2
	RiskLevel_high     RiskLevel = 3
	RiskLevel_critical RiskLevel = 4
)

// String returns the enum's constant name.
func (c RiskLevel) String() string {
	switch c {
	case RiskLevel_unknown:
		return "unknown"
	case RiskLevel_low:
		return "low"
	case RiskLevel_medium:
		return "medium"
	case RiskLevel_high:
		return "high"
	case RiskLevel_critical:
		return "critical"

	default:
		return ""
	}
}

// RiskLevelFromString returns the enum value with a name,
// or the zero value if there's no such value.
func RiskLevelFromString(c string) RiskLevel {
	switch c {
	case "unknown":
		return RiskLevel_unknown
	case "low":
		return RiskLevel_low
	case "medium":
		return RiskLevel_medium
	case "high":
		return RiskLevel_high
	case "critical":
		return RiskLevel_critical

	default:
		return 0
	}
}

type RiskLevel_List = capnp.EnumList[RiskLevel]

func NewRiskLevel_List(s *capnp.Segment, sz int32) (RiskLevel_List, error) {
	return capnp.NewEnumList[RiskLevel](s, sz)
}

type Priority uint16

// Priority_TypeID is the unique identifier for the type Priority.
const Priority_TypeID = 0xf63580600b4f15c0

// Values of Priority.
const (
	Priority_low    Priority = 0
	Priority_normal Priority = 1
	Priority_high   Priority = 2
	Priority_urgent Priority = 3
)

// String returns the enum's constant name.
func (c Priority) String() string {
	switch c {
	case Priority_low:
		return "low"
	case Priority_normal:
		return "normal"
	case Priority_high:
		return "high"
	case Priority_urgent:
		return "urgent"

	default:
		return ""
	}
}

// PriorityFromString returns the enum value with a name,
// or the zero value if there's no such value.
func PriorityFromString(c string) Priority {
	switch c {
	case "low":
		return Priority_low
	case "normal":
		return Priority_normal
	case "high":
		return Priority_high
	case "urgent":
		return Priority_urgent

	default:
		return 0
	}
}

type Priority_List = capnp.EnumList[Priority]

func NewPriority_List(s *capnp.Segment, sz int32) (Priority_List, error) {
	return capnp.NewEnumList[Priority](s, sz)
}

type Direction uint16

// Direction_TypeID is the unique identifier for the type Direction.
const Direction_TypeID = 0xc87f8c6198d9c003

// Values of Direction.
const (
	Direction_inbound  Direction = 0
	Direction_outbound Direction = 1
)

// String returns the enum's constant name.
func (c Direction) String() string {
	switch c {
	case Direction_inbound:
		return "inbound"
	case Direction_outbound:
		return "outbound"

	default:
		return ""
	}
}

// DirectionFromString returns the enum value with a name,
// or the zero value if there's no such value.
func DirectionFromString(c string) Direction {
	switch c {
	case "inbound":
		return Direction_inbound
	case "outbound":
		return Direction_outbound

	default:
		return 0
	}
}

type Direction_List = capnp.EnumList[Direction]

func NewDirection_List(s *capnp.Segment, sz int32) (Direction_List, error) {
	return capnp.NewEnumList[Direction](s, sz)
}

type Base capnp.Struct

// Base_TypeID is the unique identifier for the type Base.
const Base_TypeID = 0xd1f49c42fdeace02

func NewBase(s *capnp.Segment) (Base, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 6})
	return Base(st), err
}

func NewRootBase(s *capnp.Segment) (Base, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 6})
	return Base(st), err
}

func ReadRootBase(msg *capnp.Message) (Base, error) {
	root, err := msg.Root()
	return Base(root.Struct()), err
}

func (s Base) String() string {
	str, _ := text.Marshal(0xd1f49c42fdeace02, capnp.Struct(s))
	return str
}

func (s Base) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Base) DecodeFromPtr(p capnp.Ptr) Base {
	return Base(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Base) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Base) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Base) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Base) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Base) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Base) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Base) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Base) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Base) CreatedAt() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Base) HasCreatedAt() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Base) CreatedAtBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Base) SetCreatedAt(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Base) UpdatedAt() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Base) HasUpdatedAt() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Base) UpdatedAtBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Base) SetUpdatedAt(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Base) DeletedAt() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Base) HasDeletedAt() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Base) DeletedAtBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Base) SetDeletedAt(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Base) CreatedBy() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s Base) HasCreatedBy() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Base) CreatedByBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s Base) SetCreatedBy(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s Base) UpdatedBy() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s Base) HasUpdatedBy() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Base) UpdatedByBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s Base) SetUpdatedBy(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s Base) Status() RecordStatus {
	return RecordStatus(capnp.Struct(s).Uint16(0))
}

func (s Base) SetStatus(v RecordStatus) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s Base) SyncState() SyncState {
	return SyncState(capnp.Struct(s).Uint16(2))
}

func (s Base) SetSyncState(v SyncState) {
	capnp.Struct(s).SetUint16(2, uint16(v))
}

// Base_List is a list of Base.
type Base_List = capnp.StructList[Base]

// NewBase creates a new list of Base.
func NewBase_List(s *capnp.Segment, sz int32) (Base_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 6}, sz)
	return capnp.StructList[Base](l), err
}

// Base_Future is a wrapper for a Base promised by a client call.
type Base_Future struct{ *capnp.Future }

func (f Base_Future) Struct() (Base, error) {
	p, err := f.Future.Ptr()
	return Base(p.Struct()), err
}

type Money capnp.Struct

// Money_TypeID is the unique identifier for the type Money.
const Money_TypeID = 0xe295f4656e290ef8

func NewMoney(s *capnp.Segment) (Money, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Money(st), err
}

func NewRootMoney(s *capnp.Segment) (Money, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Money(st), err
}

func ReadRootMoney(msg *capnp.Message) (Money, error) {
	root, err := msg.Root()
	return Money(root.Struct()), err
}

func (s Money) String() string {
	str, _ := text.Marshal(0xe295f4656e290ef8, capnp.Struct(s))
	return str
}

func (s Money) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Money) DecodeFromPtr(p capnp.Ptr) Money {
	return Money(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Money) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Money) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Money) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Money) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Money) Amount() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Money) SetAmount(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s Money) Currency() CurrencyCode {
	return CurrencyCode(capnp.Struct(s).Uint16(8))
}

func (s Money) SetCurrency(v CurrencyCode) {
	capnp.Struct(s).SetUint16(8, uint16(v))
}

// Money_List is a list of Money.
type Money_List = capnp.StructList[Money]

// NewMoney creates a new list of Money.
func NewMoney_List(s *capnp.Segment, sz int32) (Money_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[Money](l), err
}

// Money_Future is a wrapper for a Money promised by a client call.
type Money_Future struct{ *capnp.Future }

func (f Money_Future) Struct() (Money, error) {
	p, err := f.Future.Ptr()
	return Money(p.Struct()), err
}

type Percentage capnp.Struct

// Percentage_TypeID is the unique identifier for the type Percentage.
const Percentage_TypeID = 0xad1b5bae2cb770bb

func NewPercentage(s *capnp.Segment) (Percentage, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Percentage(st), err
}

func NewRootPercentage(s *capnp.Segment) (Percentage, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Percentage(st), err
}

func ReadRootPercentage(msg *capnp.Message) (Percentage, error) {
	root, err := msg.Root()
	return Percentage(root.Struct()), err
}

func (s Percentage) String() string {
	str, _ := text.Marshal(0xad1b5bae2cb770bb, capnp.Struct(s))
	return str
}

func (s Percentage) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Percentage) DecodeFromPtr(p capnp.Ptr) Percentage {
	return Percentage(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Percentage) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Percentage) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Percentage) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Percentage) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Percentage) Value() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Percentage) SetValue(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

// Percentage_List is a list of Percentage.
type Percentage_List = capnp.StructList[Percentage]

// NewPercentage creates a new list of Percentage.
func NewPercentage_List(s *capnp.Segment, sz int32) (Percentage_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[Percentage](l), err
}

// Percentage_Future is a wrapper for a Percentage promised by a client call.
type Percentage_Future struct{ *capnp.Future }

func (f Percentage_Future) Struct() (Percentage, error) {
	p, err := f.Future.Ptr()
	return Percentage(p.Struct()), err
}

type DateRange capnp.Struct

// DateRange_TypeID is the unique identifier for the type DateRange.
const DateRange_TypeID = 0xd9b73f9c8ae8eadd

func NewDateRange(s *capnp.Segment) (DateRange, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return DateRange(st), err
}

func NewRootDateRange(s *capnp.Segment) (DateRange, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return DateRange(st), err
}

func ReadRootDateRange(msg *capnp.Message) (DateRange, error) {
	root, err := msg.Root()
	return DateRange(root.Struct()), err
}

func (s DateRange) String() string {
	str, _ := text.Marshal(0xd9b73f9c8ae8eadd, capnp.Struct(s))
	return str
}

func (s DateRange) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (DateRange) DecodeFromPtr(p capnp.Ptr) DateRange {
	return DateRange(capnp.Struct{}.DecodeFromPtr(p))
}

func (s DateRange) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s DateRange) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s DateRange) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s DateRange) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s DateRange) From() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s DateRange) HasFrom() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s DateRange) FromBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s DateRange) SetFrom(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s DateRange) To() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s DateRange) HasTo() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s DateRange) ToBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s DateRange) SetTo(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// DateRange_List is a list of DateRange.
type DateRange_List = capnp.StructList[DateRange]

// NewDateRange creates a new list of DateRange.
func NewDateRange_List(s *capnp.Segment, sz int32) (DateRange_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[DateRange](l), err
}

// DateRange_Future is a wrapper for a DateRange promised by a client call.
type DateRange_Future struct{ *capnp.Future }

func (f DateRange_Future) Struct() (DateRange, error) {
	p, err := f.Future.Ptr()
	return DateRange(p.Struct()), err
}

type Address capnp.Struct

// Address_TypeID is the unique identifier for the type Address.
const Address_TypeID = 0xc7a54641a37dffdf

func NewAddress(s *capnp.Segment) (Address, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 6})
	return Address(st), err
}

func NewRootAddress(s *capnp.Segment) (Address, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 6})
	return Address(st), err
}

func ReadRootAddress(msg *capnp.Message) (Address, error) {
	root, err := msg.Root()
	return Address(root.Struct()), err
}

func (s Address) String() string {
	str, _ := text.Marshal(0xc7a54641a37dffdf, capnp.Struct(s))
	return str
}

func (s Address) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Address) DecodeFromPtr(p capnp.Ptr) Address {
	return Address(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Address) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Address) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Address) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Address) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Address) Line1() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Address) HasLine1() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Address) Line1Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Address) SetLine1(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Address) Line2() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Address) HasLine2() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Address) Line2Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Address) SetLine2(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Address) City() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Address) HasCity() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Address) CityBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Address) SetCity(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Address) Region() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Address) HasRegion() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Address) RegionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Address) SetRegion(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Address) PostalCode() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s Address) HasPostalCode() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Address) PostalCodeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s Address) SetPostalCode(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s Address) Country() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s Address) HasCountry() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Address) CountryBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s Address) SetCountry(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

// Address_List is a list of Address.
type Address_List = capnp.StructList[Address]

// NewAddress creates a new list of Address.
func NewAddress_List(s *capnp.Segment, sz int32) (Address_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 6}, sz)
	return capnp.StructList[Address](l), err
}

// Address_Future is a wrapper for a Address promised by a client call.
type Address_Future struct{ *capnp.Future }

func (f Address_Future) Struct() (Address, error) {
	p, err := f.Future.Ptr()
	return Address(p.Struct()), err
}

type ContactInfo capnp.Struct

// ContactInfo_TypeID is the unique identifier for the type ContactInfo.
const ContactInfo_TypeID = 0xfdcf1d56fd90ff19

func NewContactInfo(s *capnp.Segment) (ContactInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 5})
	return ContactInfo(st), err
}

func NewRootContactInfo(s *capnp.Segment) (ContactInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 5})
	return ContactInfo(st), err
}

func ReadRootContactInfo(msg *capnp.Message) (ContactInfo, error) {
	root, err := msg.Root()
	return ContactInfo(root.Struct()), err
}

func (s ContactInfo) String() string {
	str, _ := text.Marshal(0xfdcf1d56fd90ff19, capnp.Struct(s))
	return str
}

func (s ContactInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ContactInfo) DecodeFromPtr(p capnp.Ptr) ContactInfo {
	return ContactInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ContactInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ContactInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ContactInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ContactInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ContactInfo) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ContactInfo) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ContactInfo) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ContactInfo) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ContactInfo) Email() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ContactInfo) HasEmail() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ContactInfo) EmailBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ContactInfo) SetEmail(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ContactInfo) Phone() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ContactInfo) HasPhone() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ContactInfo) PhoneBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ContactInfo) SetPhone(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s ContactInfo) Mobile() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s ContactInfo) HasMobile() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ContactInfo) MobileBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s ContactInfo) SetMobile(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s ContactInfo) Designation() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s ContactInfo) HasDesignation() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s ContactInfo) DesignationBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s ContactInfo) SetDesignation(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

// ContactInfo_List is a list of ContactInfo.
type ContactInfo_List = capnp.StructList[ContactInfo]

// NewContactInfo creates a new list of ContactInfo.
func NewContactInfo_List(s *capnp.Segment, sz int32) (ContactInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 5}, sz)
	return capnp.StructList[ContactInfo](l), err
}

// ContactInfo_Future is a wrapper for a ContactInfo promised by a client call.
type ContactInfo_Future struct{ *capnp.Future }

func (f ContactInfo_Future) Struct() (ContactInfo, error) {
	p, err := f.Future.Ptr()
	return ContactInfo(p.Struct()), err
}

type AttachmentRef capnp.Struct

// AttachmentRef_TypeID is the unique identifier for the type AttachmentRef.
const AttachmentRef_TypeID = 0xed0a71dcece75ea7

func NewAttachmentRef(s *capnp.Segment) (AttachmentRef, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5})
	return AttachmentRef(st), err
}

func NewRootAttachmentRef(s *capnp.Segment) (AttachmentRef, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5})
	return AttachmentRef(st), err
}

func ReadRootAttachmentRef(msg *capnp.Message) (AttachmentRef, error) {
	root, err := msg.Root()
	return AttachmentRef(root.Struct()), err
}

func (s AttachmentRef) String() string {
	str, _ := text.Marshal(0xed0a71dcece75ea7, capnp.Struct(s))
	return str
}

func (s AttachmentRef) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AttachmentRef) DecodeFromPtr(p capnp.Ptr) AttachmentRef {
	return AttachmentRef(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AttachmentRef) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AttachmentRef) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AttachmentRef) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AttachmentRef) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AttachmentRef) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s AttachmentRef) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AttachmentRef) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s AttachmentRef) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s AttachmentRef) FileName() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s AttachmentRef) HasFileName() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s AttachmentRef) FileNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s AttachmentRef) SetFileName(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s AttachmentRef) MimeType() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s AttachmentRef) HasMimeType() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s AttachmentRef) MimeTypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s AttachmentRef) SetMimeType(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s AttachmentRef) Path() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s AttachmentRef) HasPath() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s AttachmentRef) PathBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s AttachmentRef) SetPath(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s AttachmentRef) Sha256() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s AttachmentRef) HasSha256() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s AttachmentRef) Sha256Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s AttachmentRef) SetSha256(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s AttachmentRef) SizeBytes() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s AttachmentRef) SetSizeBytes(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

// AttachmentRef_List is a list of AttachmentRef.
type AttachmentRef_List = capnp.StructList[AttachmentRef]

// NewAttachmentRef creates a new list of AttachmentRef.
func NewAttachmentRef_List(s *capnp.Segment, sz int32) (AttachmentRef_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5}, sz)
	return capnp.StructList[AttachmentRef](l), err
}

// AttachmentRef_Future is a wrapper for a AttachmentRef promised by a client call.
type AttachmentRef_Future struct{ *capnp.Future }

func (f AttachmentRef_Future) Struct() (AttachmentRef, error) {
	p, err := f.Future.Ptr()
	return AttachmentRef(p.Struct()), err
}

type KeyValue capnp.Struct

// KeyValue_TypeID is the unique identifier for the type KeyValue.
const KeyValue_TypeID = 0xbf2a6103977e9a35

func NewKeyValue(s *capnp.Segment) (KeyValue, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return KeyValue(st), err
}

func NewRootKeyValue(s *capnp.Segment) (KeyValue, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return KeyValue(st), err
}

func ReadRootKeyValue(msg *capnp.Message) (KeyValue, error) {
	root, err := msg.Root()
	return KeyValue(root.Struct()), err
}

func (s KeyValue) String() string {
	str, _ := text.Marshal(0xbf2a6103977e9a35, capnp.Struct(s))
	return str
}

func (s KeyValue) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (KeyValue) DecodeFromPtr(p capnp.Ptr) KeyValue {
	return KeyValue(capnp.Struct{}.DecodeFromPtr(p))
}

func (s KeyValue) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s KeyValue) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s KeyValue) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s KeyValue) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s KeyValue) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s KeyValue) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s KeyValue) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s KeyValue) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s KeyValue) Value() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s KeyValue) HasValue() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s KeyValue) ValueBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s KeyValue) SetValue(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// KeyValue_List is a list of KeyValue.
type KeyValue_List = capnp.StructList[KeyValue]

// NewKeyValue creates a new list of KeyValue.
func NewKeyValue_List(s *capnp.Segment, sz int32) (KeyValue_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[KeyValue](l), err
}

// KeyValue_Future is a wrapper for a KeyValue promised by a client call.
type KeyValue_Future struct{ *capnp.Future }

func (f KeyValue_Future) Struct() (KeyValue, error) {
	p, err := f.Future.Ptr()
	return KeyValue(p.Struct()), err
}

type ValidationIssue capnp.Struct

// ValidationIssue_TypeID is the unique identifier for the type ValidationIssue.
const ValidationIssue_TypeID = 0x80de66d806507ff9

func NewValidationIssue(s *capnp.Segment) (ValidationIssue, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return ValidationIssue(st), err
}

func NewRootValidationIssue(s *capnp.Segment) (ValidationIssue, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return ValidationIssue(st), err
}

func ReadRootValidationIssue(msg *capnp.Message) (ValidationIssue, error) {
	root, err := msg.Root()
	return ValidationIssue(root.Struct()), err
}

func (s ValidationIssue) String() string {
	str, _ := text.Marshal(0x80de66d806507ff9, capnp.Struct(s))
	return str
}

func (s ValidationIssue) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ValidationIssue) DecodeFromPtr(p capnp.Ptr) ValidationIssue {
	return ValidationIssue(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ValidationIssue) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ValidationIssue) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ValidationIssue) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ValidationIssue) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ValidationIssue) Field() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ValidationIssue) HasField() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ValidationIssue) FieldBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ValidationIssue) SetField(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ValidationIssue) Code() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ValidationIssue) HasCode() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ValidationIssue) CodeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ValidationIssue) SetCode(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ValidationIssue) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ValidationIssue) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ValidationIssue) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ValidationIssue) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s ValidationIssue) Severity() RiskLevel {
	return RiskLevel(capnp.Struct(s).Uint16(0))
}

func (s ValidationIssue) SetSeverity(v RiskLevel) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

// ValidationIssue_List is a list of ValidationIssue.
type ValidationIssue_List = capnp.StructList[ValidationIssue]

// NewValidationIssue creates a new list of ValidationIssue.
func NewValidationIssue_List(s *capnp.Segment, sz int32) (ValidationIssue_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[ValidationIssue](l), err
}

// ValidationIssue_Future is a wrapper for a ValidationIssue promised by a client call.
type ValidationIssue_Future struct{ *capnp.Future }

func (f ValidationIssue_Future) Struct() (ValidationIssue, error) {
	p, err := f.Future.Ptr()
	return ValidationIssue(p.Struct()), err
}

type PageRequest capnp.Struct

// PageRequest_TypeID is the unique identifier for the type PageRequest.
const PageRequest_TypeID = 0xf1b71a429a82cc5e

func NewPageRequest(s *capnp.Segment) (PageRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return PageRequest(st), err
}

func NewRootPageRequest(s *capnp.Segment) (PageRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return PageRequest(st), err
}

func ReadRootPageRequest(msg *capnp.Message) (PageRequest, error) {
	root, err := msg.Root()
	return PageRequest(root.Struct()), err
}

func (s PageRequest) String() string {
	str, _ := text.Marshal(0xf1b71a429a82cc5e, capnp.Struct(s))
	return str
}

func (s PageRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PageRequest) DecodeFromPtr(p capnp.Ptr) PageRequest {
	return PageRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PageRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PageRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PageRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PageRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PageRequest) Page() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s PageRequest) SetPage(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s PageRequest) PageSize() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s PageRequest) SetPageSize(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s PageRequest) SortBy() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s PageRequest) HasSortBy() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PageRequest) SortByBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s PageRequest) SetSortBy(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s PageRequest) Descending() bool {
	return capnp.Struct(s).Bit(64)
}

func (s PageRequest) SetDescending(v bool) {
	capnp.Struct(s).SetBit(64, v)
}

// PageRequest_List is a list of PageRequest.
type PageRequest_List = capnp.StructList[PageRequest]

// NewPageRequest creates a new list of PageRequest.
func NewPageRequest_List(s *capnp.Segment, sz int32) (PageRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[PageRequest](l), err
}

// PageRequest_Future is a wrapper for a PageRequest promised by a client call.
type PageRequest_Future struct{ *capnp.Future }

func (f PageRequest_Future) Struct() (PageRequest, error) {
	p, err := f.Future.Ptr()
	return PageRequest(p.Struct()), err
}

type PageInfo capnp.Struct

// PageInfo_TypeID is the unique identifier for the type PageInfo.
const PageInfo_TypeID = 0xbce625e92081b792

func NewPageInfo(s *capnp.Segment) (PageInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return PageInfo(st), err
}

func NewRootPageInfo(s *capnp.Segment) (PageInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return PageInfo(st), err
}

func ReadRootPageInfo(msg *capnp.Message) (PageInfo, error) {
	root, err := msg.Root()
	return PageInfo(root.Struct()), err
}

func (s PageInfo) String() string {
	str, _ := text.Marshal(0xbce625e92081b792, capnp.Struct(s))
	return str
}

func (s PageInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PageInfo) DecodeFromPtr(p capnp.Ptr) PageInfo {
	return PageInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PageInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PageInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PageInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PageInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PageInfo) Page() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s PageInfo) SetPage(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s PageInfo) PageSize() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s PageInfo) SetPageSize(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s PageInfo) TotalItems() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s PageInfo) SetTotalItems(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s PageInfo) TotalPages() uint32 {
	return capnp.Struct(s).Uint32(16)
}

func (s PageInfo) SetTotalPages(v uint32) {
	capnp.Struct(s).SetUint32(16, v)
}

// PageInfo_List is a list of PageInfo.
type PageInfo_List = capnp.StructList[PageInfo]

// NewPageInfo creates a new list of PageInfo.
func NewPageInfo_List(s *capnp.Segment, sz int32) (PageInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0}, sz)
	return capnp.StructList[PageInfo](l), err
}

// PageInfo_Future is a wrapper for a PageInfo promised by a client call.
type PageInfo_Future struct{ *capnp.Future }

func (f PageInfo_Future) Struct() (PageInfo, error) {
	p, err := f.Future.Ptr()
	return PageInfo(p.Struct()), err
}

const schema_b7ac2215649a020c = "x\xda\x94Vkl\x1cW\xf5?g\xee\xda\x9bW\xff" +
	"\xfb\x1f\xc6\x96\x1a\xa3\xc8\xc9\xc6\x0e^\xdb\x81&!@" +
	"V\xaa\xb6vZD\xcc\xa3\xbek\x14\x94BJ\xafg" +
	"\xaew\xa7\x99\x97\xe7\xe1tK\x83\x13h$@\xa9T" +
	"*\xaa\xa6!A\xb5\x9a\x88FJ\x80HEF\xa2-" +
	"\xe1S@mAA \xb5U\xc3\xa3J\x1f\x89\x1a\x09" +
	"\xa2\x94\xa6\x11\xd1\xa0{w=;^\xdb\x14\xb4_f" +
	"\xce\x9e\xb9\xf7\xfc\x1e\xf7\x9c{\xdb\xc0\xaa;2\x9bn" +
	"\xf9\xe9\x10(c\xffR\xda\xda\xe3\x0f\xa6G\xdb_\x99" +
	"\xf8\xf3~\xa0\x9d\x88\xf1*\xe5\x88\xd1\x99?5\x0bm" +
	"$\x0b\xb0\xe5\xf9\xb5\xfd\xa8\xbd\xbc6\x0b\xa0\xfdv\xed" +
	"\xdb\x80\xf1\xfb#k~8\xfb\x96~\x18\xd4N\xa5\x99" +
	"\x0c\xb8ef]\x1e\xb53\xeb\xc4G\xa7\xd7\xe5\x100" +
	">\x7f\xf1\xccao\xff\xf1\xa7\x17\xa4\xd2\xfcGPc" +
	"y\xb1\xe8\xee\xfc4`\xfcKov\xf0'_\xfd\xe8" +
	"\xe9\x96\x122b\xb1'\xf3\x0aj'd\xf2L\xbe\x04" +
	"\x18w]\xec\x7fQ\xef{\xec\xb9\x05\xcb\xfeZ,{" +
	"^f\xbe\x9c\x7f\x1f0~l\xf6\xc0\xdaK\xbdo=" +
	"'\x96%\xf3\x97\xd5\xe8\xfa\xab\xda\xee\xf5\xe2i\xd7z" +
	"\x81k\xeb\x91o>AX\xff\xaf@\xedL\x93\xa0\x88" +
	"\x8cm=W\xb5\xbbz\xc4\xd3P\xcf^\xc0\xf8\x85\x1f" +
	"\xfd\xcd\xf1?\xf7\xc2\xd9\xd6\x0a\xb4c=7\xb4\x932" +
	"\xf1D\x8f\xc0\xf5\xda7\x9e\xff\xfa\xb4\xf6\xb1s\x0bJ" +
	"\xbd\xd0\x93G\xed\x8a\xcc\xbc$3\xff\x12\xef{z\xe8" +
	"\xb3'\xce\xb5l\xdf.26\xf6^\xd6\xb6\xf5\x0a." +
	"\xb6\xf6~E\x10K\xce\xbez\x98\x1d\x9a\xfe\xcd\x82\xfd" +
	"\x0fn\xb8\xa1}\x7f\x83\xf8\xe6\x91\x0d\x9f\x06\x8c\x95\xdf" +
	"]\xbe9|\xf4\xda\xf9Vi\xe5\xb2\x8fo\xf8\x836" +
	"#\x92\xb7\x1c\xdbpN,{\xe1\xf2;\xdf;Z\x9a" +
	"}u1\x0aj}7\xb4\x83}\xe2\xe9@\x9f\xa0`" +
	"\xe6\xc5K\xdf\xce\x9f\xec|cA\x09\x17\xfanh\x97" +
	"d\xe2\x9b}O\x00\xc6\xd7\xff\xaf\xe0\xf0k\x8f\xbf!" +
	"JPZ4\xd8VxM\xbb\xab y-\x88E\x7f" +
	"|\xef\xdb\xef\xbe>\xb9\xe2Jk\xb9m\xa2\xc8\x99B" +
	"\x17jg\x0a\xd2_\x05I\xc3\xbd/}\xeb\xc8p\xd7" +
	"\xec?Z\x96nC\x91\xd36\xb0\x02\xb5\xce\x01\xb1\xb8" +
	": \x04>\xdby\xf7\xca\xfb\xf6o\xfd\xe7\x82\x8a\xaf" +
	"\x0c\\\xd5>\x90\x89\xef\x0dT\x00\xe3\xd5\xf1\xa37w" +
	"\xae\xf9\xfd\xcd\x16\x1ad\x11\xab\x07W\xa0V\x18\x14\x8f" +
	"\xbd\x83\xdd\x08\xf1\xbc\x1f\x8f\x03\xbd\xcam\x16|\x82\xe8" +
	"\xaem\xbb\xce\xc7u\xe69^q'\xb3L\x83\x85\xa6" +
	"\xeb\xec\xc8\x05A\xc4G\x11\xe9\xff\x93\x0c@\x06\x01T" +
	"\xb6\x19\x80~\x8d \xad*\xa8\"v\xa0\x08\xf2~\x00" +
	"z\x1fAj)\xa8*J\x07*\x00\xaa9\x0c@\x0d" +
	"\x82\xd4S\x10I\x07\x12\x00\xd5\x1e\x01\xa0\x16A\xfa\x80" +
	"\x82\xdd\x13&\xb7\x0c\\\x05\x0a\xae\x02\xcc\xe9\xae\xc1\xe7" +
	"^\xa6m\x1e\x04\xac\x92\xbc\xc7\x01\x9f\xe2\xbe\x19\xd6\x00" +
	"\x00sMG\x03bN\xfc\xbb(\x8e;]=\xb2\xb9" +
	"\x13\x8e\x85,\x1bF\x81\x801(\x0b\xdb\xb7Y|\xa8" +
	"F#\x00\xa8\xa8\x93\xfd\x00HT\xf3~\x00\xcc\xa8\xbc" +
	"\x08\x80m\xean\x1f\x00\xdb\xd5]\xe2\xbf\xacJ\x87\x01" +
	"p\x99\xbaC\xfc\xb7\\\x1d*\x03\xe0\x0a\xf5\xf6\"@" +
	"\xb7\xe1\xb3\x890\xf6|\xee1\x9f\x1b\x00\x90\x0b\xb8\x13" +
	"\xc6L\xdf\xe3\xb8{-\x0e9\xa3\xc2\x8d\x92)h4" +
	"b\x8f\xf9\xa1\xc9,\x0b\xbak\xa3\xcc4r\x1e3\x8d" +
	"iw\x8a\xfbF\xc4KS\xaeip#\xd6\x99\xa3s" +
	"\xcb\xe2\x80FI\xb7\xdc\x80\x1bK\xa0+s\xdd\xf5\x8d" +
	"\xb1\x90\x85\x11Jlu\xd2\xb7\x16%\xb6\x8dul\x85" +
	"\x11\x89\xadwXb[\xb3\x19\xa0\xc4\xf4\xd0\x9c\xe2\xb1" +
	"\xe9\xd4\x1f\x00 f\xbe^5\xa7d\xf9\xd3\x06\xb7x" +
	"\xc8\x8d\x06\xb0\xc5\xb7\x1e\xe5\xbe\xce\x9d\x90U8\x88\x8d" +
	"3\x897n\x11\xdeXF\x90v(\xd8=\xc5\xac\x88" +
	"\xe3JPp\xe5\x92\x12m\x8f|\x9f;zm\xbbk" +
	"\xa0\xf4Y\x9f\x041\x99\x97 \xcc\xbc\x04\xc1\xf2\x12\xc4" +
	"\xae\xbc\x04A\xf3R\xa0\x1dy)\xd0P^\x0a\xb4-" +
	"/\x05\xda\x94\x97\x02\x15\xf2\x00\xd9\xf1\xaa\x91\x8d\x02#" +
	"\xcb#?[\x19\xf7\xb2\x01\xf3\xb3\x8c\x1b\xd9I\xe6g" +
	"]\xdb\xcf\xee\xd9kdM\xc7O\x0aS\xe6Cd\x95" +
	"n\xbe\xc3\x99p[\xcc\xdf\xbf\x98\xf9G\x9a>W\x15" +
	"\xac\xeb`\xdf\xd34\xbaJ2u\xf7G\"\x18\x12\xa4" +
	"\xfb\x15\xccy\xc2\xdf\xcb@\xc1e\x80\xb1x\x193\x1f" +
	"\x14r$\xb1\xd0\x0d\x99\xb5#\xe4@\xec\x00\x97\x83\x82" +
	"\xcb\xe7\x82\xa3\xac\x02\x84\x07I\xe6\xe2\x18>\xcfk\xdd" +
	";\x85\x08\x02\xc3\xb2\x04\x83`\x87\xf6\x10\xa4\xb7\xa50" +
	"l\x14\xca\xf5\x11\xa4\x9fT0\xbb\x87\xd7\xe6\x0e^C" +
	"\xc5\xe4\x18.\xbaQ\xd9\x0cJ{\xbe\xc0\xa7\xb8\x95\xf2" +
	"\xe1p\xdd\x87u\x09{\x8bR\xc25\xfdR\xc2\xce\x11" +
	"\x80\xe9\xc8\x11G\xc4\xc9Z\xee\xde\x92\xcd\x0d3\xb2s" +
	"U\xb3R\x8du\xdf\x0cM\x9dY\xc2\x98\x8b\x9bf\xc8" +
	"\xf3|w\x8aY\xa9s=\x7f\xcf\xf9\xde/\xcb=\xd7" +
	"\x8d\x03L{\xdc1L\xa7\x123\xb9\x824|\xec\xf3" +
	"\xfb\xb9\x1e\xd6\x9fS\x87/v\xdc\xb0\xcc'#\x13\xb2" +
	"~\xea\x0c\xce\x07>d\x189\x9f\x07\xb2\x84[\x13\x82" +
	"\x9f\x14\\\xfe\x80 }*E\xf01\x11<L\x90\x1e" +
	"Ou\xc8\x19a\xa7\xa3\x04\xe93\xc2$\x8d\x16y\xa2" +
	"\x08@\x9f\"HO)\xa8f2\x1d\x98\x01PO\x0a" +
	"\xe7<C\x90>\xab\xa0\xda\xd6\xd6\x81m\x00\xea\x19\xd1" +
	"`O\x11\xa4\xbfP\xb0\xdb2\x1d\xbe)\x91M\xbcm" +
	"n\xb6V3L\x14-\xf9\xbcb\xbaN\"\xa9\xe7\x06" +
	"!\xb3\xb6\xbb@R\xedWw#'\xf4k\x1f\xa2\xfb" +
	"\x9d\xa6_\xe2\xba\x18\x14\xd2a\x12\x92Z\xd7`\xb9\x90" +
	"\xd8t\xc6\xdd\xc81b7\x0a\xe5CZ\xd2\xf9+\x0d" +
	"\xb3\xa0~\xfe\xd7&,\x9e\xef\x02\xa0/\x11\xa4\xaf\xa4" +
	"X\xfcS\x19\x80\xfe\x91 \xfdk\x8a\xc5\x0b\"\xf8:" +
	"A\xfaN\x8a\xc57E\xf0\"A\xfa\xf7\x14\x8bWD" +
	"\xf0]\x82\xf4z\x8a\xc5\xf7D\xf0\x1a\xc12*\x88\xed" +
	"\x1d\xd8\x0e\xa0\xde\x14\x1a\\'8\x96A\x05\xd5,v" +
	"\x88!\xad!\x96\x01\xcaHpl\x15*H\xccdv" +
	"\xc5\xba\xcfY\xc8\x8d!\xc00\x89E\x9e\xb1 \xd6\xe8" +
	"\xae\xf3b\x8do\x87\x01k\xad\xdf\xa6c\xa5@\xb4\xfa" +
	"\x00s\xcd\x8b\xea\xdc\xf4\xab9\xba\x98\x03\x80\x1cs\xcd" +
	"\xabN\xcbll\x91\x8e\x85%^fN\xa5\xb59\xf4" +
	"/\xd6\x1c\xba\x9a\xcd!7\xe1\xbb\xf6\\M$t?" +
	"\xc4\"c5\xa7$\x8b\x93\xfb\xdc*\xf5\x92\xf3\x13\xd5" +
	"\xdb\xc7\xe51\xdd6.\x8f\xa9\x9c[\x19u\xe3=\xb2" +
	"\xbb\x17\x8a\x00\xb1\xe5\xea\xcc\xba\xdb\xb1\x00kq\xe3\xe4" +
	"\x8eB6\x0a\xaa\xe97\xcb*\x09\xfcbr\xba\xce\x84" +
	"e\xea!\x10n\x94&\x98i-yl\xbf\xe8:\x84" +
	"\xd7Z\x80\x17\xd3\xc03\x0d\xe0\xa2\xb3\x0f\x12\xa4\x9fQ" +
	"\xb0\xc4lq(\x92\x81\xa67FW\xfdF\x92\xdc\xf2" +
	"\xff\xe3\x8dd(\x0c\x99^\x15w\x922\xe1\x13-]" +
	"\xa3k\xb1\xae1\x92j\x10s~?!\x82\xc7\x09\xd2" +
	"\x9f\xa5\xfc~\xba?\xd5 \xe6\xfc~\xa6\xd8l\x10\xd8" +
	"\xb0\xfb\xcf\x85\xdd\x9f%H\xcf\xce\xb7\xf0\x84i\xf1/" +
	"1[N\xa0\xb9\x98m\xda\xfc\xcb5/\x1d\xcby," +
	"\xac6=Ye\x9b\xb7~\xaa\xe9\x01\xf3A>\\\x0b" +
	"9`s`-q\x85`\x15.\xda+\x0fB\x80\xff" +
	"q\xc6b\x83\x07[\xa0\xab\x12\xa4\xa1\xe0\xe1\x8e:\x0f" +
	"\x93\xa2Qz\x04\xe9C\xff\xc5\x88-\x05\xae\x1f\x0e\xd7" +
	"R\xc73\xd0\x85\xb5\x808\x15DP\x10\x974\xf6\xa8" +
	"ov\xbb\xe2F*\x8b\x97\xf5\x14\xea\xb7\x96uE\xe9" +
	"\xeb\xd5\xf5k\xa5Z\x04\x903\xceq}\x9bYr\xc6" +
	"\x95\"\xbf\"n\x89K\xdc\x89\\'dz(.\x1f" +
	"uj:\x12j\xf6\x09j\x1e H\x1fNQs@" +
	"L\x96\x87\x08\xd2\xef\xa4<rP\x04\xf7\x13\xa4\x87R" +
	"\x1e\xf9\xae \xeca\x82\xf4\xd1\x94G\x1e\x19\x07\xa0\x87" +
	"\x08\xd2\xc3\x0a\xe6\x1cf'C\xa0\x9b\xdb\xcc\xb4\x927" +
	"\xaf\xea:\xc9\x7f%\xdb\x1d7-\x9e&\xce\xac8," +
	"\x84lj\xb4\xfc;\x00\x00\xff\xff\x87\xe3\xcc9"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_b7ac2215649a020c,
		Nodes: []uint64{
			0x80de66d806507ff9,
			0x9863e6b79b1d4af7,
			0xa3a4807098b1e4d1,
			0xad1b5bae2cb770bb,
			0xbc922863cb2ae41a,
			0xbce625e92081b792,
			0xbf2a6103977e9a35,
			0xc0be48726ee19ebe,
			0xc727137f5fbd7bda,
			0xc7a54641a37dffdf,
			0xc87f8c6198d9c003,
			0xd1f49c42fdeace02,
			0xd9b73f9c8ae8eadd,
			0xe215a92283e9cba1,
			0xe295f4656e290ef8,
			0xed0a71dcece75ea7,
			0xf1b71a429a82cc5e,
			0xf63580600b4f15c0,
			0xfdcf1d56fd90ff19,
		},
		Compressed: true,
	})
}
