// Code generated by capnpc-go. DO NOT EDIT.

package infra

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	common "ph_holdings_app/schemas/go/common"
)

type DeviceStatus uint16

// DeviceStatus_TypeID is the unique identifier for the type DeviceStatus.
const DeviceStatus_TypeID = 0x9b6c08f7cb50660f

// Values of DeviceStatus.
const (
	DeviceStatus_firstSetup DeviceStatus = 0
	DeviceStatus_pending    DeviceStatus = 1
	DeviceStatus_approved   DeviceStatus = 2
	DeviceStatus_blocked    DeviceStatus = 3
	DeviceStatus_revoked    DeviceStatus = 4
)

// String returns the enum's constant name.
func (c DeviceStatus) String() string {
	switch c {
	case DeviceStatus_firstSetup:
		return "firstSetup"
	case DeviceStatus_pending:
		return "pending"
	case DeviceStatus_approved:
		return "approved"
	case DeviceStatus_blocked:
		return "blocked"
	case DeviceStatus_revoked:
		return "revoked"

	default:
		return ""
	}
}

// DeviceStatusFromString returns the enum value with a name,
// or the zero value if there's no such value.
func DeviceStatusFromString(c string) DeviceStatus {
	switch c {
	case "firstSetup":
		return DeviceStatus_firstSetup
	case "pending":
		return DeviceStatus_pending
	case "approved":
		return DeviceStatus_approved
	case "blocked":
		return DeviceStatus_blocked
	case "revoked":
		return DeviceStatus_revoked

	default:
		return 0
	}
}

type DeviceStatus_List = capnp.EnumList[DeviceStatus]

func NewDeviceStatus_List(s *capnp.Segment, sz int32) (DeviceStatus_List, error) {
	return capnp.NewEnumList[DeviceStatus](s, sz)
}

type JobStatus uint16

// JobStatus_TypeID is the unique identifier for the type JobStatus.
const JobStatus_TypeID = 0xa99ef5230258c2d5

// Values of JobStatus.
const (
	JobStatus_pending   JobStatus = 0
	JobStatus_running   JobStatus = 1
	JobStatus_completed JobStatus = 2
	JobStatus_failed    JobStatus = 3
	JobStatus_cancelled JobStatus = 4
)

// String returns the enum's constant name.
func (c JobStatus) String() string {
	switch c {
	case JobStatus_pending:
		return "pending"
	case JobStatus_running:
		return "running"
	case JobStatus_completed:
		return "completed"
	case JobStatus_failed:
		return "failed"
	case JobStatus_cancelled:
		return "cancelled"

	default:
		return ""
	}
}

// JobStatusFromString returns the enum value with a name,
// or the zero value if there's no such value.
func JobStatusFromString(c string) JobStatus {
	switch c {
	case "pending":
		return JobStatus_pending
	case "running":
		return JobStatus_running
	case "completed":
		return JobStatus_completed
	case "failed":
		return JobStatus_failed
	case "cancelled":
		return JobStatus_cancelled

	default:
		return 0
	}
}

type JobStatus_List = capnp.EnumList[JobStatus]

func NewJobStatus_List(s *capnp.Segment, sz int32) (JobStatus_List, error) {
	return capnp.NewEnumList[JobStatus](s, sz)
}

type Setting capnp.Struct

// Setting_TypeID is the unique identifier for the type Setting.
const Setting_TypeID = 0xfb0757ea10693769

func NewSetting(s *capnp.Segment) (Setting, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5})
	return Setting(st), err
}

func NewRootSetting(s *capnp.Segment) (Setting, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5})
	return Setting(st), err
}

func ReadRootSetting(msg *capnp.Message) (Setting, error) {
	root, err := msg.Root()
	return Setting(root.Struct()), err
}

func (s Setting) String() string {
	str, _ := text.Marshal(0xfb0757ea10693769, capnp.Struct(s))
	return str
}

func (s Setting) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Setting) DecodeFromPtr(p capnp.Ptr) Setting {
	return Setting(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Setting) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Setting) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Setting) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Setting) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Setting) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s Setting) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Setting) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s Setting) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Setting) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Setting) HasKey() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Setting) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Setting) SetKey(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Setting) Value() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Setting) HasValue() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Setting) ValueBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Setting) SetValue(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Setting) Category() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Setting) HasCategory() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Setting) CategoryBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Setting) SetCategory(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Setting) Description() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s Setting) HasDescription() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Setting) DescriptionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s Setting) SetDescription(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s Setting) IsEncrypted() bool {
	return capnp.Struct(s).Bit(0)
}

func (s Setting) SetIsEncrypted(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

// Setting_List is a list of Setting.
type Setting_List = capnp.StructList[Setting]

// NewSetting creates a new list of Setting.
func NewSetting_List(s *capnp.Segment, sz int32) (Setting_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5}, sz)
	return capnp.StructList[Setting](l), err
}

// Setting_Future is a wrapper for a Setting promised by a client call.
type Setting_Future struct{ *capnp.Future }

func (f Setting_Future) Struct() (Setting, error) {
	p, err := f.Future.Ptr()
	return Setting(p.Struct()), err
}
func (p Setting_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}

type Role capnp.Struct

// Role_TypeID is the unique identifier for the type Role.
const Role_TypeID = 0xfb2c8a368b82e3e8

func NewRole(s *capnp.Segment) (Role, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5})
	return Role(st), err
}

func NewRootRole(s *capnp.Segment) (Role, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5})
	return Role(st), err
}

func ReadRootRole(msg *capnp.Message) (Role, error) {
	root, err := msg.Root()
	return Role(root.Struct()), err
}

func (s Role) String() string {
	str, _ := text.Marshal(0xfb2c8a368b82e3e8, capnp.Struct(s))
	return str
}

func (s Role) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Role) DecodeFromPtr(p capnp.Ptr) Role {
	return Role(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Role) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Role) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Role) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Role) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Role) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s Role) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Role) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s Role) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Role) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Role) HasName() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Role) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Role) SetName(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Role) DisplayName() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Role) HasDisplayName() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Role) DisplayNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Role) SetDisplayName(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Role) Description() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Role) HasDescription() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Role) DescriptionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Role) SetDescription(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Role) Permissions() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s Role) HasPermissions() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Role) PermissionsBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s Role) SetPermissions(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s Role) IsActive() bool {
	return capnp.Struct(s).Bit(0)
}

func (s Role) SetIsActive(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s Role) IsSystem() bool {
	return capnp.Struct(s).Bit(1)
}

func (s Role) SetIsSystem(v bool) {
	capnp.Struct(s).SetBit(1, v)
}

// Role_List is a list of Role.
type Role_List = capnp.StructList[Role]

// NewRole creates a new list of Role.
func NewRole_List(s *capnp.Segment, sz int32) (Role_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5}, sz)
	return capnp.StructList[Role](l), err
}

// Role_Future is a wrapper for a Role promised by a client call.
type Role_Future struct{ *capnp.Future }

func (f Role_Future) Struct() (Role, error) {
	p, err := f.Future.Ptr()
	return Role(p.Struct()), err
}
func (p Role_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}

type User capnp.Struct

// User_TypeID is the unique identifier for the type User.
const User_TypeID = 0xacefdcab1b58c79e

func NewUser(s *capnp.Segment) (User, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 13})
	return User(st), err
}

func NewRootUser(s *capnp.Segment) (User, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 13})
	return User(st), err
}

func ReadRootUser(msg *capnp.Message) (User, error) {
	root, err := msg.Root()
	return User(root.Struct()), err
}

func (s User) String() string {
	str, _ := text.Marshal(0xacefdcab1b58c79e, capnp.Struct(s))
	return str
}

func (s User) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (User) DecodeFromPtr(p capnp.Ptr) User {
	return User(capnp.Struct{}.DecodeFromPtr(p))
}

func (s User) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s User) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s User) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s User) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s User) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s User) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s User) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s User) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s User) Username() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s User) HasUsername() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s User) UsernameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s User) SetUsername(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s User) Email() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s User) HasEmail() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s User) EmailBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s User) SetEmail(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s User) PasswordHash() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s User) HasPasswordHash() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s User) PasswordHashBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s User) SetPasswordHash(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s User) RoleId() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s User) HasRoleId() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s User) RoleIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s User) SetRoleId(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s User) FullName() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s User) HasFullName() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s User) FullNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s User) SetFullName(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s User) DisplayName() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s User) HasDisplayName() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s User) DisplayNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s User) SetDisplayName(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

func (s User) Department() (string, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.Text(), err
}

func (s User) HasDepartment() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s User) DepartmentBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.TextBytes(), err
}

func (s User) SetDepartment(v string) error {
	return capnp.Struct(s).SetText(7, v)
}

func (s User) JobTitle() (string, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.Text(), err
}

func (s User) HasJobTitle() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s User) JobTitleBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.TextBytes(), err
}

func (s User) SetJobTitle(v string) error {
	return capnp.Struct(s).SetText(8, v)
}

func (s User) IsActive() bool {
	return capnp.Struct(s).Bit(0)
}

func (s User) SetIsActive(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s User) LastLoginAt() (string, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return p.Text(), err
}

func (s User) HasLastLoginAt() bool {
	return capnp.Struct(s).HasPtr(9)
}

func (s User) LastLoginAtBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return p.TextBytes(), err
}

func (s User) SetLastLoginAt(v string) error {
	return capnp.Struct(s).SetText(9, v)
}

func (s User) PasswordChangedAt() (string, error) {
	p, err := capnp.Struct(s).Ptr(10)
	return p.Text(), err
}

func (s User) HasPasswordChangedAt() bool {
	return capnp.Struct(s).HasPtr(10)
}

func (s User) PasswordChangedAtBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(10)
	return p.TextBytes(), err
}

func (s User) SetPasswordChangedAt(v string) error {
	return capnp.Struct(s).SetText(10, v)
}

func (s User) MustChangePassword() bool {
	return capnp.Struct(s).Bit(1)
}

func (s User) SetMustChangePassword(v bool) {
	capnp.Struct(s).SetBit(1, v)
}

func (s User) RoleName() (string, error) {
	p, err := capnp.Struct(s).Ptr(11)
	return p.Text(), err
}

func (s User) HasRoleName() bool {
	return capnp.Struct(s).HasPtr(11)
}

func (s User) RoleNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(11)
	return p.TextBytes(), err
}

func (s User) SetRoleName(v string) error {
	return capnp.Struct(s).SetText(11, v)
}

func (s User) Role() (Role, error) {
	p, err := capnp.Struct(s).Ptr(12)
	return Role(p.Struct()), err
}

func (s User) HasRole() bool {
	return capnp.Struct(s).HasPtr(12)
}

func (s User) SetRole(v Role) error {
	return capnp.Struct(s).SetPtr(12, capnp.Struct(v).ToPtr())
}

// NewRole sets the role field to a newly
// allocated Role struct, preferring placement in s's segment.
func (s User) NewRole() (Role, error) {
	ss, err := NewRole(capnp.Struct(s).Segment())
	if err != nil {
		return Role{}, err
	}
	err = capnp.Struct(s).SetPtr(12, capnp.Struct(ss).ToPtr())
	return ss, err
}

// User_List is a list of User.
type User_List = capnp.StructList[User]

// NewUser creates a new list of User.
func NewUser_List(s *capnp.Segment, sz int32) (User_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 13}, sz)
	return capnp.StructList[User](l), err
}

// User_Future is a wrapper for a User promised by a client call.
type User_Future struct{ *capnp.Future }

func (f User_Future) Struct() (User, error) {
	p, err := f.Future.Ptr()
	return User(p.Struct()), err
}
func (p User_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}
func (p User_Future) Role() Role_Future {
	return Role_Future{Future: p.Future.Field(12, nil)}
}

type Device capnp.Struct

// Device_TypeID is the unique identifier for the type Device.
const Device_TypeID = 0xd0759e7d3b1eab17

func NewDevice(s *capnp.Segment) (Device, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 10})
	return Device(st), err
}

func NewRootDevice(s *capnp.Segment) (Device, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 10})
	return Device(st), err
}

func ReadRootDevice(msg *capnp.Message) (Device, error) {
	root, err := msg.Root()
	return Device(root.Struct()), err
}

func (s Device) String() string {
	str, _ := text.Marshal(0xd0759e7d3b1eab17, capnp.Struct(s))
	return str
}

func (s Device) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Device) DecodeFromPtr(p capnp.Ptr) Device {
	return Device(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Device) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Device) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Device) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Device) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Device) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s Device) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Device) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s Device) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Device) MachineId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Device) HasMachineId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Device) MachineIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Device) SetMachineId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Device) DeviceName() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Device) HasDeviceName() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Device) DeviceNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Device) SetDeviceName(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Device) OsInfo() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Device) HasOsInfo() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Device) OsInfoBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Device) SetOsInfo(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Device) FirstSeenAt() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s Device) HasFirstSeenAt() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Device) FirstSeenAtBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s Device) SetFirstSeenAt(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s Device) LastSeenAt() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s Device) HasLastSeenAt() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Device) LastSeenAtBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s Device) SetLastSeenAt(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s Device) Status() DeviceStatus {
	return DeviceStatus(capnp.Struct(s).Uint16(0))
}

func (s Device) SetStatus(v DeviceStatus) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s Device) ApprovedBy() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s Device) HasApprovedBy() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s Device) ApprovedByBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s Device) SetApprovedBy(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

func (s Device) ApprovedAt() (string, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.Text(), err
}

func (s Device) HasApprovedAt() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s Device) ApprovedAtBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.TextBytes(), err
}

func (s Device) SetApprovedAt(v string) error {
	return capnp.Struct(s).SetText(7, v)
}

func (s Device) IsAdminDevice() bool {
	return capnp.Struct(s).Bit(16)
}

func (s Device) SetIsAdminDevice(v bool) {
	capnp.Struct(s).SetBit(16, v)
}

func (s Device) Notes() (string, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.Text(), err
}

func (s Device) HasNotes() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s Device) NotesBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.TextBytes(), err
}

func (s Device) SetNotes(v string) error {
	return capnp.Struct(s).SetText(8, v)
}

func (s Device) ApproverName() (string, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return p.Text(), err
}

func (s Device) HasApproverName() bool {
	return capnp.Struct(s).HasPtr(9)
}

func (s Device) ApproverNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return p.TextBytes(), err
}

func (s Device) SetApproverName(v string) error {
	return capnp.Struct(s).SetText(9, v)
}

// Device_List is a list of Device.
type Device_List = capnp.StructList[Device]

// NewDevice creates a new list of Device.
func NewDevice_List(s *capnp.Segment, sz int32) (Device_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 10}, sz)
	return capnp.StructList[Device](l), err
}

// Device_Future is a wrapper for a Device promised by a client call.
type Device_Future struct{ *capnp.Future }

func (f Device_Future) Struct() (Device, error) {
	p, err := f.Future.Ptr()
	return Device(p.Struct()), err
}
func (p Device_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}

type DeviceUser capnp.Struct

// DeviceUser_TypeID is the unique identifier for the type DeviceUser.
const DeviceUser_TypeID = 0x99d3b7fd84c0a0dd

func NewDeviceUser(s *capnp.Segment) (DeviceUser, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5})
	return DeviceUser(st), err
}

func NewRootDeviceUser(s *capnp.Segment) (DeviceUser, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5})
	return DeviceUser(st), err
}

func ReadRootDeviceUser(msg *capnp.Message) (DeviceUser, error) {
	root, err := msg.Root()
	return DeviceUser(root.Struct()), err
}

func (s DeviceUser) String() string {
	str, _ := text.Marshal(0x99d3b7fd84c0a0dd, capnp.Struct(s))
	return str
}

func (s DeviceUser) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (DeviceUser) DecodeFromPtr(p capnp.Ptr) DeviceUser {
	return DeviceUser(capnp.Struct{}.DecodeFromPtr(p))
}

func (s DeviceUser) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s DeviceUser) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s DeviceUser) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s DeviceUser) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s DeviceUser) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s DeviceUser) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s DeviceUser) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s DeviceUser) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s DeviceUser) DeviceId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s DeviceUser) HasDeviceId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s DeviceUser) DeviceIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s DeviceUser) SetDeviceId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s DeviceUser) UserId() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s DeviceUser) HasUserId() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s DeviceUser) UserIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s DeviceUser) SetUserId(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s DeviceUser) IsPrimary() bool {
	return capnp.Struct(s).Bit(0)
}

func (s DeviceUser) SetIsPrimary(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s DeviceUser) User() (User, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return User(p.Struct()), err
}

func (s DeviceUser) HasUser() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s DeviceUser) SetUser(v User) error {
	return capnp.Struct(s).SetPtr(3, capnp.Struct(v).ToPtr())
}

// NewUser sets the user field to a newly
// allocated User struct, preferring placement in s's segment.
func (s DeviceUser) NewUser() (User, error) {
	ss, err := NewUser(capnp.Struct(s).Segment())
	if err != nil {
		return User{}, err
	}
	err = capnp.Struct(s).SetPtr(3, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s DeviceUser) Device() (Device, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return Device(p.Struct()), err
}

func (s DeviceUser) HasDevice() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s DeviceUser) SetDevice(v Device) error {
	return capnp.Struct(s).SetPtr(4, capnp.Struct(v).ToPtr())
}

// NewDevice sets the device field to a newly
// allocated Device struct, preferring placement in s's segment.
func (s DeviceUser) NewDevice() (Device, error) {
	ss, err := NewDevice(capnp.Struct(s).Segment())
	if err != nil {
		return Device{}, err
	}
	err = capnp.Struct(s).SetPtr(4, capnp.Struct(ss).ToPtr())
	return ss, err
}

// DeviceUser_List is a list of DeviceUser.
type DeviceUser_List = capnp.StructList[DeviceUser]

// NewDeviceUser creates a new list of DeviceUser.
func NewDeviceUser_List(s *capnp.Segment, sz int32) (DeviceUser_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5}, sz)
	return capnp.StructList[DeviceUser](l), err
}

// DeviceUser_Future is a wrapper for a DeviceUser promised by a client call.
type DeviceUser_Future struct{ *capnp.Future }

func (f DeviceUser_Future) Struct() (DeviceUser, error) {
	p, err := f.Future.Ptr()
	return DeviceUser(p.Struct()), err
}
func (p DeviceUser_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}
func (p DeviceUser_Future) User() User_Future {
	return User_Future{Future: p.Future.Field(3, nil)}
}
func (p DeviceUser_Future) Device() Device_Future {
	return Device_Future{Future: p.Future.Field(4, nil)}
}

type UserSession capnp.Struct

// UserSession_TypeID is the unique identifier for the type UserSession.
const UserSession_TypeID = 0x8efcbeaea0bdd9c1

func NewUserSession(s *capnp.Segment) (UserSession, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 9})
	return UserSession(st), err
}

func NewRootUserSession(s *capnp.Segment) (UserSession, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 9})
	return UserSession(st), err
}

func ReadRootUserSession(msg *capnp.Message) (UserSession, error) {
	root, err := msg.Root()
	return UserSession(root.Struct()), err
}

func (s UserSession) String() string {
	str, _ := text.Marshal(0x8efcbeaea0bdd9c1, capnp.Struct(s))
	return str
}

func (s UserSession) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (UserSession) DecodeFromPtr(p capnp.Ptr) UserSession {
	return UserSession(capnp.Struct{}.DecodeFromPtr(p))
}

func (s UserSession) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s UserSession) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s UserSession) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s UserSession) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s UserSession) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s UserSession) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s UserSession) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s UserSession) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s UserSession) UserId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s UserSession) HasUserId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s UserSession) UserIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s UserSession) SetUserId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s UserSession) Token() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s UserSession) HasToken() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s UserSession) TokenBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s UserSession) SetToken(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s UserSession) RefreshToken() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s UserSession) HasRefreshToken() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s UserSession) RefreshTokenBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s UserSession) SetRefreshToken(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s UserSession) AccessTokenExpiry() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s UserSession) HasAccessTokenExpiry() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s UserSession) AccessTokenExpiryBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s UserSession) SetAccessTokenExpiry(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s UserSession) RefreshTokenExpiry() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s UserSession) HasRefreshTokenExpiry() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s UserSession) RefreshTokenExpiryBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s UserSession) SetRefreshTokenExpiry(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s UserSession) LastActivityAt() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s UserSession) HasLastActivityAt() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s UserSession) LastActivityAtBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s UserSession) SetLastActivityAt(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

func (s UserSession) IsActive() bool {
	return capnp.Struct(s).Bit(0)
}

func (s UserSession) SetIsActive(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s UserSession) InvalidatedAt() (string, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.Text(), err
}

func (s UserSession) HasInvalidatedAt() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s UserSession) InvalidatedAtBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.TextBytes(), err
}

func (s UserSession) SetInvalidatedAt(v string) error {
	return capnp.Struct(s).SetText(7, v)
}

func (s UserSession) InvalidatedReason() (string, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.Text(), err
}

func (s UserSession) HasInvalidatedReason() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s UserSession) InvalidatedReasonBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.TextBytes(), err
}

func (s UserSession) SetInvalidatedReason(v string) error {
	return capnp.Struct(s).SetText(8, v)
}

// UserSession_List is a list of UserSession.
type UserSession_List = capnp.StructList[UserSession]

// NewUserSession creates a new list of UserSession.
func NewUserSession_List(s *capnp.Segment, sz int32) (UserSession_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 9}, sz)
	return capnp.StructList[UserSession](l), err
}

// UserSession_Future is a wrapper for a UserSession promised by a client call.
type UserSession_Future struct{ *capnp.Future }

func (f UserSession_Future) Struct() (UserSession, error) {
	p, err := f.Future.Ptr()
	return UserSession(p.Struct()), err
}
func (p UserSession_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}

type Alert capnp.Struct

// Alert_TypeID is the unique identifier for the type Alert.
const Alert_TypeID = 0xa9cebaef53d1ae29

func NewAlert(s *capnp.Segment) (Alert, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return Alert(st), err
}

func NewRootAlert(s *capnp.Segment) (Alert, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return Alert(st), err
}

func ReadRootAlert(msg *capnp.Message) (Alert, error) {
	root, err := msg.Root()
	return Alert(root.Struct()), err
}

func (s Alert) String() string {
	str, _ := text.Marshal(0xa9cebaef53d1ae29, capnp.Struct(s))
	return str
}

func (s Alert) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Alert) DecodeFromPtr(p capnp.Ptr) Alert {
	return Alert(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Alert) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Alert) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Alert) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Alert) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Alert) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s Alert) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Alert) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s Alert) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Alert) AlertType() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Alert) HasAlertType() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Alert) AlertTypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Alert) SetAlertType(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Alert) Severity() common.RiskLevel {
	return common.RiskLevel(capnp.Struct(s).Uint16(0))
}

func (s Alert) SetSeverity(v common.RiskLevel) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s Alert) Title() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Alert) HasTitle() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Alert) TitleBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Alert) SetTitle(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Alert) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Alert) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Alert) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Alert) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Alert) IsActive() bool {
	return capnp.Struct(s).Bit(16)
}

func (s Alert) SetIsActive(v bool) {
	capnp.Struct(s).SetBit(16, v)
}

func (s Alert) IsAcknowledged() bool {
	return capnp.Struct(s).Bit(17)
}

func (s Alert) SetIsAcknowledged(v bool) {
	capnp.Struct(s).SetBit(17, v)
}

// Alert_List is a list of Alert.
type Alert_List = capnp.StructList[Alert]

// NewAlert creates a new list of Alert.
func NewAlert_List(s *capnp.Segment, sz int32) (Alert_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4}, sz)
	return capnp.StructList[Alert](l), err
}

// Alert_Future is a wrapper for a Alert promised by a client call.
type Alert_Future struct{ *capnp.Future }

func (f Alert_Future) Struct() (Alert, error) {
	p, err := f.Future.Ptr()
	return Alert(p.Struct()), err
}
func (p Alert_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}

type AuditLog capnp.Struct

// AuditLog_TypeID is the unique identifier for the type AuditLog.
const AuditLog_TypeID = 0x91634d68d0e158ee

func NewAuditLog(s *capnp.Segment) (AuditLog, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return AuditLog(st), err
}

func NewRootAuditLog(s *capnp.Segment) (AuditLog, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return AuditLog(st), err
}

func ReadRootAuditLog(msg *capnp.Message) (AuditLog, error) {
	root, err := msg.Root()
	return AuditLog(root.Struct()), err
}

func (s AuditLog) String() string {
	str, _ := text.Marshal(0x91634d68d0e158ee, capnp.Struct(s))
	return str
}

func (s AuditLog) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AuditLog) DecodeFromPtr(p capnp.Ptr) AuditLog {
	return AuditLog(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AuditLog) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AuditLog) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AuditLog) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AuditLog) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AuditLog) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s AuditLog) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AuditLog) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s AuditLog) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s AuditLog) UserId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s AuditLog) HasUserId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s AuditLog) UserIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s AuditLog) SetUserId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s AuditLog) Action() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s AuditLog) HasAction() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s AuditLog) ActionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s AuditLog) SetAction(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s AuditLog) Resource() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s AuditLog) HasResource() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s AuditLog) ResourceBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s AuditLog) SetResource(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

// AuditLog_List is a list of AuditLog.
type AuditLog_List = capnp.StructList[AuditLog]

// NewAuditLog creates a new list of AuditLog.
func NewAuditLog_List(s *capnp.Segment, sz int32) (AuditLog_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[AuditLog](l), err
}

// AuditLog_Future is a wrapper for a AuditLog promised by a client call.
type AuditLog_Future struct{ *capnp.Future }

func (f AuditLog_Future) Struct() (AuditLog, error) {
	p, err := f.Future.Ptr()
	return AuditLog(p.Struct()), err
}
func (p AuditLog_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}

type Job capnp.Struct

// Job_TypeID is the unique identifier for the type Job.
const Job_TypeID = 0xf8c5b0796704d42c

func NewJob(s *capnp.Segment) (Job, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 7})
	return Job(st), err
}

func NewRootJob(s *capnp.Segment) (Job, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 7})
	return Job(st), err
}

func ReadRootJob(msg *capnp.Message) (Job, error) {
	root, err := msg.Root()
	return Job(root.Struct()), err
}

func (s Job) String() string {
	str, _ := text.Marshal(0xf8c5b0796704d42c, capnp.Struct(s))
	return str
}

func (s Job) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Job) DecodeFromPtr(p capnp.Ptr) Job {
	return Job(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Job) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Job) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Job) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Job) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Job) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s Job) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Job) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s Job) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Job) Type() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Job) HasType() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Job) TypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Job) SetType(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Job) Status() JobStatus {
	return JobStatus(capnp.Struct(s).Uint16(0))
}

func (s Job) SetStatus(v JobStatus) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s Job) Input() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Job) HasInput() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Job) InputBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Job) SetInput(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Job) Output() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Job) HasOutput() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Job) OutputBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Job) SetOutput(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Job) Error() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s Job) HasError() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Job) ErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s Job) SetError(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s Job) Progress() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s Job) SetProgress(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s Job) StartedAt() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s Job) HasStartedAt() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Job) StartedAtBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s Job) SetStartedAt(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s Job) CompletedAt() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s Job) HasCompletedAt() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s Job) CompletedAtBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s Job) SetCompletedAt(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

func (s Job) Attempts() int64 {
	return int64(capnp.Struct(s).Uint64(16))
}

func (s Job) SetAttempts(v int64) {
	capnp.Struct(s).SetUint64(16, uint64(v))
}

func (s Job) MaxAttempts() int64 {
	return int64(capnp.Struct(s).Uint64(24))
}

func (s Job) SetMaxAttempts(v int64) {
	capnp.Struct(s).SetUint64(24, uint64(v))
}

// Job_List is a list of Job.
type Job_List = capnp.StructList[Job]

// NewJob creates a new list of Job.
func NewJob_List(s *capnp.Segment, sz int32) (Job_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 32, PointerCount: 7}, sz)
	return capnp.StructList[Job](l), err
}

// Job_Future is a wrapper for a Job promised by a client call.
type Job_Future struct{ *capnp.Future }

func (f Job_Future) Struct() (Job, error) {
	p, err := f.Future.Ptr()
	return Job(p.Struct()), err
}
func (p Job_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}

type BackupPolicy capnp.Struct

// BackupPolicy_TypeID is the unique identifier for the type BackupPolicy.
const BackupPolicy_TypeID = 0xc495862bccdb91c3

func NewBackupPolicy(s *capnp.Segment) (BackupPolicy, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3})
	return BackupPolicy(st), err
}

func NewRootBackupPolicy(s *capnp.Segment) (BackupPolicy, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3})
	return BackupPolicy(st), err
}

func ReadRootBackupPolicy(msg *capnp.Message) (BackupPolicy, error) {
	root, err := msg.Root()
	return BackupPolicy(root.Struct()), err
}

func (s BackupPolicy) String() string {
	str, _ := text.Marshal(0xc495862bccdb91c3, capnp.Struct(s))
	return str
}

func (s BackupPolicy) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (BackupPolicy) DecodeFromPtr(p capnp.Ptr) BackupPolicy {
	return BackupPolicy(capnp.Struct{}.DecodeFromPtr(p))
}

func (s BackupPolicy) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s BackupPolicy) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s BackupPolicy) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s BackupPolicy) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s BackupPolicy) AutoBackupEnabled() bool {
	return capnp.Struct(s).Bit(0)
}

func (s BackupPolicy) SetAutoBackupEnabled(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s BackupPolicy) FrequencyDays() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s BackupPolicy) SetFrequencyDays(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s BackupPolicy) LastBackupAt() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s BackupPolicy) HasLastBackupAt() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s BackupPolicy) LastBackupAtBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s BackupPolicy) SetLastBackupAt(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s BackupPolicy) LastBackupPath() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s BackupPolicy) HasLastBackupPath() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s BackupPolicy) LastBackupPathBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s BackupPolicy) SetLastBackupPath(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s BackupPolicy) NextBackupDueAt() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s BackupPolicy) HasNextBackupDueAt() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s BackupPolicy) NextBackupDueAtBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s BackupPolicy) SetNextBackupDueAt(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s BackupPolicy) DueNow() bool {
	return capnp.Struct(s).Bit(1)
}

func (s BackupPolicy) SetDueNow(v bool) {
	capnp.Struct(s).SetBit(1, v)
}

// BackupPolicy_List is a list of BackupPolicy.
type BackupPolicy_List = capnp.StructList[BackupPolicy]

// NewBackupPolicy creates a new list of BackupPolicy.
func NewBackupPolicy_List(s *capnp.Segment, sz int32) (BackupPolicy_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3}, sz)
	return capnp.StructList[BackupPolicy](l), err
}

// BackupPolicy_Future is a wrapper for a BackupPolicy promised by a client call.
type BackupPolicy_Future struct{ *capnp.Future }

func (f BackupPolicy_Future) Struct() (BackupPolicy, error) {
	p, err := f.Future.Ptr()
	return BackupPolicy(p.Struct()), err
}

const schema_c198fb847f509fc5 = "x\xda\x8cW\x7fl\x14\xd7\x11\x9e\xd9w\xe7\xb3\x1d;" +
	"\xe7\xd3^\xd4D-5-X\x04p\x0a\xd8\xa1i)" +
	"\x95c\xd7\x96\x00\x01\xf5\xfa@\xa1\x11\x95X\xef>\x9f" +
	"\x17\xef\xed.\xfb\xc3pQ\x91\xd3(\xa9\x92\xb6jJ" +
	"\x94H\xd0\x12J$PA\x81\x14*P\xa1\x02\x04)" +
	"\xa8\x90\x92\xc8\xb4 AK\xa4\xd2\"5Bj\x93V" +
	"\xad\x9a4\xa0\xad\xe6\xed\xdd\xed\xda\xb1\x09\xf2?\xbeo" +
	"\xe7\xfd\x98\x99o\xe6\x9b\xb7\xf0J\xf3\xe3\xa9E\xcd\xbf" +
	"\xe8\x06\xa9p[J\xd7\x85g\xae\x9d\xdc\xfd\xc6\xa9\xdb" +
	"?\x02%\x8f\x18\x9e\xfbY\xff\xd8\xb3\x1fo?\x03\xe9" +
	"\x86\x0c@\xe7\xc9\x99\x12\xca\x17f\xd2\xbf\xe7f>&" +
	"\x01\x86\xffXwc|x\x95\xb6\x0dr\xf9\xa4u*" +
	"\x03 \xcf\x9duK^<\x8b\xfe[4\xebo\x80\xe1" +
	"\xbb\xbbO?{\xe7W\x7f\xd81y\xeb4\x994\xcc" +
	"\xfe\x9f\xfc\xc0l\xda97\xfb\x09\x04\x0c\xb3C\xfd\xbf" +
	"\xfbo\xbd\xf9S\xc8\xe5\xa5\xd8\x18\xb0\x93\xb75\xa2\x1c" +
	"\xb4\xd1\xa2Mmc\x80\xe1\x957\xd7I\xb3\xfe\xb3k" +
	"\xffdK\xf9`\xdb\xbf\xe4\xe3\xc2\xf0\xa80\x9c\xfb\xc6" +
	"\xa5\xc2\xfb\xbf~g\xff\xe4\x0b\x88\xdb\xfe\xb3\xed\xf7\xf2" +
	"\x1d2\xee\xfc\xa8\xedE\xba\xc0\xae\xdf\xae\xfb\xec\xeb\xd7" +
	"\xdf?0\xd9\xba\x99\xac\xb7\xcdyK~u\x0eY\xef" +
	"\x98\xf3M\x06\x18\xfef\xdb\x9f.\xce\xff\xde+g\xc9" +
	":q\x8b4#\x9b\xc5\xf3\x1bQ\xee\x9bO\xffv\xcf" +
	"\x17\xde}\xe6\xf5\xcf\x7fm\xeb\xae`|\xf2\xe6\x8d\xb4" +
	"\xf9\xde\xf6?\xca\x87\xdb\xc9\xfa`\xfb\xcf)\xca\xed\x97" +
	"S\xc5\xf2\xa1s\x1f\x92u*a\x9d!\xeb\xef.x" +
	"S~a\x01Y?\xb7\xc0&k\xe31\xa3\xe5\xd6\x13" +
	"\x99\x8f\xa7\x8cs\xae\xe3/\xf2\x8c\x0e\xb2~\xa8C\xdc" +
	"\xe4\xbd\xbf>\xf3\x83/\x7f\xbf}j\xebM\x9do\xc9" +
	"[;\xc9\xba\xdc\xf9\"B8\xe1\xef\x97\xa1\xa7\x0d\xf3" +
	"\x92\xea-`\x865\xe4\xaa_\xd2T\xc7r\x96\xac\xf5" +
	"\xb8[\xe0\x9eg\xd8\x16\xf4#*\x0f\xb3\x14@\x0a)" +
	"\xc78\x0f\xa0\x90B\x86\x85\x16\x940\x87\x98G\xc2\x9b" +
	"q\x09@\xa1\x9e\xf0<\xe1\x92\x94G\x89\xee\x8a\x1d\x00" +
	"\x85&\xc2\x1f$\x9c\xb1<2\x00\xf9\x01\xdc\x08P\xc8" +
	"\x13>\x93\xf0T*\x8f)\x00y\x06\xbe\x04P\x98I" +
	"x;\xe1\xe9t\x1e\xd3DD\xfc\x09@\xa1\x9d\xf0\xaf" +
	"\x10^W\x97\xc7:\x00y1>\x05Px\x94\xf0\xc7" +
	"QB\xcc\xe4\x91\x9c\xfe:\xae\x00(,%x\x19\x99" +
	"\xd7g\xf2X\x0f \xf7\xa1\x0bP\xe8%\xbc\x9f\xf0\x86" +
	"\xfa<6\x00\xc8\xab\xc4\xb1\xfd\x84\xafG\x09\xb3\x83\xaa" +
	"\xc7\xb1%\x94\xde\xb9u\xa7g\xe7\xbf/\x01 \xb6\x00" +
	"v\x05\x1ew\x97\xeb\xd8\x04\x126\x01\xb6\xfa\xf6\x08\xb7" +
	"\xaa\xbfB\x97\x0f\xb9\xdc\x1b^\x03\xd9\x09\xb0\xaai\xdc" +
	"\xf3\xd6\xd88\xc2\xad\xbe-\x8e\xe1b\xf9\x13K\xd0\xae" +
	"|dn\xfc\xd1T=\xbf[\xf3\x0d\xe8\x1a5\xfcr" +
	"\xb7_\xfb`x\x04\x8fr\xa0k\x81\x84D\x01\xc3\x1a" +
	"UMCW\xa1\xd5\xe7z\xd2\xb6\x82\xa3\xcf\xf5\x01\xae" +
	"z6\xc67\xab\xa6^J\xa6\xbe;\xd0\x8d\xac\xbf\xd2" +
	".R\xde[\xaay\xcf\xa9\xf3\x00\x94\xf5\x0c\x95\xe18" +
	"\xe99\xbe\x04@\xd9\xc0P1\xe3\x8c\xe7\x0c\x02u\x86" +
	"\x8a\x13\xa7;WZ\x01\xa0\x98\x0c\x95-\xf7\x1a\xdc." +
	"U\xf3\x0d;\x19]\xcf\x0e\\M8}W\x07z\xf9" +
	"\xa8\xd1\xa5q\xa20\xb9\xf0`\xcd\x85\x1d\xe4\xc2\xcb\x0c" +
	"\x95\xdd\x09\x17^\xa5\x8b\xedd\xa8\xecK\xb8\xb0\x97\\" +
	"\xd8\xcdP9 !V<\xd8?\x00\xa0\xecc\xa8\x1c" +
	"!\xb62\xc1\xd6\xdca\xda\xf2\x00C\xe5\x18Q5%" +
	"\xa8\x9a;J\xab\x0f1TNL\xebk\xa8\xf3QC" +
	"\xe3\xcb\xf5\x847\x93\xfc\x0f\x0d\xaf\xdf5J\xaa\x0bX" +
	"\xaef9K&\xd8\x12\xb7\xb5J\xe4\xa2\xdd\xb0%n" +
	"I\x95c\xa6,\xee^a]\xf0U?\xf0@\x94w" +
	"\xe4\xf5\xe2'iYnQ\x0f\x00J\xb9\xb9+\x00\x90" +
	"\xe5\xda\xe8W*7\xa3\x07 \x1c2\\\xcf/p\x1f" +
	"X\xe0\x8c9\xdc\xd2\x0d\xab\x18\xaa\x8e\xe3\xda\xa3\x9c<" +
	"\x19\x1b4mm\x84\xebc.\x1f\xb5G\xb8>u~" +
	"V\xd8\x83\x85Vqx\xe2\xe8\x1eq\xf4#\xd1\xd1m" +
	"\x03\xe2\xe8/,\x11G?4\x00P=m\xcc\x0d," +
	"\x8bN\xd5\xec\x92cr\x9f\x03\xea]C\xaaar=" +
	"\xd4TK\xe3\xa6I\xd04\xcc6\xb9\x8b>\x1d\xfa\xb9" +
	"\x1a'\x8e\xce\x8bsU\xe3\xc4qJ\xf51\x86\xcaY" +
	"\x09\xb1B\x893\xc4\x93\xd3\x0c\x95\x8b\xc4j)\xe2\xc4" +
	"\x85\x0e\x00\xe5,Ce<\xc1\x89\xb7{\x00\x94\xf3\x0c" +
	"\x95\xcb\xc4\x89\x96\x88\x13\x97h\xf98C\xe5:\xf5\xae" +
	"\x9c\xe8]\xb9kO\x01(W\x19*7\xa7'\x8aj" +
	"r\xd7_Sv\x00yL{>\xca]\xc3/\x13y" +
	"\xb2\xe1\xa9]7,w\xd9\xa9\xd3\xb4\"KM\xc9\xf0" +
	"\xcd\x9a\xedX\x89{\x9eZ\xe4w\xef\x1d^\xb76b" +
	"\xd9\x9b\xa1\xcb\xe4z\x91\xeb\xb5\x0fS\x86\x91\x0a+\xa2" +
	"\xcd\xd2\x9a*\xbc\"T\xe1\xc7\xd4>w&Ua\x87" +
	"h\xc3\xdb\x09\xdf\x93T\x85\xd7\x84*\xec$|_R" +
	"\x15\xf6\x0aU\xd8C\xf8\xa1\xa4*\x1c\x14\xea\xb2\x8f\xf0" +
	"#IU8,\xf6?D\xf8\x89\xa4*\x1c\xc7A\x80" +
	"\xc21\xc2\xcf\x12\x9e\xa9\xc8\xc2\x19|\x12\xa0p\x9a\xf0" +
	"\x8bB\x16\xea#Y\xb8 \xf69O\xf8eR\x91\x86" +
	"H\x15.\x09x\x9c\xe0\xebd\xde\xd8\x90\xc7F\x00\xf9" +
	"\x9a\xd8\xfe*\xe17\x09\xbf\xaf1\x8f\xf7\x01\xc87\x84" +
	"\x8a\xdc$\xfc\x03\xc2\x9b0\x8fM\x00\xf2\xdf\x85x}" +
	"@\xf8m\xc2\x9b\xef\xcbc3\x80\xfc\x91\xd8\xffC\xc2" +
	"S\x92\x84\xb9\xfb\x9b\xf2x?\x80\x8c\x12\x85\xf36\xe1" +
	"\xf5\xd2\xf4\xdc\xa0n`\xa9\xa5dKl\xe5%\xd50" +
	"k\xd9vT\xcf\xdbl\xbb:d\x97\xa9\xdep\xad\xd3" +
	"\xb8\xb6\xc9\x13\x9df(0\xcd\xd5\x13\xf7\x09u\xc3s" +
	"L\xb5\xbc\x1a2j)f\x8f\xce\x1d\xd5\xf5K\x1c\x98" +
	"\x15K\xccF{p\x0dq.\xb9|*\x9a\x91\x9e\xad" +
	"\xb4\x8b\x06d\xac\x84@U\xaf\x88\xdf\x18V\xad\"\xd7" +
	"\xbb1\xfeV\x0a<\x9f`,\xf2~a\xc6\xdc\x98\x9c" +
	"\xe4\xc4\xa4[g\x09\xc3\x96x\x1e\xba[\x1b\xecQ\xb5" +
	"\x91\xc0\xe9\xb7MC+G|NH\xc5K\x09U\xa8" +
	"\xb6\x85\xbd.\x80\xb2\x87\xa1r(n\x0b\x077&\x04" +
	"\x80a\xd4\x16\x8eR]\x1fa\xa8\x9c&\x0aKQ[" +
	"8\xf9\x0c\x80r\x82\xa1r\x9e\xf8\x8bQ[8\xb7$" +
	"\xee*\xa1\x1a\xf86]\x0a\x03\xa7\xcfR\x07M\x8e\xb1" +
	"\xb3C.\xdf\x14pK\x83\xd6r\xafZ\xf60\x0d\x12" +
	"\xa6+1\xa55\x90\x0d\x9cDPkpW\xe0\xf4\xab" +
	"~-\xf3\xa1\xc5\xb7\xf8\x953z\x03\xde\xed\xc7\xea\xa3" +
	"\x07|\xb5\xbd\xf9\xee\xa5O\xca\xc14N\xb1ZX\xab" +
	"\xfdnQ\xfb\xf1\xa8U\xad\xfd>\x1c\x980jUk" +
	"\x7f\x95\xa8\xc1\x95\x84\xafK\xd6\xfeZQ\xe3\xb5\x11\xac" +
	"V\xfb\xdf\x12\xc5\xb6\x8ep=Y\xfb\xaa\xd8g\x03\xe1" +
	"&\xd5l\xa5\xf4\x0d\xb1\x8dN\xb0#J\xbf.*\xfd" +
	"\x9207\x09\xdf\x92\x9c\x08\x03\x81\xfb\x84?-&\xc2" +
	"\x96\xa8\xf6\xb7\x8aI\xf1;\x84?/j\xbf>\xaa\xfd" +
	"\xe7D\xebz\x9a\xf0\x1f\x8a\xdao\x88j\xff\x05\xd1\xba" +
	"\x9e'\xfc\xe5\xe9'\xc8\xb0\xa4j\xc3\x86\xc5\x97\x03\xea" +
	"\x89\xaa\"A^\xad\x02\x8bK\xad\xcb\xf6\x96[Cv" +
	"\\\xa3\x91\xf6\xf2\x89\xc5Cy.pn\x01\x8b\xc1." +
	"O\x88+f\xe3\xe7W\xa4\x0c\xb1T\xb3\x9ex\xca\x8c" +
	"\xc1\x89\x13\xa6^2\xac^h\x8d&\x8b\x0a+Z-" +
	"\xdb\xe7\xde\xe4\xa5.dW'\x9b\xc4t\xaa/j\xac" +
	"\xbd\xc6\x9b6\xc1\x9bx\xd2\xaf\xf2f\xae\xc0g\x13\xbe" +
	"\x10k\x95&?\"\xf2\xfa0\xc1\x8fb\xac\xc1\xf2\"" +
	"\x91\x8f\xf8aP\x91ay\xb1\xb0_H\xf8R\x8c\xa7" +
	"3\xf9\xab\xc2\xbe\xf6`\xc8\xd5a\xc4\x9b\xc9/\x86L" +
	":\xe2\xcdd\x1a\xd7\xd7E\xbcY%h\x19\xd3\xb8A" +
	"\x8ax\xb3V\xec\xb3\x86\xf0\x0d\x827,\xe2\xcd\xb7\x85" +
	"\xfdz\xc2\x87\xa7\xe7G\xd6/;\xfc\x93\x99\xac=\x8f" +
	"+\x1aoXN\x10'\xdc\x0e\xfc\xc4\xcfV\xee\xba\xb6" +
	"\x1b\xf7W\xd7.\xba\xdc\xf3\xa8MV\xbb\x86\xe7\xab." +
	"=\x13 \xd1kk\x13U&\xf9|P}\x9f\x97\x1c" +
	"\x7f\xc2\xea\x92\xba\xa5\x9b`\xc88~\xdc\x89\xa6\xccz" +
	"\x81\xfb~\xc6\xb0\x8a\xf72\x88\x7f\x11@\xd9\xceP\xd9" +
	"\x93\x18\xc4_\xebH\xf4\xe1\xea[b\xef\x8a\xb8\x0fW" +
	"\xbbD\xee\xe0`\xdc\x881]\x19\xc4\x07\xe3><M" +
	"\xbc3#\xbcV\x0a\xad\xa3\xaa\x19\xc44\xd6T\x9f\x17" +
	"m\xb7<A\x15\xb9\xa7\xb9\x86\xe3C&\xf941\xbc" +
	">Ks\xcb\x0ed\xfcO\x1b\x9e\x06l\xd2\xc9{\x99" +
	"A\xe7%4\xa4\x1a\x8e\x93\x83\x09\x0d\xa9\x86\xe3\xdc`" +
	"r\x08\xad\x84\xe3m\x02/2T\xae\xc6\xe1\xb8Bq" +
	"\xbb\xccP\xf9sL\xfb\xdc\xbb\x04^g\xa8\xbc7=" +
	"'\xad\x09#\xc04\x83\xc1T\x81q\xb8[2<\xcf" +
	"\x80\x8cmy\x9f2\x82\x16\xca\x1eq*\xc6\xfe\x1f\x00" +
	"\x00\xff\xffN\xed8\xa7"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_c198fb847f509fc5,
		Nodes: []uint64{
			0x8efcbeaea0bdd9c1,
			0x91634d68d0e158ee,
			0x99d3b7fd84c0a0dd,
			0x9b6c08f7cb50660f,
			0xa99ef5230258c2d5,
			0xa9cebaef53d1ae29,
			0xacefdcab1b58c79e,
			0xc495862bccdb91c3,
			0xd0759e7d3b1eab17,
			0xf8c5b0796704d42c,
			0xfb0757ea10693769,
			0xfb2c8a368b82e3e8,
		},
		Compressed: true,
	})
}
