// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {device} from '../models';
import {time} from '../models';
import {finance} from '../models';
import {crm} from '../models';
import {infra} from '../models';
import {release} from '../models';
import {viewmodel} from '../models';
import {deletion} from '../models';

export function ActivateLicense(arg1:string):Promise<main.LicenseActivationResult>;

export function AddManualCustomerMapping(arg1:string,arg2:string):Promise<void>;

export function ApplyDeploymentLicenseActivationFlush():Promise<void>;

export function ApplyReconciliation(arg1:string):Promise<void>;

export function ApproveDevice(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function AutoMatchChequesToStatement(arg1:string,arg2:string):Promise<number>;

export function AutoMatchDepositsToStatement(arg1:string,arg2:string):Promise<number>;

export function BackfillOfferItemCostBreakdown():Promise<Record<string, any>>;

export function BackfillRFQDocumentTracking():Promise<number>;

export function BackupDatabase():Promise<string>;

export function BlockDevice(arg1:string):Promise<void>;

export function CalculateCosting(arg1:main.CostingRequest):Promise<main.CostingResult>;

export function CanViewUserActivityMonitoring():Promise<boolean>;

export function CancelJob(arg1:string):Promise<void>;

export function CancelScan(arg1:string):Promise<void>;

export function CheckDeviceStatus():Promise<device.RegistrationResult>;

export function CheckFirstInstall():Promise<boolean>;

export function CheckPermissionByRole(arg1:string,arg2:string):Promise<boolean>;

export function CleanupOldJobs(arg1:number):Promise<void>;

export function ClearDepositInTransit(arg1:string,arg2:string,arg3:time.Time):Promise<void>;

export function ClearSyncHistory():Promise<void>;

export function ConfigureWatchPaths(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ConfirmOneDriveDeal(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CreateBookBankReconciliation(arg1:string,arg2:time.Time,arg3:number,arg4:number,arg5:number,arg6:number):Promise<finance.BookBankReconciliation>;

export function CreateCustomerFromButler(arg1:main.ButlerCustomerRequest):Promise<crm.CustomerMaster>;

export function CreateDepositInTransit(arg1:string,arg2:time.Time,arg3:number,arg4:string,arg5:string,arg6:string,arg7:any,arg8:Array<string>):Promise<finance.DepositInTransit>;

export function CreateOfferDraftFromButler(arg1:main.ButlerOfferDraftRequest):Promise<crm.Offer>;

export function CreateSupplierFromButler(arg1:main.ButlerSupplierRequest):Promise<crm.SupplierMaster>;

export function CreateUser(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<infra.User>;

export function DeactivateUser(arg1:string):Promise<void>;

export function EndUserActivitySession(arg1:string):Promise<void>;

export function EnsureLicenseTableExists():Promise<void>;

export function EnsurePhase7Rollout():Promise<void>;

export function EnsureUserActivityMonitoringFoundation():Promise<void>;

export function ExportCostingToExcel(arg1:main.CostingExportData):Promise<string>;

export function ExportCostingToPDF(arg1:main.CostingExportData):Promise<string>;

export function ExportPilotSignoffReport():Promise<main.PilotExportResult>;

export function ExportPilotSupportBundle():Promise<main.PilotSupportBundleResult>;

export function ExportReconciliationReport(arg1:main.ReconciliationResult,arg2:string):Promise<void>;

export function ExportReport(arg1:string,arg2:string,arg3:string):Promise<string>;

export function FinalizeBookBankReconciliation(arg1:string,arg2:string):Promise<void>;

export function FixDatabaseDates():Promise<Record<string, number>>;

export function FixPurchaseOrderSupplierNames():Promise<number>;

export function GenerateBatchLicenseKeys(arg1:string,arg2:number,arg3:string,arg4:string):Promise<Array<string>>;

export function GenerateCustomer360Report(arg1:string):Promise<string>;

export function GenerateDashboardReport():Promise<string>;

export function GenerateLicenseKey(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GeneratePredictionHistoryReport(arg1:number):Promise<string>;

export function GenerateReportAsync(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetAccessToken():Promise<string>;

export function GetAccessTokenWithValidation():Promise<string>;

export function GetApplicationPaths():Promise<main.ApplicationPaths>;

export function GetAuditLogs(arg1:number,arg2:string,arg3:string):Promise<Array<infra.AuditLog>>;

export function GetAuthState():Promise<main.AuthState>;

export function GetAvailableLocales():Promise<Array<string>>;

export function GetBackupInfo():Promise<Record<string, any>>;

export function GetBackupPolicy():Promise<infra.BackupPolicy>;

export function GetBookBankReconciliation(arg1:string):Promise<finance.BookBankReconciliation>;

export function GetBookBankReconciliationReport(arg1:string):Promise<main.BookBankReconciliationReport>;

export function GetBookBankReconciliations(arg1:string):Promise<Array<finance.BookBankReconciliation>>;

export function GetBuildInfo():Promise<release.BuildInfo>;

export function GetCRMCustomerDashboard():Promise<main.CRMCustomerDashboard>;

export function GetCRMCustomerDashboardByYear(arg1:number):Promise<main.CRMCustomerDashboard>;

export function GetCSRFToken():Promise<string>;

export function GetCacheStats():Promise<Record<string, any>>;

export function GetCollectionPerformance():Promise<Record<string, any>>;

export function GetComplianceDashboard(arg1:string):Promise<viewmodel.ComplianceDashboardVM>;

export function GetCurrentDeviceInfo():Promise<infra.Device>;

export function GetCurrentUserRole():Promise<string>;

export function GetCurrentUserStub():Promise<infra.User>;

export function GetCustomerNameMapping():Promise<Record<string, string>>;

export function GetDashboardStatsOptimized():Promise<Record<string, any>>;

export function GetDashboardStatsV2():Promise<main.DashboardStatsV2>;

export function GetDeploymentDataAudit():Promise<main.DeploymentDataAudit>;

export function GetDepositsInTransit(arg1:string):Promise<main.DepositsInTransitResult>;

export function GetDeviceUsers(arg1:string):Promise<Array<infra.DeviceUser>>;

export function GetDiscrepanciesByType(arg1:string,arg2:string,arg3:string):Promise<Array<main.DataDiscrepancy>>;

export function GetFinancialDashboard():Promise<main.FinancialDashboard>;

export function GetFinancialDashboardForYear(arg1:number):Promise<main.FinancialDashboard>;

export function GetInboxDocuments(arg1:string):Promise<Array<main.InboxDocument>>;

export function GetInboxStats():Promise<main.InboxStats>;

export function GetInvoiceWithItems(arg1:string):Promise<finance.Invoice>;

export function GetJobStatus(arg1:string):Promise<main.JobStatusResponse>;

export function GetLatestBookBankReconciliation(arg1:string):Promise<finance.BookBankReconciliation>;

export function GetLicenseRole():Promise<string>;

export function GetMasterDataCleanupAudit():Promise<main.MasterDataCleanupAudit>;

export function GetOrderWithItems(arg1:string):Promise<crm.Order>;

export function GetPhase7RolloutStatus():Promise<main.Phase7RolloutStatus>;

export function GetPilotDeploymentChecklist():Promise<Array<main.PilotChecklistItem>>;

export function GetPilotReadinessSummary():Promise<main.PilotReadinessSummary>;

export function GetPricingRecommendation(arg1:string,arg2:Record<string, any>):Promise<main.PricingRecommendation>;

export function GetRecentEvents(arg1:number):Promise<Array<main.FileSyncState>>;

export function GetRecentJobs(arg1:number):Promise<Array<main.JobSummary>>;

export function GetRecentSyncEvents(arg1:number):Promise<Array<main.FileWatchEvent>>;

export function GetReconciliationStatusSummary():Promise<Array<main.ReconciliationStatusSummary>>;

export function GetReconciliationVariances(arg1:string):Promise<Array<main.VarianceItem>>;

export function GetReportData(arg1:string,arg2:string):Promise<main.ReportData>;

export function GetRole(arg1:number):Promise<infra.Role>;

export function GetRolePermissionsList(arg1:string):Promise<Array<string>>;

export function GetScanProgress(arg1:string):Promise<main.ScanProgress>;

export function GetScanResult(arg1:string):Promise<main.ScanResult>;

export function GetSurvivalMetricsOptimized():Promise<main.SurvivalMetrics>;

export function GetSyncStatus():Promise<Record<string, any>>;

export function GetTranslations(arg1:string):Promise<Record<string, string>>;

export function GetUser(arg1:string):Promise<infra.User>;

export function GetUserPermissions(arg1:string):Promise<Array<string>>;

export function GetWatcherStatus():Promise<Record<string, any>>;

export function GetWeeklyUserActivityReport(arg1:string):Promise<main.UserActivityWeeklyReport>;

export function HasLicensePermission(arg1:string):Promise<boolean>;

export function HasPermission(arg1:string,arg2:string):Promise<boolean>;

export function Import2026BusinessData(arg1:string):Promise<Record<string, any>>;

export function ImportOneDriveDeals(arg1:Array<main.DiscoveredDeal>):Promise<Array<main.OneDriveImportResult>>;

export function InitializeJobQueue():Promise<void>;

export function InvalidateCache(arg1:string):Promise<void>;

export function ListAllDevices():Promise<Array<infra.Device>>;

export function ListCollaborativePendingOperations(arg1:string,arg2:number):Promise<Array<main.CollaborativePendingOperation>>;

export function ListCustomersOptimized(arg1:number):Promise<Array<crm.CustomerMaster>>;

export function ListCustomersPaginated(arg1:number,arg2:number):Promise<main.PaginationResult>;

export function ListInvoicesPaginated(arg1:number,arg2:number,arg3:string):Promise<main.PaginationResult>;

export function ListLicenseKeys():Promise<Array<main.LicenseKey>>;

export function ListOffersPaginated(arg1:number,arg2:number,arg3:string):Promise<main.PaginationResult>;

export function ListOrdersPaginated(arg1:number,arg2:number,arg3:string):Promise<main.PaginationResult>;

export function ListPendingDevices():Promise<Array<infra.Device>>;

export function ListPilotReadinessRows(arg1:boolean):Promise<Array<main.PilotReadinessRow>>;

export function ListProductsOptimized(arg1:number,arg2:boolean):Promise<Array<crm.ProductMaster>>;

export function ListProductsPaginated(arg1:number,arg2:number,arg3:string,arg4:boolean):Promise<main.PaginationResult>;

export function ListPurchaseOrdersPaginated(arg1:number,arg2:number,arg3:string):Promise<main.PaginationResult>;

export function ListRoles():Promise<Array<infra.Role>>;

export function ListSuppliersOptimized(arg1:number):Promise<Array<crm.SupplierMaster>>;

export function ListSuppliersPaginated(arg1:number,arg2:number):Promise<main.PaginationResult>;

export function ListUsers():Promise<Array<infra.User>>;

export function LoginDevice(arg1:string,arg2:string):Promise<device.RegistrationResult>;

export function Logout():Promise<void>;

export function LogoutWithSession():Promise<void>;

export function MarkInboxDocumentProcessed(arg1:string,arg2:string):Promise<void>;

export function NeedsLicenseActivation():Promise<boolean>;

export function OpenExportedFile(arg1:string):Promise<void>;

export function ProcessInboxDocument(arg1:string,arg2:string):Promise<main.InboxProcessResult>;

export function RecalculateInvoiceItemCosts():Promise<Record<string, any>>;

export function ReconcileOfferData(arg1:string):Promise<main.ReconciliationResult>;

export function RecordUserActivityBatch(arg1:Array<main.UserActivityEventInput>):Promise<void>;

export function RecordUserActivityHeartbeat(arg1:main.UserActivityHeartbeatInput):Promise<void>;

export function RefreshAuth():Promise<void>;

export function RefreshAuthWithSession(arg1:infra.UserSession):Promise<void>;

export function RegisterDevice():Promise<device.RegistrationResult>;

export function RegisterReportHandlers():Promise<void>;

export function RequestDeleteApproval(arg1:string,arg2:string,arg3:string,arg4:string):Promise<deletion.Request>;

export function RerunPhase7FollowUpBackfill():Promise<main.Phase7ActionResult>;

export function ResetUserPassword(arg1:string,arg2:string):Promise<void>;

export function RetryCollaborativePendingOperation(arg1:string):Promise<void>;

export function RetryCollaborativePendingOperations(arg1:string,arg2:number):Promise<main.Phase7ActionResult>;

export function RetryFailedSyncs():Promise<number>;

export function ReturnDeposit(arg1:string,arg2:string):Promise<void>;

export function ReviewDeleteApprovalRequest(arg1:string,arg2:string,arg3:string):Promise<deletion.Request>;

export function RevokeLicense(arg1:string):Promise<void>;

export function RunAllDataFixes():Promise<Record<string, any>>;

export function RunIntegrityCheck():Promise<string>;

export function RunScheduledBackupIfDue(arg1:string):Promise<Record<string, any>>;

export function SaveBackupPolicy(arg1:boolean,arg2:number):Promise<infra.BackupPolicy>;

export function ScanOneDrivePaths(arg1:Array<string>):Promise<main.OneDriveScanResult>;

export function SeedAdditionalBankAccounts():Promise<void>;

export function SeedDefaultRoles():Promise<void>;

export function SeedEmployeeKeys():Promise<void>;

export function SeedLicenseKeys():Promise<void>;

export function SetupAdminAccount(arg1:string,arg2:string,arg3:string,arg4:string):Promise<infra.User>;

export function ShutdownJobQueue():Promise<void>;

export function SimulateMargin(arg1:string,arg2:number):Promise<main.MarginSimulation>;

export function StartArchaeologyScan(arg1:string,arg2:boolean,arg3:string):Promise<string>;

export function StartFileWatcher():Promise<void>;

export function StartLogin():Promise<string>;

export function StartUserActivitySession(arg1:string):Promise<main.UserActivitySession>;

export function StopFileWatcher():Promise<void>;

export function StoreCustomerGraph(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function TimeNow():Promise<time.Time>;

export function TriggerBackup():Promise<Record<string, any>>;

export function TriggerCollaborativeSyncNow():Promise<void>;

export function TriggerSync(arg1:string):Promise<void>;

export function UnblockDevice(arg1:string):Promise<void>;

export function UpdateBookBankReconciliation(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number,arg7:string):Promise<finance.BookBankReconciliation>;

export function UpdateBookBankReconciliationAdjustments(arg1:string,arg2:number,arg3:number):Promise<void>;

export function UpdateLicenseDisplayName(arg1:string,arg2:string):Promise<main.LicenseKey>;

export function UpdatePilotDeploymentChecklistItem(arg1:string,arg2:boolean,arg3:string):Promise<Array<main.PilotChecklistItem>>;

export function UpdateUser(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean):Promise<void>;

export function ValidateCSRFToken(arg1:string):Promise<boolean>;

export function ValidateLicense():Promise<main.LicenseValidationResult>;

export function ValidateOneDrivePath(arg1:string):Promise<Record<string, any>>;

export function WriteMasterDataCleanupReport(arg1:string):Promise<string>;
