// Code generated by capnpc-go. DO NOT EDIT.

package syncschema

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	math "math"
	common "ph_holdings_app/schemas/go/common"
)

type FileSyncStatus uint16

// FileSyncStatus_TypeID is the unique identifier for the type FileSyncStatus.
const FileSyncStatus_TypeID = 0x893595a82e233617

// Values of FileSyncStatus.
const (
	FileSyncStatus_queued       FileSyncStatus = 0
	FileSyncStatus_processing   FileSyncStatus = 1
	FileSyncStatus_synced       FileSyncStatus = 2
	FileSyncStatus_failed       FileSyncStatus = 3
	FileSyncStatus_conflict     FileSyncStatus = 4
	FileSyncStatus_skippedLarge FileSyncStatus = 5
)

// String returns the enum's constant name.
func (c FileSyncStatus) String() string {
	switch c {
	case FileSyncStatus_queued:
		return "queued"
	case FileSyncStatus_processing:
		return "processing"
	case FileSyncStatus_synced:
		return "synced"
	case FileSyncStatus_failed:
		return "failed"
	case FileSyncStatus_conflict:
		return "conflict"
	case FileSyncStatus_skippedLarge:
		return "skippedLarge"

	default:
		return ""
	}
}

// FileSyncStatusFromString returns the enum value with a name,
// or the zero value if there's no such value.
func FileSyncStatusFromString(c string) FileSyncStatus {
	switch c {
	case "queued":
		return FileSyncStatus_queued
	case "processing":
		return FileSyncStatus_processing
	case "synced":
		return FileSyncStatus_synced
	case "failed":
		return FileSyncStatus_failed
	case "conflict":
		return FileSyncStatus_conflict
	case "skippedLarge":
		return FileSyncStatus_skippedLarge

	default:
		return 0
	}
}

type FileSyncStatus_List = capnp.EnumList[FileSyncStatus]

func NewFileSyncStatus_List(s *capnp.Segment, sz int32) (FileSyncStatus_List, error) {
	return capnp.NewEnumList[FileSyncStatus](s, sz)
}

type SyncDirection uint16

// SyncDirection_TypeID is the unique identifier for the type SyncDirection.
const SyncDirection_TypeID = 0xd2d58bc5d899fc04

// Values of SyncDirection.
const (
	SyncDirection_push SyncDirection = 0
	SyncDirection_pull SyncDirection = 1
)

// String returns the enum's constant name.
func (c SyncDirection) String() string {
	switch c {
	case SyncDirection_push:
		return "push"
	case SyncDirection_pull:
		return "pull"

	default:
		return ""
	}
}

// SyncDirectionFromString returns the enum value with a name,
// or the zero value if there's no such value.
func SyncDirectionFromString(c string) SyncDirection {
	switch c {
	case "push":
		return SyncDirection_push
	case "pull":
		return SyncDirection_pull

	default:
		return 0
	}
}

type SyncDirection_List = capnp.EnumList[SyncDirection]

func NewSyncDirection_List(s *capnp.Segment, sz int32) (SyncDirection_List, error) {
	return capnp.NewEnumList[SyncDirection](s, sz)
}

type ConflictState uint16

// ConflictState_TypeID is the unique identifier for the type ConflictState.
const ConflictState_TypeID = 0xdd64913838d3e1d5

// Values of ConflictState.
const (
	ConflictState_none       ConflictState = 0
	ConflictState_localWins  ConflictState = 1
	ConflictState_remoteWins ConflictState = 2
)

// String returns the enum's constant name.
func (c ConflictState) String() string {
	switch c {
	case ConflictState_none:
		return "none"
	case ConflictState_localWins:
		return "localWins"
	case ConflictState_remoteWins:
		return "remoteWins"

	default:
		return ""
	}
}

// ConflictStateFromString returns the enum value with a name,
// or the zero value if there's no such value.
func ConflictStateFromString(c string) ConflictState {
	switch c {
	case "none":
		return ConflictState_none
	case "localWins":
		return ConflictState_localWins
	case "remoteWins":
		return ConflictState_remoteWins

	default:
		return 0
	}
}

type ConflictState_List = capnp.EnumList[ConflictState]

func NewConflictState_List(s *capnp.Segment, sz int32) (ConflictState_List, error) {
	return capnp.NewEnumList[ConflictState](s, sz)
}

type TallyImportStatus uint16

// TallyImportStatus_TypeID is the unique identifier for the type TallyImportStatus.
const TallyImportStatus_TypeID = 0xf298c7ecc5fc30a7

// Values of TallyImportStatus.
const (
	TallyImportStatus_pending   TallyImportStatus = 0
	TallyImportStatus_imported  TallyImportStatus = 1
	TallyImportStatus_matched   TallyImportStatus = 2
	TallyImportStatus_duplicate TallyImportStatus = 3
	TallyImportStatus_error     TallyImportStatus = 4
)

// String returns the enum's constant name.
func (c TallyImportStatus) String() string {
	switch c {
	case TallyImportStatus_pending:
		return "pending"
	case TallyImportStatus_imported:
		return "imported"
	case TallyImportStatus_matched:
		return "matched"
	case TallyImportStatus_duplicate:
		return "duplicate"
	case TallyImportStatus_error:
		return "error"

	default:
		return ""
	}
}

// TallyImportStatusFromString returns the enum value with a name,
// or the zero value if there's no such value.
func TallyImportStatusFromString(c string) TallyImportStatus {
	switch c {
	case "pending":
		return TallyImportStatus_pending
	case "imported":
		return TallyImportStatus_imported
	case "matched":
		return TallyImportStatus_matched
	case "duplicate":
		return TallyImportStatus_duplicate
	case "error":
		return TallyImportStatus_error

	default:
		return 0
	}
}

type TallyImportStatus_List = capnp.EnumList[TallyImportStatus]

func NewTallyImportStatus_List(s *capnp.Segment, sz int32) (TallyImportStatus_List, error) {
	return capnp.NewEnumList[TallyImportStatus](s, sz)
}

type FileWatchEvent capnp.Struct

// FileWatchEvent_TypeID is the unique identifier for the type FileWatchEvent.
const FileWatchEvent_TypeID = 0xabcd96301015f42b

func NewFileWatchEvent(s *capnp.Segment) (FileWatchEvent, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return FileWatchEvent(st), err
}

func NewRootFileWatchEvent(s *capnp.Segment) (FileWatchEvent, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return FileWatchEvent(st), err
}

func ReadRootFileWatchEvent(msg *capnp.Message) (FileWatchEvent, error) {
	root, err := msg.Root()
	return FileWatchEvent(root.Struct()), err
}

func (s FileWatchEvent) String() string {
	str, _ := text.Marshal(0xabcd96301015f42b, capnp.Struct(s))
	return str
}

func (s FileWatchEvent) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (FileWatchEvent) DecodeFromPtr(p capnp.Ptr) FileWatchEvent {
	return FileWatchEvent(capnp.Struct{}.DecodeFromPtr(p))
}

func (s FileWatchEvent) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s FileWatchEvent) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s FileWatchEvent) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s FileWatchEvent) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s FileWatchEvent) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s FileWatchEvent) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s FileWatchEvent) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s FileWatchEvent) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s FileWatchEvent) FilePath() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s FileWatchEvent) HasFilePath() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s FileWatchEvent) FilePathBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s FileWatchEvent) SetFilePath(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s FileWatchEvent) EventType() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s FileWatchEvent) HasEventType() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s FileWatchEvent) EventTypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s FileWatchEvent) SetEventType(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

// FileWatchEvent_List is a list of FileWatchEvent.
type FileWatchEvent_List = capnp.StructList[FileWatchEvent]

// NewFileWatchEvent creates a new list of FileWatchEvent.
func NewFileWatchEvent_List(s *capnp.Segment, sz int32) (FileWatchEvent_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return capnp.StructList[FileWatchEvent](l), err
}

// FileWatchEvent_Future is a wrapper for a FileWatchEvent promised by a client call.
type FileWatchEvent_Future struct{ *capnp.Future }

func (f FileWatchEvent_Future) Struct() (FileWatchEvent, error) {
	p, err := f.Future.Ptr()
	return FileWatchEvent(p.Struct()), err
}
func (p FileWatchEvent_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}

type FileSyncState capnp.Struct

// FileSyncState_TypeID is the unique identifier for the type FileSyncState.
const FileSyncState_TypeID = 0x93a318cbcbc091a9

func NewFileSyncState(s *capnp.Segment) (FileSyncState, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 8})
	return FileSyncState(st), err
}

func NewRootFileSyncState(s *capnp.Segment) (FileSyncState, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 8})
	return FileSyncState(st), err
}

func ReadRootFileSyncState(msg *capnp.Message) (FileSyncState, error) {
	root, err := msg.Root()
	return FileSyncState(root.Struct()), err
}

func (s FileSyncState) String() string {
	str, _ := text.Marshal(0x93a318cbcbc091a9, capnp.Struct(s))
	return str
}

func (s FileSyncState) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (FileSyncState) DecodeFromPtr(p capnp.Ptr) FileSyncState {
	return FileSyncState(capnp.Struct{}.DecodeFromPtr(p))
}

func (s FileSyncState) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s FileSyncState) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s FileSyncState) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s FileSyncState) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s FileSyncState) Path() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s FileSyncState) HasPath() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s FileSyncState) PathBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s FileSyncState) SetPath(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s FileSyncState) EventType() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s FileSyncState) HasEventType() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s FileSyncState) EventTypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s FileSyncState) SetEventType(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s FileSyncState) Status() FileSyncStatus {
	return FileSyncStatus(capnp.Struct(s).Uint16(0))
}

func (s FileSyncState) SetStatus(v FileSyncStatus) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s FileSyncState) LastModified() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s FileSyncState) HasLastModified() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s FileSyncState) LastModifiedBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s FileSyncState) SetLastModified(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s FileSyncState) LastSynced() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s FileSyncState) HasLastSynced() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s FileSyncState) LastSyncedBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s FileSyncState) SetLastSynced(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s FileSyncState) RemoteHash() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s FileSyncState) HasRemoteHash() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s FileSyncState) RemoteHashBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s FileSyncState) SetRemoteHash(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s FileSyncState) LocalHash() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s FileSyncState) HasLocalHash() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s FileSyncState) LocalHashBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s FileSyncState) SetLocalHash(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s FileSyncState) RetryCount() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s FileSyncState) SetRetryCount(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s FileSyncState) LastError() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s FileSyncState) HasLastError() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s FileSyncState) LastErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s FileSyncState) SetLastError(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

func (s FileSyncState) Metadata() (common.KeyValue_List, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return common.KeyValue_List(p.List()), err
}

func (s FileSyncState) HasMetadata() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s FileSyncState) SetMetadata(v common.KeyValue_List) error {
	return capnp.Struct(s).SetPtr(7, v.ToPtr())
}

// NewMetadata sets the metadata field to a newly
// allocated common.KeyValue_List, preferring placement in s's segment.
func (s FileSyncState) NewMetadata(n int32) (common.KeyValue_List, error) {
	l, err := common.NewKeyValue_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return common.KeyValue_List{}, err
	}
	err = capnp.Struct(s).SetPtr(7, l.ToPtr())
	return l, err
}

// FileSyncState_List is a list of FileSyncState.
type FileSyncState_List = capnp.StructList[FileSyncState]

// NewFileSyncState creates a new list of FileSyncState.
func NewFileSyncState_List(s *capnp.Segment, sz int32) (FileSyncState_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 8}, sz)
	return capnp.StructList[FileSyncState](l), err
}

// FileSyncState_Future is a wrapper for a FileSyncState promised by a client call.
type FileSyncState_Future struct{ *capnp.Future }

func (f FileSyncState_Future) Struct() (FileSyncState, error) {
	p, err := f.Future.Ptr()
	return FileSyncState(p.Struct()), err
}

type SyncStatus capnp.Struct

// SyncStatus_TypeID is the unique identifier for the type SyncStatus.
const SyncStatus_TypeID = 0xc23f0fc41176a06c

func NewSyncStatus(s *capnp.Segment) (SyncStatus, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return SyncStatus(st), err
}

func NewRootSyncStatus(s *capnp.Segment) (SyncStatus, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return SyncStatus(st), err
}

func ReadRootSyncStatus(msg *capnp.Message) (SyncStatus, error) {
	root, err := msg.Root()
	return SyncStatus(root.Struct()), err
}

func (s SyncStatus) String() string {
	str, _ := text.Marshal(0xc23f0fc41176a06c, capnp.Struct(s))
	return str
}

func (s SyncStatus) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SyncStatus) DecodeFromPtr(p capnp.Ptr) SyncStatus {
	return SyncStatus(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SyncStatus) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SyncStatus) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SyncStatus) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SyncStatus) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SyncStatus) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s SyncStatus) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SyncStatus) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s SyncStatus) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s SyncStatus) FilePath() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s SyncStatus) HasFilePath() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s SyncStatus) FilePathBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s SyncStatus) SetFilePath(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s SyncStatus) Status() FileSyncStatus {
	return FileSyncStatus(capnp.Struct(s).Uint16(0))
}

func (s SyncStatus) SetStatus(v FileSyncStatus) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s SyncStatus) LastSyncTime() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s SyncStatus) HasLastSyncTime() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s SyncStatus) LastSyncTimeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s SyncStatus) SetLastSyncTime(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

// SyncStatus_List is a list of SyncStatus.
type SyncStatus_List = capnp.StructList[SyncStatus]

// NewSyncStatus creates a new list of SyncStatus.
func NewSyncStatus_List(s *capnp.Segment, sz int32) (SyncStatus_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[SyncStatus](l), err
}

// SyncStatus_Future is a wrapper for a SyncStatus promised by a client call.
type SyncStatus_Future struct{ *capnp.Future }

func (f SyncStatus_Future) Struct() (SyncStatus, error) {
	p, err := f.Future.Ptr()
	return SyncStatus(p.Struct()), err
}
func (p SyncStatus_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}

type SyncRecord capnp.Struct

// SyncRecord_TypeID is the unique identifier for the type SyncRecord.
const SyncRecord_TypeID = 0xe276adb0502a9bb2

func NewSyncRecord(s *capnp.Segment) (SyncRecord, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 4})
	return SyncRecord(st), err
}

func NewRootSyncRecord(s *capnp.Segment) (SyncRecord, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 4})
	return SyncRecord(st), err
}

func ReadRootSyncRecord(msg *capnp.Message) (SyncRecord, error) {
	root, err := msg.Root()
	return SyncRecord(root.Struct()), err
}

func (s SyncRecord) String() string {
	str, _ := text.Marshal(0xe276adb0502a9bb2, capnp.Struct(s))
	return str
}

func (s SyncRecord) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SyncRecord) DecodeFromPtr(p capnp.Ptr) SyncRecord {
	return SyncRecord(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SyncRecord) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SyncRecord) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SyncRecord) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SyncRecord) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SyncRecord) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s SyncRecord) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SyncRecord) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s SyncRecord) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s SyncRecord) SyncTable() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s SyncRecord) HasSyncTable() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s SyncRecord) SyncTableBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s SyncRecord) SetSyncTable(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s SyncRecord) RecordId() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s SyncRecord) HasRecordId() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s SyncRecord) RecordIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s SyncRecord) SetRecordId(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s SyncRecord) SyncedAt() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s SyncRecord) HasSyncedAt() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s SyncRecord) SyncedAtBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s SyncRecord) SetSyncedAt(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s SyncRecord) Direction() SyncDirection {
	return SyncDirection(capnp.Struct(s).Uint16(0))
}

func (s SyncRecord) SetDirection(v SyncDirection) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s SyncRecord) RemoteVersion() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s SyncRecord) SetRemoteVersion(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s SyncRecord) LocalVersion() int64 {
	return int64(capnp.Struct(s).Uint64(16))
}

func (s SyncRecord) SetLocalVersion(v int64) {
	capnp.Struct(s).SetUint64(16, uint64(v))
}

func (s SyncRecord) ConflictState() ConflictState {
	return ConflictState(capnp.Struct(s).Uint16(2))
}

func (s SyncRecord) SetConflictState(v ConflictState) {
	capnp.Struct(s).SetUint16(2, uint16(v))
}

// SyncRecord_List is a list of SyncRecord.
type SyncRecord_List = capnp.StructList[SyncRecord]

// NewSyncRecord creates a new list of SyncRecord.
func NewSyncRecord_List(s *capnp.Segment, sz int32) (SyncRecord_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 4}, sz)
	return capnp.StructList[SyncRecord](l), err
}

// SyncRecord_Future is a wrapper for a SyncRecord promised by a client call.
type SyncRecord_Future struct{ *capnp.Future }

func (f SyncRecord_Future) Struct() (SyncRecord, error) {
	p, err := f.Future.Ptr()
	return SyncRecord(p.Struct()), err
}
func (p SyncRecord_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}

type TallyInvoiceImport capnp.Struct

// TallyInvoiceImport_TypeID is the unique identifier for the type TallyInvoiceImport.
const TallyInvoiceImport_TypeID = 0xa384105a8098ee80

func NewTallyInvoiceImport(s *capnp.Segment) (TallyInvoiceImport, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 7})
	return TallyInvoiceImport(st), err
}

func NewRootTallyInvoiceImport(s *capnp.Segment) (TallyInvoiceImport, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 7})
	return TallyInvoiceImport(st), err
}

func ReadRootTallyInvoiceImport(msg *capnp.Message) (TallyInvoiceImport, error) {
	root, err := msg.Root()
	return TallyInvoiceImport(root.Struct()), err
}

func (s TallyInvoiceImport) String() string {
	str, _ := text.Marshal(0xa384105a8098ee80, capnp.Struct(s))
	return str
}

func (s TallyInvoiceImport) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TallyInvoiceImport) DecodeFromPtr(p capnp.Ptr) TallyInvoiceImport {
	return TallyInvoiceImport(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TallyInvoiceImport) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TallyInvoiceImport) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TallyInvoiceImport) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TallyInvoiceImport) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TallyInvoiceImport) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s TallyInvoiceImport) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TallyInvoiceImport) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s TallyInvoiceImport) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s TallyInvoiceImport) ImportBatch() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s TallyInvoiceImport) HasImportBatch() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s TallyInvoiceImport) ImportBatchBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s TallyInvoiceImport) SetImportBatch(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s TallyInvoiceImport) Year() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s TallyInvoiceImport) SetYear(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s TallyInvoiceImport) InvoiceNumber() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s TallyInvoiceImport) HasInvoiceNumber() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s TallyInvoiceImport) InvoiceNumberBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s TallyInvoiceImport) SetInvoiceNumber(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s TallyInvoiceImport) CustomerName() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s TallyInvoiceImport) HasCustomerName() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s TallyInvoiceImport) CustomerNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s TallyInvoiceImport) SetCustomerName(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s TallyInvoiceImport) MatchedCustomerId() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s TallyInvoiceImport) HasMatchedCustomerId() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s TallyInvoiceImport) MatchedCustomerIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s TallyInvoiceImport) SetMatchedCustomerId(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s TallyInvoiceImport) InvoiceDate() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s TallyInvoiceImport) HasInvoiceDate() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s TallyInvoiceImport) InvoiceDateBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s TallyInvoiceImport) SetInvoiceDate(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s TallyInvoiceImport) Amount() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s TallyInvoiceImport) SetAmount(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

func (s TallyInvoiceImport) Currency() common.CurrencyCode {
	return common.CurrencyCode(capnp.Struct(s).Uint16(16))
}

func (s TallyInvoiceImport) SetCurrency(v common.CurrencyCode) {
	capnp.Struct(s).SetUint16(16, uint16(v))
}

func (s TallyInvoiceImport) Status() TallyImportStatus {
	return TallyImportStatus(capnp.Struct(s).Uint16(18))
}

func (s TallyInvoiceImport) SetStatus(v TallyImportStatus) {
	capnp.Struct(s).SetUint16(18, uint16(v))
}

func (s TallyInvoiceImport) RawData() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s TallyInvoiceImport) HasRawData() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s TallyInvoiceImport) RawDataBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s TallyInvoiceImport) SetRawData(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

// TallyInvoiceImport_List is a list of TallyInvoiceImport.
type TallyInvoiceImport_List = capnp.StructList[TallyInvoiceImport]

// NewTallyInvoiceImport creates a new list of TallyInvoiceImport.
func NewTallyInvoiceImport_List(s *capnp.Segment, sz int32) (TallyInvoiceImport_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 7}, sz)
	return capnp.StructList[TallyInvoiceImport](l), err
}

// TallyInvoiceImport_Future is a wrapper for a TallyInvoiceImport promised by a client call.
type TallyInvoiceImport_Future struct{ *capnp.Future }

func (f TallyInvoiceImport_Future) Struct() (TallyInvoiceImport, error) {
	p, err := f.Future.Ptr()
	return TallyInvoiceImport(p.Struct()), err
}
func (p TallyInvoiceImport_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}

type TallyPurchaseImport capnp.Struct

// TallyPurchaseImport_TypeID is the unique identifier for the type TallyPurchaseImport.
const TallyPurchaseImport_TypeID = 0xa7f3f6376ff296f9

func NewTallyPurchaseImport(s *capnp.Segment) (TallyPurchaseImport, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 7})
	return TallyPurchaseImport(st), err
}

func NewRootTallyPurchaseImport(s *capnp.Segment) (TallyPurchaseImport, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 7})
	return TallyPurchaseImport(st), err
}

func ReadRootTallyPurchaseImport(msg *capnp.Message) (TallyPurchaseImport, error) {
	root, err := msg.Root()
	return TallyPurchaseImport(root.Struct()), err
}

func (s TallyPurchaseImport) String() string {
	str, _ := text.Marshal(0xa7f3f6376ff296f9, capnp.Struct(s))
	return str
}

func (s TallyPurchaseImport) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TallyPurchaseImport) DecodeFromPtr(p capnp.Ptr) TallyPurchaseImport {
	return TallyPurchaseImport(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TallyPurchaseImport) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TallyPurchaseImport) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TallyPurchaseImport) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TallyPurchaseImport) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TallyPurchaseImport) Base() (common.Base, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return common.Base(p.Struct()), err
}

func (s TallyPurchaseImport) HasBase() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TallyPurchaseImport) SetBase(v common.Base) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBase sets the base field to a newly
// allocated common.Base struct, preferring placement in s's segment.
func (s TallyPurchaseImport) NewBase() (common.Base, error) {
	ss, err := common.NewBase(capnp.Struct(s).Segment())
	if err != nil {
		return common.Base{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s TallyPurchaseImport) ImportBatch() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s TallyPurchaseImport) HasImportBatch() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s TallyPurchaseImport) ImportBatchBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s TallyPurchaseImport) SetImportBatch(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s TallyPurchaseImport) Year() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s TallyPurchaseImport) SetYear(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s TallyPurchaseImport) InvoiceNumber() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s TallyPurchaseImport) HasInvoiceNumber() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s TallyPurchaseImport) InvoiceNumberBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s TallyPurchaseImport) SetInvoiceNumber(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s TallyPurchaseImport) SupplierName() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s TallyPurchaseImport) HasSupplierName() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s TallyPurchaseImport) SupplierNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s TallyPurchaseImport) SetSupplierName(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s TallyPurchaseImport) MatchedSupplierId() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s TallyPurchaseImport) HasMatchedSupplierId() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s TallyPurchaseImport) MatchedSupplierIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s TallyPurchaseImport) SetMatchedSupplierId(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s TallyPurchaseImport) InvoiceDate() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s TallyPurchaseImport) HasInvoiceDate() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s TallyPurchaseImport) InvoiceDateBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s TallyPurchaseImport) SetInvoiceDate(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s TallyPurchaseImport) Amount() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s TallyPurchaseImport) SetAmount(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

func (s TallyPurchaseImport) Currency() common.CurrencyCode {
	return common.CurrencyCode(capnp.Struct(s).Uint16(16))
}

func (s TallyPurchaseImport) SetCurrency(v common.CurrencyCode) {
	capnp.Struct(s).SetUint16(16, uint16(v))
}

func (s TallyPurchaseImport) Status() TallyImportStatus {
	return TallyImportStatus(capnp.Struct(s).Uint16(18))
}

func (s TallyPurchaseImport) SetStatus(v TallyImportStatus) {
	capnp.Struct(s).SetUint16(18, uint16(v))
}

func (s TallyPurchaseImport) RawData() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s TallyPurchaseImport) HasRawData() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s TallyPurchaseImport) RawDataBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s TallyPurchaseImport) SetRawData(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

// TallyPurchaseImport_List is a list of TallyPurchaseImport.
type TallyPurchaseImport_List = capnp.StructList[TallyPurchaseImport]

// NewTallyPurchaseImport creates a new list of TallyPurchaseImport.
func NewTallyPurchaseImport_List(s *capnp.Segment, sz int32) (TallyPurchaseImport_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 7}, sz)
	return capnp.StructList[TallyPurchaseImport](l), err
}

// TallyPurchaseImport_Future is a wrapper for a TallyPurchaseImport promised by a client call.
type TallyPurchaseImport_Future struct{ *capnp.Future }

func (f TallyPurchaseImport_Future) Struct() (TallyPurchaseImport, error) {
	p, err := f.Future.Ptr()
	return TallyPurchaseImport(p.Struct()), err
}
func (p TallyPurchaseImport_Future) Base() common.Base_Future {
	return common.Base_Future{Future: p.Future.Field(0, nil)}
}

type SyncRunStatus capnp.Struct

// SyncRunStatus_TypeID is the unique identifier for the type SyncRunStatus.
const SyncRunStatus_TypeID = 0xf9b3a16dfdc3136d

func NewSyncRunStatus(s *capnp.Segment) (SyncRunStatus, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 2})
	return SyncRunStatus(st), err
}

func NewRootSyncRunStatus(s *capnp.Segment) (SyncRunStatus, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 2})
	return SyncRunStatus(st), err
}

func ReadRootSyncRunStatus(msg *capnp.Message) (SyncRunStatus, error) {
	root, err := msg.Root()
	return SyncRunStatus(root.Struct()), err
}

func (s SyncRunStatus) String() string {
	str, _ := text.Marshal(0xf9b3a16dfdc3136d, capnp.Struct(s))
	return str
}

func (s SyncRunStatus) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SyncRunStatus) DecodeFromPtr(p capnp.Ptr) SyncRunStatus {
	return SyncRunStatus(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SyncRunStatus) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SyncRunStatus) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SyncRunStatus) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SyncRunStatus) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SyncRunStatus) LastSyncStatus() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s SyncRunStatus) HasLastSyncStatus() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SyncRunStatus) LastSyncStatusBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s SyncRunStatus) SetLastSyncStatus(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s SyncRunStatus) LastSyncTime() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s SyncRunStatus) HasLastSyncTime() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s SyncRunStatus) LastSyncTimeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s SyncRunStatus) SetLastSyncTime(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s SyncRunStatus) CloudSyncEnabled() bool {
	return capnp.Struct(s).Bit(0)
}

func (s SyncRunStatus) SetCloudSyncEnabled(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s SyncRunStatus) IsRunning() bool {
	return capnp.Struct(s).Bit(1)
}

func (s SyncRunStatus) SetIsRunning(v bool) {
	capnp.Struct(s).SetBit(1, v)
}

func (s SyncRunStatus) PendingPushCount() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s SyncRunStatus) SetPendingPushCount(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s SyncRunStatus) PendingPullCount() int64 {
	return int64(capnp.Struct(s).Uint64(16))
}

func (s SyncRunStatus) SetPendingPullCount(v int64) {
	capnp.Struct(s).SetUint64(16, uint64(v))
}

func (s SyncRunStatus) FailedCount() int64 {
	return int64(capnp.Struct(s).Uint64(24))
}

func (s SyncRunStatus) SetFailedCount(v int64) {
	capnp.Struct(s).SetUint64(24, uint64(v))
}

// SyncRunStatus_List is a list of SyncRunStatus.
type SyncRunStatus_List = capnp.StructList[SyncRunStatus]

// NewSyncRunStatus creates a new list of SyncRunStatus.
func NewSyncRunStatus_List(s *capnp.Segment, sz int32) (SyncRunStatus_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 32, PointerCount: 2}, sz)
	return capnp.StructList[SyncRunStatus](l), err
}

// SyncRunStatus_Future is a wrapper for a SyncRunStatus promised by a client call.
type SyncRunStatus_Future struct{ *capnp.Future }

func (f SyncRunStatus_Future) Struct() (SyncRunStatus, error) {
	p, err := f.Future.Ptr()
	return SyncRunStatus(p.Struct()), err
}

const schema_d0b8835cc94b27a5 = "x\xda\xecWm\x88\x1dg\x15>g\xde{\xf7\xab\xdb" +
	"\xceN\xe7\x06Si\xd9]b\xe2\xee\xf5\xb6&M\xd7" +
	"\xa4K\xcbfw\xb3\xb2\x1bc\xbdsgi0\xac\xd0" +
	"wg\xde\xe4N\x9c;3\x99\x8f\x95+\xd6\xb4\xa8?" +
	"Z\x11I\xc5~\xf8\x01\x86R\xaa\x88T\xfc\x00\x7f4" +
	"X\xd4\xd0\x86Xi\xb4\x81\x16\x1a\xb0\xd2b\x91*5" +
	"F1\xb0a\xe4\xbcs\xf7\xce$\x9b\x8d\xf8C\xf0\x87" +
	"\xe4G&\xcf<\xf7\xccy\xcf\xf3\xbc\xe7\x9cl\xdf6" +
	"\xb8\xa7\xb4\xe3\xc6\xe7\xa6A1W\x95rO\xfa\xbe\x8f" +
	"l\xb9\xe3\xbb_\x9fx\x044]I\x9f\xf9\xe0\xc7N" +
	"/}\xe1g\xaf\x00\xe0\xce\x93#7\xa3\xfe\xf2H/" +
	"\x80~z\xe4\x09\xc0\xf4{\xc7_8sf\xf3\xd3_" +
	"\x03C\xc7\x02\xb5\xdc\xd7\x0b\xb0\xf3\x96\xd1\x01\xd4\xc7G" +
	"\xe9q\xeb\xe8.\x050}\xe8/O>tp\xe8\x8b" +
	"O\x13\x9d\x15\xe8\xbd\xc49\xbe\xe5N\xd4Ol\xa1\xc7" +
	"oo\xf1\x89~\xe9\xf1\x0b\xfe\xae\x7f\xfc\xed\xd9k\xd2" +
	"wl\x9bD}z\x1b=\xde\xbbM\xd2?tq\xd3" +
	"\xd0\xf6\xc7_\xfe>h:\x16\xd8\x8c(g\xc7nF" +
	"\xfd\xcd1\xca\xfc\xfc\xd8s\x80\xa9\xfb\x9d\x15\xedW\xea" +
	"\xd4/(\xf6\xd5l\xfd\xc1\xf1\x0b\xfa#\xe3\xf4\xf4\xa5" +
	"\xf1?\x02\xa6\xa5\xd5\xa7^;\xf5\xe5s\xbf]W\x10" +
	"^\x1d@\xfdh\x95\x98\xad\xea.\xc0\xf4\xdc\x9b\xbf\xdb" +
	"\xbd\xfb\xb8}~\x1d\xf3(1\x1f\x96\xcc\x07\xab\x9f\x00" +
	"L\x7f\xf4\xcdj\xfd\x87?X\xf9\xc3\xd5\x87+\x11\xe5" +
	"\xa9\xea\x05\xfd\x19\"\xef<Q}\x11\x01\xd3g\xb7\xaf" +
	"\x9ez\xf7\xc5'/\xac\x8b\xfbp\xad\x8a\xfa\xf1\x1a\xfd" +
	"\xe8+\xb5c\x80iK\xff\xe5\xe5\xd6\x89\x1f_\xa2\xb8" +
	"\xa5B\\\x85\xa2\x9d\xae\x0d\xa0\xfe:\xb1w\x9e\xab}" +
	"\x15!\xbd\xe2\xcf\xc94\xb2\x9a\xa2\xc5\xa3\x0f\xb3\xa8\xed" +
	"YwX<\xf0\x82\xc9\x8f:\xae0\xdb\x9ee\xc6<" +
	"N0\xaa#\x1a\x9bQ\x01\xd0\xa6'\x01\x10\xb5\xbb\x0f" +
	"\x02\xa0\xa2M\xd0\xbf\x98v;\xfdU\xd2\xb6\xee\x03\xc0" +
	"\xb26z\x04`\xeah\"\x12a\xa7A\xe8[\"\x8a" +
	"\x1c`\xde\xe1)\x8a/\xec\xa9C\xdcq\x85\x9dZ\xbe" +
	"w\xc8u\xac\x18\x00\xd2\xe8\xd3N\x10\x08{?\xa8<" +
	"<,\xfemF\x02\x802\x1ac%\x80\x12\x02\xe8\xfd" +
	"X\x050K\xc8\xd0\x1cB\x055\xc4\x0a\x12~#6" +
	"\x00\xccA\xc27\xa3\x82\xa8T\xe8\x10\xfa&\x9c\x040" +
	"\x87\x08\xbe\x95\xe8L\xa9 \x03\xd0o\xc1#\x00\xe6f" +
	"\xc2?@x\x89U\xb0\x04\xa0\x8f\xe2A\x00s\x84\xf0" +
	"\x1a\xe1\xe5R\x05\xcb\x00\xfa\xb8\xc4\xc7\x08\xbf\x8b\xf0\x9e" +
	"r\x05{\x00\xf4\x1d\xf2\xb3\xdb\x09\xbf\x87\xf0^\xac " +
	"\x89u\xb7\xe4\xef&|/\xe1}=\x15\xec\x03\xd0\xa7" +
	"%\x7f\x0f\xe1\xfb\x09\xef\xef\xad`?\x80\xbe\x80\xfb\x00" +
	"\xccy\xc2mTP\x0dx\xdc\xc4APp\x100\x15" +
	"+\xc2\x8b\x17\xdb\x01\xa0X\xc3\xa6\"\x92+B5\xbf" +
	"\xcd\x80\xa8\x92\xf3y\x14\x7f\xdc\xb7\x1dP\x0f9\xc2\xee" +
	"\xc6 \x98\x8a\x0a\xac\x00\x86\xa2\xe5\xc7b\x9e\x03\x8b\xf2" +
	"\xaf\xb9\xbe\xc5\xddy\x1e\x016\x0b\xc48l\xcf\xfa\x09" +
	"0/\xc62(X\xee\x84\x9c\x0bC\x1f0\xec\x12[" +
	"\"\xe66\x8f9\x00\xe0M\x80u\x868\x94N|\xe3" +
	"\xf3O0^\xfd9\xa5x\x13\xe05E_\xe4\xae\xdb" +
	"^\xf0V|\xc7\x12\x0b\xc3\xad\xc0\x0fc\x12\xbe\xd6\x15" +
	"~\xab\x14>WfM\xf8q\\.*\xb3&\xfc\x0e" +
	"I\xaf\x11\xbc\xbb(\xfc\x04\x86\x00\xe6]\x84\xef)\x0a" +
	"\x7f\xaf4\xc4=\x84\xcf\x17\x85\x9f\xc3\xc7\xd6\x84Y," +
	"\x0ao\xc8\xcf\xd6\x09_*\x0a\xffIi\xb8E\xc2\x1f" +
	"\x90\xc2\xf7e\xc2\x7fJ\x0a\xbcDxS\x0a\xdf\x9f\x09" +
	"/$\xff\x01\xc2]\xc2\x07z*8\x00\xa0;8\x03" +
	"`\xda\x84\x07d\x88e\x1e\x09\x1cJ\x95\xdf\xfc\xe9\xf2" +
	"\xcc\xb7.\x9e\xa5R\x0e\x01\xa6\x8e\xac\xd4\x0c\x87\xde\xd8" +
	"\xea\xca\xa5\xb6\x05\x0f\xbb29YQ\xef\x83\xe1\xa4\xb5" +
	",r\xa9\xac$\x8a\xfd\x96\x08A\xbd\x8f\xb7D\xae " +
	"\x8f\xad\xa6\xb0g\xb1\xf3z\x01s\xbftB\xed\x85^" +
	"\x1e\xe7V\xe4-?\xf1b\xbc\x01\x14\xbcA\xc6\x0dC" +
	"\xe1Ym\xb2\x80\x9a\xbe\xff\xad\xea\x19k\xec\xb1\xe7;" +
	"\xf6\xcc}\xdbmy\xd9\x8bc!\xff\xcc^\x1e\xf3\xee" +
	"\xb764I=\x09\xad&\x8f\xc4\xd4\xc2\xff]\xf2\xdf" +
	"wI\x94\x04\x81\xebl\xe4\x12\x13;\xaf\xff\x97\\B" +
	"\xf3\xe3\x00\xe57\xb7\"<\x94\x06\x19\\3\x886W" +
	"\x050\xf604\xf6\xe7\xee\xd0\x16\xf6\x01\x18\xf3\x0c\x8d" +
	"E\x055%\xf3\x86f4\x00\x8c:Cci\xe3\xc2" +
	"\x1er\\Q\xe7q\x93Nq\x9dn\xddMS)\xa4" +
	")G\xdc\xb0<(\xa58\xd4M\x91S\x8aK\x0c\x8d" +
	"f!EA)\xda\x0c\x8d\xa0\xeb^\xad5\x09`4" +
	"\x19\x1aqn]\xed\xe8\x11\x00#`h|\xee?J" +
	"\xfb\xfa\x03EN\x0eu\xd1i\x89\xebV\x9eh{\x9d" +
	"PX\xb1\xe3{\xd9\xe4\xee\x93\x99jU\xb9K\xf4W" +
	"\x01\xd4 \x89\x9aj\x90\xb8\xee5C\xccvv\x85\xc2" +
	"\xf0\x1f\x94!n\xcbBlj\xc8uD;\x08\xa0z" +
	"\xbe'\xb2qu\xc0\xf1\x00\xa3\xce<;@;H\xb4" +
	"a\xcd\x1b\xc3\xc2\xf2C\x9b\"\x8ftk~\x96j\xfe" +
	"k\x86\xc6k\x85\x9a\x9f#\x07\xbc\xca\xd0\xf8}\xc1\x16" +
	"\xe7I\x887\x18\x1a\xefP\xd1YV\xf4\xb7\x09|\x8b" +
	"\xa1\xf1\x9e\x82X\x92\xbdB\xfb3\xfd\xfa]\x86\xc6?" +
	"\xa9Q\xa0l\x14\xda\xdfC\x00\xe3\"\xc3\x86\xec\x12\x8a" +
	"\xec\x12\xdae\x92l\x95\xa1\xd9W\xec\x11e\xd9\x83\xba" +
	"\x9b\xceFZ\xd2\xe9\x16\xf9\xb2[\xb4[(O\xb8`" +
	"\x17m\x99\xadd\xd3q\x11\xb3;Z\x01z\xa8\xe6k" +
	"pG\xf8\xac\x9a\xf7\x0b\x18\x0e#\xc7\xf7\xf2\xb9O\x15" +
	"\xbf\x9fZ\xc2\x15pw\xcb\x1b\x96\xda\xa1\x9ao\xcb\x9d" +
	"\x80\x1b\xcf}\xd9\x9f\xccX]\xbb\x0cY\xa9'f\xa4" +
	"\xe4\xb7\xef\x93\x92\x8f\xcf\xc8\x0dt\xb4!7\xd0\xdb\xee" +
	"\x048\x16\x08\xcfv\xbc\xc3\x9d\xfe&\xe8\xbc\xc7:\x9d" +
	")\xb5\x93\xc0u,\x1e\x03\x8aa\x11\x86~\xb8\xa1c" +
	"\x1b\x89'\x97\xdf(\xb3\xdb\xad]S\xfc\xf4\xb3\x00\xc6" +
	"O\x18\x1a/\x14Lq\x92\xc4z\x9e\xa1\xf1R~\x11" +
	"O=\x0a`\xbc\xc4\xd0x\x95<\x81\x99'\xce\x92\xfe" +
	"\xaf04\xde\xa0\x01\x82\x99)^\x7f\xb4\xe0\x9e\xb2\x92" +
	"\x99\xe2m\x02\xdfah\\$S\xb0\xcc\x14\x7f]\x06" +
	"0\xdech\xac*\x85;8\x95e\xba~\xad\xbb\xf2" +
	"rZ\xae\x9f\xd8f\xdbCk\xce\xe3\xcb.U\x06\x11" +
	"\x14\xa4\xffk8Q#\xf1<\xba0\x87\xbbX\xa7\x90" +
	"uL\xa2\xe6,\xf5iZ\xef;\xba\xe6\xef\\\xf7\xea" +
	"w\xd9\x82?\xebCo\x92/\x86\xff\x0a\x00\x00\xff\xff" +
	"\xd95`v"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_d0b8835cc94b27a5,
		Nodes: []uint64{
			0x893595a82e233617,
			0x93a318cbcbc091a9,
			0xa384105a8098ee80,
			0xa7f3f6376ff296f9,
			0xabcd96301015f42b,
			0xc23f0fc41176a06c,
			0xd2d58bc5d899fc04,
			0xdd64913838d3e1d5,
			0xe276adb0502a9bb2,
			0xf298c7ecc5fc30a7,
			0xf9b3a16dfdc3136d,
		},
		Compressed: true,
	})
}
